### ISSUE TITLE
go get fails

### ISSUE THREAD

**Issue by cleanerx** [improbable-eng/grpc-web#100]
go get -u github.com/improbable-eng/grpc-web/go/grpcwebproxy

../github.com/improbable-eng/grpc-web/go/grpcwebproxy/main.go:91: cannot use logger (type *"github.com/sirupsen/logrus".Entry) as type *"github.com/grpc-ecosystem/go-grpc-middleware/vendor/github.com/sirupsen/logrus".Entry in argument to grpc_logrus.ReplaceGrpcLogger
../github.com/improbable-eng/grpc-web/go/grpcwebproxy/main.go:101: cannot use director (type func("golang.org/x/net/context".Context, string) (*"google.golang.org/grpc".ClientConn, error)) as type proxy.StreamDirector in argument to proxy.TransparentHandler
../github.com/improbable-eng/grpc-web/go/grpcwebproxy/main.go:103: cannot use logger (type *"github.com/sirupsen/logrus".Entry) as type *"github.com/grpc-ecosystem/go-grpc-middleware/vendor/github.com/sirupsen/logrus".Entry in argument to grpc_logrus.UnaryServerInterceptor
../github.com/improbable-eng/grpc-web/go/grpcwebproxy/main.go:103: cannot use grpc_prometheus.UnaryServerInterceptor (type func("golang.org/x/net/context".Context, interface {}, *"google.golang.org/grpc".UnaryServerInfo, "google.golang.org/grpc".UnaryHandler) (interface {}, error)) as type "github.com/grpc-ecosystem/go-grpc-middleware/vendor/google.golang.org/grpc".UnaryServerInterceptor in argument to grpc_middleware.WithUnaryServerChain
../github.com/improbable-eng/grpc-web/go/grpcwebproxy/main.go:105: cannot use grpc_middleware.WithUnaryServerChain(grpc_logrus.UnaryServerInterceptor(logger), grpc_prometheus.UnaryServerInterceptor) (type "github.com/grpc-ecosystem/go-grpc-middleware/vendor/google.golang.org/grpc".ServerOption) as type "google.golang.org/grpc".ServerOption in argument to "google.golang.org/grpc".NewServer
../github.com/improbable-eng/grpc-web/go/grpcwebproxy/main.go:107: cannot use logger (type *"github.com/sirupsen/logrus".Entry) as type *"github.com/grpc-ecosystem/go-grpc-middleware/vendor/github.com/sirupsen/logrus".Entry in argument to grpc_logrus.StreamServerInterceptor
../github.com/improbable-eng/grpc-web/go/grpcwebproxy/main.go:107: cannot use grpc_prometheus.StreamServerInterceptor (type func(interface {}, "google.golang.org/grpc".ServerStream, *"google.golang.org/grpc".StreamServerInfo, "google.golang.org/grpc".StreamHandler) error) as type "github.com/grpc-ecosystem/go-grpc-middleware/vendor/google.golang.org/grpc".StreamServerInterceptor in argument to grpc_middleware.WithStreamServerChain
../github.com/improbable-eng/grpc-web/go/grpcwebproxy/main.go:109: cannot use grpc_middleware.WithStreamServerChain(grpc_logrus.StreamServerInterceptor(logger), grpc_prometheus.StreamServerInterceptor) (type "github.com/grpc-ecosystem/go-grpc-middleware/vendor/google.golang.org/grpc".ServerOption) as type "google.golang.org/grpc".ServerOption in argument to "google.golang.org/grpc".NewServer

**Comment by MarcusLongmuir** [comment]
@cleanerx: Please re-open if [latest master](https://github.com/improbable-eng/grpc-web/commit/be0c2b345bd05d234ac112af05f1f1ae28e306ff) does not fix the issue you're seeing.
