### ISSUE TITLE
Thoughts on how to deploy the GO backend proxy in AWS ECS

### ISSUE THREAD

**Issue by bryanmcgrane** [improbable-eng/grpc-web#1009]
Hello!

This isn't a bug report, but I am really stuck on trying to deploy my web-gRPC go server in AWS as a load-balanced container. I've managed to get the settings dialed in for my pure gRPC server, but the web-gRPC server has two main sticking points that have me realizing I don't fully understand how web-gRPC works. Perhaps you all can help shed some light.

My networking stack looks something like this:

![image](https://user-images.githubusercontent.com/3849234/123641361-6cebbe80-d7df-11eb-8002-4d1862b589c8.png)

Where the **Proxy** is the improbable-eng web-grpc proxy, and the **Amazon Load Balancer** is the piece of infrastructure I'm trying to configure.

**Issue 1: Protocol version**
The image below shows my options for the protocol by which all traffic will be routed to the web-gRPC port. Initially I had selected the second option, but it's hard to tell if things are working correctly due to issue 2.

![image](https://user-images.githubusercontent.com/3849234/123640540-804a5a00-d7de-11eb-8e9b-17b7eb09cde2.png)

**Issue 2: Healthcheck**
I've implemented a gRPC healthcheck endpoint, which works great when I'm load balancing pure gRPC traffic. I simply tell AWS what endpoint to hit and what response code is expected back. This tells my load balancer the container is healthy and enables traffic routing to it.

![image](https://user-images.githubusercontent.com/3849234/123642722-d9b38880-d7e0-11eb-954d-fe34238b9810.png)

In pure gRPC land my healthcheck endpoint will return a status code of 0 (OK) if all is well. My question is, how does the improbable-eng proxy handle status code translations? Would a 0 gRPC status code translate to a 200 HTTP status code?

Thank you for this awesome OSS package. I couldn't build what I needed to without it!

**Comment by ChristopheBougere** [comment]
I'm having a similar issue, trying to configure ALB health check with grpc-web-proxy. The proxy is available from the outside, but as the health check is failing it continuously deregister the target and replace it with a new one.

The issue is, I think, that there is no HTTP endpoint available to query for the healthcheck (see [feature request](https://github.com/improbable-eng/grpc-web/issues/890)), that returns a HTTP 200 without expecting any specific header that cannot be set from the target group health check config (like Content-Type).
The `/metrics` path could be used, but it seems to be broken and [the PR fixing it](https://github.com/improbable-eng/grpc-web/pull/957) has been pending for a while.

**Comment by johanbrandhorst** [comment]
I think with the setup you describe you would need to use the ALB in HTTP/2 mode. The traffic between the proxy and the gRPC server will be HTTP/2 exclusively. I may be missing something but if you're got gRPC health checking working, what else do you need?

**Comment by ChristopheBougere** [comment]
I can confirm that by using the code from master (with changes from https://github.com/improbable-eng/grpc-web/pull/957), the health check works when set to `/metrics` with expected status 200, thanks for merging 👍

**Comment by bryanmcgrane** [comment]
@johanbrandhorst I think you're in the right direction. The main different with the gRPC healthcheck is that it is executed through the "gRPC" protocol shown in image 1, not "HTTP2". If I switch to HTTP2 for my pure gRPC server, I will lose some important load balancing features. The core issue is you can't have a healthcheck use a different protocol than the routed traffic.

The issue that @ChristopheBougere pointed out is that the healthcheck request previously required a specific header in order to work correctly. Without the header, ELB's healtcheck would be passed through to the gRPC server, which would inevitably return an unhealthy status. I'll check #957 fixes the issue for me. This might be exactly what I'm looking for!

**Comment by bryanmcgrane** [comment]
@ChristopheBougere how did you go about enabling this feature? I've pulled the latest commit via `go get github.com/improbable-eng/grpc-web@master`. 

And this is my wrap server function
```
w := grpcweb.WrapServer(s,
		grpcweb.WithWebsockets(true),
		grpcweb.WithOriginFunc(func(origin string) bool { return true }),
		grpcweb.WithWebsocketOriginFunc(func(req *http.Request) bool { return true }))
```

**Comment by ChristopheBougere** [comment]
Here is my Dockerfile:
```
FROM golang:1

RUN go get github.com/improbable-eng/grpc-web/go/grpcwebproxy@189bea5186996e8b5fc900f3f86d82b73ca8d8f4
RUN ls /go/bin
RUN cp /go/bin/grpcwebproxy /usr/local/bin/grpcwebproxy
EXPOSE 8080
ENTRYPOINT [ "grpcwebproxy" ]
```

And here is the command I'm running:
```
[
        `--backend_addr=localhost:${grpcPort}`,
        '--run_tls_server=false', // TLS is done by ALB
        '--enable_request_debug=true',
        '--use_websockets',
        `--allowed_origins=${allowedOrigins.join(',')}`,
        '--backend_max_call_recv_msg_size=8388608', // 8MB
],
```

You might be missing the `--enable_request_debug=true` flag?

**Comment by bryanmcgrane** [comment]
Great thanks for this! And did you end up choosing HTTP2 as the Protocol Version of your Target Group?

**Comment by bryanmcgrane** [comment]
I ended up getting things to work. I'm actually using to Go library as part of my gRPC server. I configure and launch my web gRPC server like so:

```
func startWebGrpcServer(server *grpc.Server, port string) {
	w := grpcweb.WrapServer(server,
		grpcweb.WithWebsockets(true),
		grpcweb.WithOriginFunc(func(origin string) bool { return true }),
		grpcweb.WithWebsocketOriginFunc(func(req *http.Request) bool { return true }))

	// Register http interceptor
	handler := func(resp http.ResponseWriter, req *http.Request) {
		switch req.URL.Path {
		case "/health":
			resp.WriteHeader(http.StatusOK)
		default:
			w.ServeHTTP(resp, req)
		}
	}

	// Create http server to host gRPC web server
	h := http.Server{
		Addr:    ":" + port,
		Handler: http.HandlerFunc(handler),
	}

	// Start gRPC web server
	if err := h.ListenAndServe(); err != nil {
		log.Fatalf("failed starting http server: %v", err)
	}
}
```

My AWS config is as follows:

HTTP1 or HTTP2
![image](https://user-images.githubusercontent.com/3849234/124051832-75f4af80-d9da-11eb-81f3-7df923113f1f.png)

And the healtcheck looks like this
![image](https://user-images.githubusercontent.com/3849234/124051872-84db6200-d9da-11eb-9836-e242b13a3f57.png)

**Comment by ChristopheBougere** [comment]
Glad you made it work, thanks for sharing I might take inspiration!
Yes, in my case as well., I had to configure the target group to HTTP1, I can't explain it...

**Comment by seanwatters** [comment]
> I had to configure the target group to HTTP1, I can't explain it...

I think it may be that `/healthcheck` and `/metrics` expect to use HTTP1, so when you select HTTP2 it gets sad because ALB's HTTP2 option doesn't seem to support HTTP1 calls. 

If the assumptions I'm making are correct, it might be interesting to allow the `/healthcheck` endpoint to also be HTTP2?
