### ISSUE TITLE
Option to set xhr.withCredentials

### ISSUE THREAD

**Issue by aakoshh** [improbable-eng/grpc-web#103]
I'm facing a scenario where I have to talk to a gRPC server that sits behind a reverse proxy which redirects to ADFS for login and sets a http-only session cookie which it will pick up on subsequent requests and attaches an `Authorization` header. The problem is that the transports don't set the cookies with the gRPC invocation, so each POST results in a redirect. 

What do you think about adding an option somewhere which could set the `withCredentials` property of the `XMLHttpRequest` before sending the request?

**Comment by fabxc** [comment]
Looks like the CORS headers set for OPTIONS requests specifically set `Access-Control-Allow-Credentials: true` but the JS/TS implementation hard-codes the opposite (e.g. [here](https://github.com/improbable-eng/grpc-web/blob/master/ts/src/transports/fetch.ts#L37) not allowing to set `withCredentials = true` in the `XMLHTTPRequest`.

This seems like an unnecessary restriction that forces annoying constraints on the rest of the setup. Providing a fully custom transport for this seems like a lot of overhead.

**Comment by jonnyreeves** [comment]
So while we can solve this problem for fetch and xhr based transports, there is nothing that can be done for including cookies on cross-origin WebSocket connections as far as I know.

One workaround would be to make the WebSocketTransport throw an error if you try to construct it in such a way that you request credentials (cookies) be send cross origin (`credentials: 'include'`).

**Comment by MOZGIII** [comment]
Why not let the browser deal with that?
I was looking for a way to pass `credentials: 'include'` to the `fetch` transport - and found this issue. Our usecase is actually sending the corss-origin request with cerdentials - it's allowd by fetch spec.

**Comment by MOZGIII** [comment]
We ended up copying `fetch` transport from tree to our source code and patching it so it passes `include`.
In general it would be great to have an ability to configure various transport-specific parameters if we opt out of transport autodetection by pass transport manually. Seems like a good idea to me - it doesn't require a generic interface deduction of any kind, and just provides a flexible way of using that's already in there.

I can compose a sample PR if you like this idea.

**Comment by johanbrandhorst** [comment]
Sounds good to me, let's get a PR up for discussion.

**Comment by MOZGIII** [comment]
@johanbrandhorst please take a look at #260

**Comment by MOZGIII** [comment]
And #261.

**Comment by jonny-improbable** [comment]
This has been resolved for some time now, you can now configure the `CrossBrowserTransport`.

**Comment by maxmcd** [comment]
Linking directly for others:
https://github.com/improbable-eng/grpc-web/blob/d92a6da4a4d4ecda62101920186fee82c402d637/client/grpc-web/src/transports/http/http.ts#L9-L17
