### ISSUE TITLE
d.ts files not generated

### ISSUE THREAD

**Issue by onthegit** [improbable-eng/grpc-web#1030]
Hello,

when I run the following command 
protoc --plugin=protoc-gen-ts=/usr/local/bin/protoc-gen-ts --js_out=import_style=commonjs,binary:.  --ts_out=service=grpc-web:. -I=. blog.proto

only two files are generated:
blog_pb.js
blog.ts

there are no d.ts files generated.
protoc is v3.14.0

**Comment by johanbrandhorst** [comment]
You might want to raise an issue against https://github.com/improbable-eng/ts-protoc-gen, this repository only maintains the proxy part of the grpc-web implementation.
