### ISSUE TITLE
new release with working support for go modules

### ISSUE THREAD

**Issue by salmanisd** [improbable-eng/grpc-web#1045]
The latest release v0.14.0 (pointing at e757cdbb2b76e6f16963366ad156b95c47372688) doesnt build correctly with go modules.

A later commit (5cc8ddf6e65dc6df78023eff825e97389e08ee02) fixes this issue.

Is it possible to officially release maybe a 0.14.1 that includes this fix?

**Comment by johanbrandhorst** [comment]
This sounds like a great idea. Let me see what I can do.
