### ISSUE TITLE
Enable usage of gRPC-Web without Envoy Proxy in Clients that Support HTTP2

### ISSUE THREAD

**Issue by netpoetica** [improbable-eng/grpc-web#1054]
In cases where cross-browser support and old versions of browsers are not needed, it should be possible to utilize gRPC-Web directly from the client. For example, in Electron apps, where you have the most recent version of Chrome, and can enable experimental flags for ReadableStreams (or implement readable streams yourself, with native patching), using the transports you already provide, this should be entirely possible.

I have experimented with this, where I have a C++ server running with self-signed certs and an ElectronJS app, enabling FetchReadableStreamTransport, and enabling a couple of flags in electron's Chromium instance
```
// For ReadableStreams support (experimental)
app.commandLine.appendSwitch('enable-experimental-web-platform-features', 'true');
// For self-signed certs
app.commandLine.appendSwitch('allow-insecure-localhost', 'true');
app.commandLine.appendSwitch('ignore-certificate-errors', 'true');
```

However, making an HTTP2 fetch request directly to my gRPC server without Envoy in the middle still gives me a somewhat obscure error and the request fails
```
POST https://localhost:50051/ping_pong.PingPong/PingUnary net::ERR_HTTP2_PROTOCOL_ERROR
```

I am not 100% sure the angle to approach this problem from, but I would like to give it a try. I have been working with gRPC and gRPC-Web (and Envoy) for a while now, and I am thinking that maybe the problem here has something to do with the gRPC-Web filtering process that Envoy proxy does? I'm assuming there are some mismatching or unexpected response headers that may be causing this rejection, but any insights from the team that might push me over this hump would be appreciated :) ultimately if there is a non-invasive way to enable this, I think it would be of value.

FWIW, the convenience of gRPC-Web inside of ElectronJS vs. gRPC-js is that it would require no IPC hops. Today, to use gRPC-js, it needs to be done from the node side of electron, which means renderer -> ipc -> node -> gRPC server and back around. gRPC-Web would remove the node and IPC hops and be very convenient, but introducing something like Envoy proxy when your client fully supports HTTP/2 is not ideal.

What I am primarily looking for here is:

1. Is this something that would make sense for this project?
2. Is this a PR you might accept if the solution is clean and minimally invasive?

and if possible, some thoughts from the team here about some of the obstacles one might face trying to achieve this, a.k.a I do not mind doing the work, but the work is not clear to me at the moment.

**Comment by johanbrandhorst** [comment]
Hi, thanks for your issue. I'm a little confused, and wondering if you might be confusing us with the official grpc-web implementation (https://github.com/grpc/grpc-web)? This project is mostly in maintenance mode, and we generally encourage users to use the official implementation.

That said, we do have a transport abstraction and several different implementations: https://github.com/improbable-eng/grpc-web/tree/master/client. Maybe something here will already satisfy your needs?

**Comment by netpoetica** [comment]
Hey Johan! I have worked mostly with the official grpc-web implementation, but having noticed that this project had a variety of transport options, I thought this project is a bit closer to achieving what I am looking for than the official grpc-web lib has -  although you are correct, I could also open the same question to that team, this project seems a bit more adventurous so I thought it may be more likely to take a feature like this.

My thinking was that we may be able to use a custom transport that assumes HTTP/2 functionality exists across client and server, and then gRPC-Web would work just fine. However, it seems that simply utilizing HTTP/2 doesn't actually cut it, and that there is something more Envoy proxy does to enable gRPC-Web. What I am saying in this issue is that it would be great if gRPC-Web worked *without* a proxy in the case where both your client and your server *definitely* speak HTTP/2, but it seems that even when forcing HTTP/2 transmission, these errors still arise. I am however just not quite clear on what the errors are, because the [spec](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-WEB.md) is kind of light on specification. I am hoping that from this issue maybe I can understand what would be required to make gRPC-Web requests without Envoy proxy, and then maybe I could author a transport for this lib that would allow it :)

**Comment by johanbrandhorst** [comment]
I appreciate your desire to remove the need for the proxy, however, ultimately the reason we cannot do pure grpc in the browser is because the existing JS APIs are not powerful enough (no ability to force HTTP/2, no ability to read trailers). It's as simple as that, and that is why there must be a proxy, as the gRPC specification requires both of the aforementioned to be true.

If both sides support HTTP/2 and trailers (like node servers, or react native) I would recommend using the existing transports available for those platforms. If there's nothing else to discuss here, please feel free to close the issue.

**Comment by netpoetica** [comment]
Thanks Johan! When using Electron with this setting:
```
app.commandLine.appendSwitch('enable-experimental-web-platform-features', 'true');
```
it basically tells fetch to use HTTP/2 and enables streaming. You can see some more detail here: https://web.dev/fetch-upload-streaming/

So my thinking here is that while it is true that streaming has not yet been implemented, and we cannot count on the user's default browser having experimental flags enabled, we *can* enable those things in ElectronJS and be sure our user has HTTP/2-by-default fetch and streaming enabled. And in those cases, Envoy *should* be able to be eliminated, no?

**Comment by johanbrandhorst** [comment]
I don't see any mention of supporting trailers in these features, even if you can force HTTP/2. I still don't think it's feasible.

**Comment by netpoetica** [comment]
For people in the future considering this, some reference material:

https://github.com/grpc/grpc/issues/2786
https://bugs.chromium.org/p/chromium/issues/detail?id=422958

Basically until this is implemented in Chromium, or another browser, it is just not an option.

Thank you @johanbrandhorst for considering this :) I will close and maybe we will see something like this in the future.
