### ISSUE TITLE
Node and browser environment support 

### ISSUE THREAD

**Issue by hersentino** [improbable-eng/grpc-web#1058]
**Versions of relevant software used**
v0.14.1

**What happened**
request is not working in node environment (ssr usage)

**What you expected to happen**
A solution to run this library on both node and browser (for ssr usage)

**How to reproduce it (as minimally and precisely as possible)**:
Follow the example in the readme

example :
constructor of my service
```
this.rpc = new GrpcWebImpl(url, {
    transport: grpc.CrossBrowserHttpTransport({ withCredentials: true }),
    debug: false,
});
this.client = new GrpcClient(this.rpc);
```
demo file (run like this: ts-node demo.ts)
```
const service =  new Service("localhost:8000");
services.getAll().then((reponse: any) => console.log(response)).catch((err: any) => {
    console.error(err);
    process.exit(1);
});
```
 tsconfig.js as your example (https://github.com/improbable-eng/grpc-web#nodejs-support)
```
{
  "compilerOptions": {
    "lib": [ "dom", /* ... */ ],
  }
}

```

**Full logs to relevant components**
```
"Error: This environment's XHR implementation cannot support binary transfer.\n"
 'at Object.transport (/node_modules/@improbable-eng/grpc-web/dist/grpc-web-client.js:1:19094)\n'
```

**Anything else we need to know**

Because of this error I had try to fix by using grpc-web-node-http-transport but I get another error :
https://stackoverflow.com/questions/69632094/make-grpc-web-working-in-cross-env-js-library

**Comment by johanbrandhorst** [comment]
Maybe you need to use the node transport: https://github.com/improbable-eng/grpc-web/tree/master/client/grpc-web-node-http-transport?

**Comment by johanbrandhorst** [comment]
Ah I see. Can you detect at runtime which environment you are running in and switch transport maybe? I'm not too experienced with node.

**Comment by hersentino** [comment]
Hi, i find the solution, it was to create two different build for my library, one for the node env that uses NodeHttpTransport, and one for the browser env that uses CrossBrowserHttpTransport.
