### ISSUE TITLE
Example not work. Cannot find package

### ISSUE THREAD

**Issue by 0pt1m1z3r** [improbable-eng/grpc-web#106]
Hi. I try run example.
I do:
```bash
git clone https://github.com/improbable-eng/grpc-web
cd grpc-web/example/

# then I install go from brew and set:
# export GOPATH=$HOME/work
# export GOBIN=$HOME/work/bin

npm install
npm run get_go_deps
npm start
```

and I get the error:
```bash
[0] go/exampleserver/exampleserver.go:18:2: cannot find package "github.com/improbable-eng/grpc-web/go/grpcweb" in any of:
[0] 	/usr/local/Cellar/go/1.9.2/libexec/src/github.com/improbable-eng/grpc-web/go/grpcweb (from $GOROOT)
[0] 	/Users/ezheg/work/src/github.com/improbable-eng/grpc-web/go/grpcweb (from $GOPATH)
```

**Comment by easyCZ** [comment]
Looking into this. If you do `go get github.com/improbable-eng/grpc-web/go/grpcweb` then it will work

**Comment by easyCZ** [comment]
We're expecting the repository is cloned to `$GOPATH/src/github.com/improbable-eng/grpc-web` which is not idea. I'll modify the scripts to call `go get ...` if we don't find it. Thanks for raising

**Comment by easyCZ** [comment]
PR raised to address this #113

**Comment by easyCZ** [comment]
Closing as stale. #113 should resolve this.

**Comment by sgon00** [comment]
I am having the same issue today. I don't think the script does call `go get` properly. 

```
$ npm run get_go_deps

> grpc-web-example@0.1.0 get_go_deps /home/user/grpc-web/example
> ./get_go_deps.sh

Installing go dependencies...
/home/user/grpc-web/example/go is not within a known GOPATH/src
Installing Protobuf to Golang compiler...
```

Note that `dep ensure` does nothing because of `/home/user/grpc-web/example/go is not within a known GOPATH/src`

**Comment by zhouqiangWang** [comment]
I encountered the same issue today, any suggestion?
My error is
`root project import: /Users/xxxx/Documents/GitHub/grpc-web/client/grpc-web-react-example/go is not within any GOPATH/src`

**Comment by johanbrandhorst** [comment]
@zhouqiangWang please try to follow the installation instructions again. You need to clone into a valid GOPATH to be able to build the go parts, for example: `/Users/xxxx/go/src/github.com/improbable-eng/grpc-web/`

**Comment by zhouqiangWang** [comment]
It works, thank you very much~
