### ISSUE TITLE
WithAllowNonRootResource should not take a bool, but an actual function

### ISSUE THREAD

**Issue by oakad** [improbable-eng/grpc-web#1107]
` WithAllowNonRootResource` currently takes `bool` as an argument to internally select between an identity endpoint func and a regex based tail finding one:

https://github.com/improbable-eng/grpc-web/blob/0cc6a6cdf16871e1d60359fcc05351245daf7ff6/go/grpcweb/wrapper.go#L82-L89

However, it will be much more convenient if it took user specified `func(req *http.Request) string` directly, because in most cases we do know the path prefix length in advance and slicing off a fixed known prefix is trivial in complexity as compared to a regex.

Additionally, an user may want to modify the endpoint path in some other way, add some custom rewriting, etc.

Many benefits for a trivial enhancement which consistently fits with other similar options.

**Comment by johanbrandhorst** [comment]
Hi, thanks for your issue! This library is pretty much in maintenance mode, and I don't think we're looking to add new features. Not to mention that this would be a breaking change to our API. Sorry!

**Comment by oakad** [comment]
It's not going to break anything, because it simply can be additional, similarly named, option.

By the way, do you know of any other grpc-web for go implementations? If this one is not maintained, may be something else is.

**Comment by johanbrandhorst** [comment]
I'm afraid I don't know of any other grpc-web implementations in Go. I would recommend using the official Envoy plugin, or using the capabilities available in this wrapper.
