### ISSUE TITLE
Implement the http.RoundTripper interface?

### ISSUE THREAD

**Issue by mholt** [improbable-eng/grpc-web#1117]
We are [looking at using this in the Caddy web server](https://github.com/caddyserver/caddy/pull/4896) (maybe as a plugin, still deciding).

This package heavily leans on the `http.Handler` interface -- which is great. Just wondering though, can this package implement the [`http.RoundTripper` interface](https://pkg.go.dev/net/http#RoundTripper)?

In other words, instead of `ServeHTTP(ResponseWriter, Request)` could you provide this package's functionality with an API of `RoundTrip(Request) Response`?

I'm not super familiar with gRPC or gRPC-web. My feature request is not a requirement; we can probably use the current APIs, but I was just wondering if from your experience this was technically feasible. If so, it could open some more possibilities to Caddy users -- that's all.

**Comment by johanbrandhorst** [comment]
Hi Matt, so nice to see you here! I would recommend against relying on this as a library in Caddy - this repository is in maintenance mode and you're far better off rewriting the logic you need on your own. Most of the interesting stuff is in https://github.com/improbable-eng/grpc-web/blob/master/go/grpcweb/grpc_web_response.go. I wouldn't want to put you in a situation where you'd have to rely on us to get fixes into Caddy. I'd be happy to advise on any grpc-web questions, you can find my email in my git history, or you can reach out to me on Twitter (@johanbrandhorst) or Gophers Slack directly. Have a good day!

**Comment by mholt** [comment]
@johanbrandhorst Thanks for the consideration!

Totally understandable. What I am doing for now is I put this functionality in an unofficial third-party repository under my own account: https://github.com/mholt/caddy-grpc-web

It works well as far as I can tell from my own testing and someone else who is using it. So it's a good starting point. And if it grows more popular I can probably work out a more robust, self-contained solution that doesn't depend on your lib.

Thanks very much for making this though. I was pleased how easy it was to make work!
