### ISSUE TITLE
grpcwebproxy websocket connection fails with specific origin

### ISSUE THREAD

**Issue by kdchouhan** [improbable-eng/grpc-web#1119]
**Versions of relevant software used**
0.15.0
**What happened**
grpcwebproxy websocket connection fails when specific origin is specified in allowed_origins list. It works when I allow all origins in grpcwebproxy
**What you expected to happen**
The connection should work since origin was in the list
**How to reproduce it (as minimally and precisely as possible)**:
Tru using websocket for grpc-web and set origin in allow_origins list
**Full logs to relevant components**

**Anything else we need to know**

**Comment by johanbrandhorst** [comment]
Could you provide a test case that reproduces the issue? The logic for this is here: https://github.com/improbable-eng/grpc-web/blob/90ce72a31aa7bdfd6eae03fc735953902949c0de/go/grpcweb/wrapper.go#L117. You could try cloning the repo and adding some debug logging if you want.

**Comment by kdchouhan** [comment]
Thank you @johanbrandhorst  for quick response. As mentioned in wrapper.go docs, it actually checks the host header not the origin to check the CORS request for websocket call. I had to add 2 origin in my list, one for grpc-web calls, which contains origin headers value(i.e. starts with https://) allowed and another one for grpc-web websocket calls, which contains the host header value(i.e. just the host name).
It works with this configuration. This is how my value of allowed_origins look like:
--allowed_origins=https://app.example.com,app.example.com
