### ISSUE TITLE
QUIC and HTTP3 support

### ISSUE THREAD

**Issue by lbensaad** [improbable-eng/grpc-web#1121]
Can this grpc-web implementation run over QUIC/HTTP3?
And what about the grpc go  wrapper and proxy, do they support QUIC/HTTP3?

**Comment by johanbrandhorst** [comment]
The client-side implementation just uses browser APIs, so it should support HTTP/3 if the browser does. The server side will not support HTTP/3 unless you use some custom HTTP library for it, as the standard library HTTP library in Go does not (yet).
