### ISSUE TITLE
Build a fully working example with React

### ISSUE THREAD

**Issue by easyCZ** [improbable-eng/grpc-web#114]
In order to better cater for the web development community, we should provide better documentation including a fully working example with React as it is one of the most popular frontend frameworks at the moment.

### Spec
- [ ] Should be clone, install and ready to go
- [ ] Should demonstrate both unary and streaming requests
- [ ] Should be well written and documented

### 
Example could be based on the standard ToDo List or something more elaborate - could be a Hacker News reader or a Reddit viewer to demonstrate the capability

**Comment by ishitatsuyuki** [comment]
There's one example in Vue.js with GAE/Go. https://qiita.com/koki_cheese/items/369cdfc6e3250185ccdb

I'm also working on a side project utilizing the same tools.

It doesn't really need to be React.

**Comment by 1mentat** [comment]
This would be really useful to me. I'm looking at ways to modernize some applications with gRPC and APIs. Working with grpc-gateway is good for service to service backward compatibility but would really like to write grpc "native" web apps as well and a clearer example of React integration would be a huge help.

**Comment by easyCZ** [comment]
Raised #133. An example project is available at https://github.com/easyCZ/grpc-web-hacker-news/

**Comment by easyCZ** [comment]
Closing. Reference to the example merged in #133.
