### ISSUE TITLE
grpcwebproxy - Help Proxying existing GRPC service

### ISSUE THREAD

**Issue by effofxprime** [improbable-eng/grpc-web#1143]
**Versions of relevant software used**
Current source version as of Dec. 31st 2022.
**What happened**
"invalid gRPC request method"
The above message is displayed when trying to query.

**What you expected to happen**
I am expecting output in JSON format to show in the web browser.  I am able to query the grpc web service with a cli tool.
<img width="938" alt="image" src="https://user-images.githubusercontent.com/53557/210155578-c1529743-d60d-45c5-aaf6-2fd07897038a.png">

I believe this would be the format in order to query it in the browser.
`https://jackal-grpc-web.thesilverfox.pro:8443/cosmos.staking.v1beta1.Query/Validators?status=BOND_STATUS_BONDED`
However I feel like I am misunderstanding the use and so I am uncertain if the above is the proper way. 

**How to reproduce it (as minimally and precisely as possible)**:
Attempt to run a query via a URI to get JSON output in the browser.

**Details**
It's quite possible I've misunderstood the intended use of the `grpcwebproxy`.  
I am running the proxy like so:
```bash
 grpcwebproxy --allow_all_origins --backend_addr=localhost:9090 --backend_tls=false --backend_tls_noverify --server_tls_key_file=/etc/letsencrypt/live/jackal-grpc-web.thesilverfox.pro/privkey.pem --server_tls_cert_file=/etc/letsencrypt/live/jackal-grpc-web.thesilverfox.pro/fullchain.pem --enable_health_endpoint --enable_request_debug
```

Both HTTP and https are enabled.  Attempting to go to /debug/{events,requests} result do not display anything.  I've tried from both the 8443 and 8080 ports.  I get a `not allowed` message in the browser.

The GRPC service I am running is coming from a Cosmos based blockchain.  It hosts a GRPC service on port 9090, no TLS options.  It also is able to host a GRPC-WEB service on 9091, but I am trying to avoid using envoy in favor of grpcwebproxy.  I was under the impression that using the `grpcwebproxy` I would be able to avoid using envoy and reverse proxy https requests for grpc from the web to the service in question.

All I have done is attempt to use the grpcwebproxy.  Maybe I am missing further steps?

**Comment by johanbrandhorst** [comment]
Hi, this seems to be a fairly simple confusion - grpc-web requires you to use `POST`, as per the spec: https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-WEB.md. If you just load the URL in the browser it will send a `GET` request, which will result in this error. You can't load the URL directly in a browser, but you could write a little JS client that makes a POST request to the URI.

Hope that helps!
