### ISSUE TITLE
Is there any way to use Nginx or Envoy with this project?

### ISSUE THREAD

**Issue by fordneild** [improbable-eng/grpc-web#1166]
My team has used this library extensively on the client. They do not want to migrate off of this project since it is a dependency of ts-proto. I would like to replace our custom go proxy with an industry standard proxy like envoy or nginx (as a K8s ingress), but im not sure its possible. Is it possible? Anyone know of any docs?

**Comment by fordneild** [comment]
Yes, Envoy can convert grpc-web to grpc via a envoy filter. Contour sets this up by default

**Comment by sidanas22** [comment]
what about nginx? I am using nginx to serve an angular application that uses this library but I am getting CORs issues.
