### ISSUE TITLE
Question: What is the status of `go/grpcwebproxy` project?

### ISSUE THREAD

**Issue by tomer-ben-david** [improbable-eng/grpc-web#1170]
Hi,

I was looking at: https://github.com/improbable-eng/grpc-web/tree/master/go/grpcwebproxy

But then I saw that the parent project grpc-web says that it has moved to https://github.com/grpc/grpc-web and that updated project says that its default proxy is now envoy.  

So, my question is should I be using go/grpcwebproxy is it actively maintained?

**Comment by vsly-ru** [comment]
envoy is a hell to configure. I've spent several hours with **no luck**, trying to config envoy in a https mode. 
While go/grpcwebproxy was ready in like 5-10 minutes (most of which is reading help) and was working like a charm.

**Comment by tomer-ben-david** [comment]
Had this feeling about envoy I guess envoy configuration is a whole world of itself - but then why configure when we can just use the go/grpcwebproxy which is simple and also we have the source code right in front of us to use and pull request in any case needed.

**Comment by tomer-ben-david** [comment]
Had this feeling about envoy, I guess envoy configuration is a whole world of itself – but then why configure when we can just use the go/grpcwebproxy which is simple, and also we have the source code right in front of us to use and pull request in any case needed.
