### ISSUE TITLE
npm package needs update

### ISSUE THREAD

**Issue by jwahlin** [improbable-eng/grpc-web#128]
I am using your npm grpc-web-client package which depends on the npm browser-headers package. A fix for parsing trailers was added to browser-headers about a month ago, but it appears that the grpc-web-client package is still depending on an older version of browser-headers.

Can this be updated?

If there is a better place to request this, please let me know.

**Comment by easyCZ** [comment]
This was updated recently in https://github.com/improbable-eng/grpc-web/commit/ac277bc74439abe1836697f5e63b6d38978d8c40 to v0.4.0. Please let me know if you're still having issues and I'll re-open.
