### ISSUE TITLE
Release new version of grpc-web-client

### ISSUE THREAD

**Issue by lifk** [improbable-eng/grpc-web#131]
Hi,

Last version fo rgpc-web-client seems to be from September, some changes have already been merged since then so it would be great if a new version could be released.

Thanks.

**Comment by easyCZ** [comment]
Hi @lifk,

Thanks for raising. We're looking to cut a release soon!

**Comment by easyCZ** [comment]
@MarcusLongmuir could we cut a release?

**Comment by easyCZ** [comment]
2 releases have been cut. 0.4 which includes general bug fixes and improvements and 0.5 which adds client style API. Closing.

**Comment by hartmut-co-uk** [comment]
@easyCZ would you have a ref for
> adds client style API
? 
..if it's going to be in release notes, never mind then.. :-)

**Comment by easyCZ** [comment]
client style API: https://github.com/improbable-eng/grpc-web/commit/9cca7d4530683dc49fc10cf627309ce4be119af5
