### ISSUE TITLE
Semver incompatibility

### ISSUE THREAD

**Issue by Ky6uk** [improbable-eng/grpc-web#139]
I have tried to upgrade `grpc-web-client` from `v0.3.1` to new minor version `v0.5.0`. That shouldn't break the current API but it does. `Code` and `BrowserHeaders` are not importable directly from the package any more.

**Comment by easyCZ** [comment]
Hi @Ky6uk,

Sorry for the issues this has caused you. Unfortunately for a library pre 1.0 we cannot make any guarantees on versioning. When in 0.x.y, x tends to be a potentially breaking change while y tends to backwards compatible. 

https://github.com/dbrock/semver-howto
