### ISSUE TITLE
Can not deserialize via browser - web-proxy

### ISSUE THREAD

**Issue by saga-dash** [improbable-eng/grpc-web#144]
In version 0.5.0, errors occur in the browser, but Nodejs works fine.

server: grpc-node, grpc-swift
proxy: grpc-web-proxy
client:  grpc-web-client(browser , nodejs)

node server log(same swift server)
```
E0227 16:58:53.826440000 123145363775488 call.cc:942]                  Invalid entry in accept encoding metadata: ' deflate'. Ignoring.
```

[Old version proxy](https://hub.docker.com/r/jfyne/docker-grpcwebproxy/) it was deserializable via browser - web-proxy(Metadata could not be taken ...)
I do not know the version used by this docker image .. May be this 0ab7201b53447db59d63ff3a95173e565baae10a

**Comment by jonahbron** [comment]
I'm seeing this same error, and it seems to cause this error in the proxy console output:

    rpc error: code = Internal desc = stream terminated by RST_STREAM with error code: INTERNAL_ERROR

**Comment by jonahbron** [comment]
Confirmed, when I use a Node client it works fine.  But sending traffic through the grpcwebproxy triggers these from my server:

    E0227 17:22:20.300875438       1 call.cc:920]                Invalid entry in accept encoding metadata: ' deflate'. Ignoring.
    E0227 17:22:20.301035258       1 call.cc:920]                Invalid entry in accept encoding metadata: ' br'. Ignoring.

And this error from the proxy:

    time="2018-02-27T17:22:20Z" level=error msg="finished streaming call with code Internal" error="rpc error: code = Internal desc = stream terminated by RST_STREAM with error code: INTERNAL_ERROR" grpc.code=Internal grpc.method=SayHello grpc.service=helloworld.Greeter grpc.start_time="2018-02-27T17:22:20Z" grpc.time_ms=1.478 span.kind=server system=grpc

**Comment by jonahbron** [comment]
I'm not sure that my Internal error is related to the accept encoding entry error, I'm going to file a separate issue.

**Comment by saga-dash** [comment]
I thought that encoding can be changed with grpc-web-proxy option.

And this is due to the implementation of grpc-swift ...
I get an error by adding user-agent twice with grpc-web-client and grpc-web-proxy, but will this be okay?

**Comment by saga-dash** [comment]
I misunderstood about accept-encoding and proxy.

The question about grpc-web-proxy is that there are multiple user-agents.

**Comment by saga-dash** [comment]
Temporary fix up to grpc-swift fix.
saga-dash@1f6e4b4730668ca229e2128b2f274761de6df3c0

**Comment by jonahbron** [comment]
@saga-dash I notice that the errors only complain about `br` and `deflate`.  Maybe you could filter the accept-encoding down to only `gzip`, instead of removing the header entirely?

**Comment by saga-dash** [comment]
@jonahbron Have you already tried this?
https://hub.docker.com/r/sagadash/grpc-web-proxy/

**Comment by jonahbron** [comment]
@saga-dash I haven't, does it work?  I'm currently using this one:

https://store.docker.com/community/images/jfyne/docker-grpcwebproxy/builds

It's an older build (October), but it does work.  There must have been a regression since then.

**Comment by jonny-improbable** [comment]
@saga-dash I believe this was the same issue as #145, please re-open if this issue still persists from the latest master.
