### ISSUE TITLE
Status code used when network error occurs is inconsistent with Go gRPC Client

### ISSUE THREAD

**Issue by johanbrandhorst** [improbable-eng/grpc-web#149]
Hi,

As part of my downstream project [`gRPC-Web for Go`](https://github.com/johanbrandhorst/protobuf/)'s migration to the new websocket transport, I developed a testing framework that allows me to run the same tests against the gRPC-Web client and the Go gRPC client. Please see the source ([gRPC-Web](https://github.com/johanbrandhorst/protobuf/blob/21e69814b025a0e57181cddb093908f3d934c8c1/test/client/main.go#L337), [gRPC-Go](https://github.com/johanbrandhorst/protobuf/blob/6e3e35cbb49a72e95c4815ce87d1256f5304e630/test/webdriver_test.go#L180)) for more details.

Through this, I've noticed there's an inconsistency when it comes to returned status codes from the client when the network connection is dropped. gRPC-Go returns [`codes.Unknown`](https://github.com/grpc/grpc-go/blob/fa28bef9392c6c3e28e75389d8be8a6797561f57/transport/http_util.go#L268), and gRPC-Web returns [`codes.Internal`](https://github.com/improbable-eng/grpc-web/blob/eb398c2f9233171176ceebb2353148224a0e58a0/ts/src/client.ts#L165).

Ideally the gRPC-Web client should return `codes.Unknown`, in my opinion.

**Comment by mingfang** [comment]
what does `codes.Unknown` even mean?
I'm getting this error now
```
 time="2020-05-08T08:39:10Z" level=error msg="finished streaming call with code Unknown" error="rpc error: code = Unknown desc = " grpc.code=Unknown grpc.method=transaction grpc.service=session.SessionService grpc.start_time="2020-05-0 8T08:39:10Z" grpc.time_ms=2.136 span.kind=server system=grpc                                                                                                                                                                               ```
