### ISSUE TITLE
Not working in Node.js environment?

### ISSUE THREAD

**Issue by joemphilips** [improbable-eng/grpc-web#151]
I've been trying to use `grpc-web-client` from Node.js environment using TypeScript

But when I try `import {grpc} from 'grpc-web-client'` , it will cause errors like
```
node_modules/browser-headers/lib/BrowserHeaders.d.ts:24:18 - error TS2304: Cannot find name 'Headers'.
```
I specified all `"es2017"` , `"es6"` and `"es5"` in `tsconfig.json` but still having the same Error.
Am I missing something here? thanks.

**Comment by easyCZ** [comment]
Hi @joemphilips,

`browser-headers` are a dependency of `grpc-web` and should be available. Would you be able to provide more detail on your setup? Ideally small sample repository which manifests the problem? This will allow me to look into it better and see how we can fix this issue for you.

**Comment by joemphilips** [comment]
Thanks for kind response.
I have managed to debug by myself.
Problem was that I was not specifying `dom` (which seems to contain the definition for `Headers`) in the `"lib"` option for my `tsconfig.json` .
`dom` is usually injected by default if I didn't specify any other option, but this time I was specifying `es2017` as my `lib` , so the compiler was complaining.

So it was not an issue for this library, but maybe it is nice to mention in `README.md` that user must include `dom` as their `lib` ?

**Comment by easyCZ** [comment]
Glad it's working now. 

That's a good idea. Would you like to create a PR and improve the readme?

**Comment by joemphilips** [comment]
I made a PR #156 so closing this issue.
