### ISSUE TITLE
Clarify the nececity to run dep

### ISSUE THREAD

**Issue by MHDante** [improbable-eng/grpc-web#152]
Due to the fact that the package depends on gRPC internals, the readme (on the proxy, at least) should mention that one needs to run `dep ensure` to get the right version of the repository installed.

Failing to do so will result in the following error (as grpc-go's master branch was updated 6 days ago) :

```
# github.com/mwitkow/grpc-proxy/proxy
..\..\mwitkow\grpc-proxy\proxy\handler.go:63:30: undefined: transport.StreamFromContext
```

I understand that this is a known Go procedure, but given that the proxy may be used by peeps who're writing services in other languages, it could help save us a couple hours. :)

**Comment by n0mer** [comment]
@MHDante do you think that #153 can be fixed by running `dep ensure` somehow?

**Comment by n0mer** [comment]
twimc: this `Dockerfile` worked

```dockerfile
from golang:alpine as builder
RUN apk --no-cache add git
RUN go get -v -u github.com/golang/dep/cmd/dep
RUN go get -v github.com/improbable-eng/grpc-web/go/grpcwebproxy ; exit 0
RUN cd src/github.com/improbable-eng/grpc-web && dep ensure
RUN go get -v -u github.com/improbable-eng/grpc-web/go/grpcwebproxy

from alpine
RUN apk --no-cache add ca-certificates
WORKDIR /
COPY --from=builder /go/bin/grpcwebproxy .
CMD ["/grpcwebproxy", "--backend_addr=localhost:8080", "--run_tls_server=false"]
```

**Comment by johanbrandhorst** [comment]
I'm closing this as it's only required if you want to build grpcweb-proxy. Release 0.6.3 includes binary versions of the proxy: https://github.com/improbable-eng/grpc-web/releases/tag/0.6.3
