### ISSUE TITLE
grpcwebproxy does not compile [anymore]

### ISSUE THREAD

**Issue by cristipp** [improbable-eng/grpc-web#153]
```
$ go version
go version go1.9.2 darwin/amd64
$ go get -u github.com/improbable-eng/grpc-web/go/grpcwebproxy
# github.com/mwitkow/grpc-proxy/proxy
../../../../go/src/github.com/mwitkow/grpc-proxy/proxy/handler.go:63:30: undefined: transport.StreamFromContext
```

`server_tls.go` depends on the URL `"github.com/mwitkow/go-conntrack/connhelpers"`, https://github.com/improbable-eng/grpc-web/blob/master/go/grpcwebproxy/server_tls.go#L7. Presumably `mwiktow` has updated their repo, breaking grpcwebproxy in the process.

**Comment by n0mer** [comment]
@mwiktow can you please comment on this?

**Comment by cristipp** [comment]
FYI, https://github.com/ckarenz suggested using https://golang.github.io/dep/ to constrain dependencies versions. I have not got around to make this work.

> GRPC broke the contract in this change: https://github.com/grpc/grpc-go/commit/57640c0e6fd5e562b3a53f6b72738759165c80e1

> You can fix it by pinning your dependency via `dep` to this change: `031ee13cfe2f6f9f3ea0bb7d4243cd59780f0355`

> The format in your `Gopkg.toml` file is as follows:
```[[constraint]]
  name = "github.com/grpc/grpc-go"
  revision = "031ee13cfe2f6f9f3ea0bb7d4243cd59780f0355"```

**Comment by n0mer** [comment]
@cristipp https://github.com/improbable-eng/grpc-web/issues/152#issuecomment-376973723

**Comment by cristipp** [comment]
Thanks. That fixes it.

**Comment by trusktr** [comment]
For anyone stumbling here, this commit also describes how to fix `undefined: transport.StreamFromContext` (or why there's no bin file after go install): https://github.com/jfyne/docker-grpcwebproxy/commit/da712301bde103014e7becbac0fa298384bf622f

For example, I had this problem with http://github.com/improbable-eng/grpc-web, and the following worked:

```js
go get -u github.com/improbable-eng/grpc-web/go/grpcwebproxy
cd $GOPATH/src/github.com/improbable-eng/grpc-web
brew install dep # install golang/dep somehow
dep ensure
go get -u github.com/improbable-eng/grpc-web/go/grpcwebproxy
```

After that `$GOPATH/bin/grpcwebproxy` was available.
