### ISSUE TITLE
Release nightly on NPM under grpc-web-client@next

### ISSUE THREAD

**Issue by easyCZ** [improbable-eng/grpc-web#157]
In order to get better feedback on features being shipped, we should make it possible to consume `grpc-web-client` from NPM directly with regular changes from `master`.

I propose we start building `grpc-web-client` on every commit and release it as `grpc-web-client@next` on NPM.

## How?
* Add a build step to [Travis and release ](https://docs.travis-ci.com/user/deployment/npm/)on successful unit & integration tests. 
* Make use of tags - https://jbavari.github.io/blog/2015/10/16/using-npm-tags/

## How often?
Every commit to master.

## What will happen with regular versioned releases?
Nothing will change with the current version release process. 

## Why @next?
Inspired by other open-source projects:
* https://www.typescriptlang.org/docs/handbook/nightly-builds.html

**Comment by johanbrandhorst** [comment]
What is the status of this?

**Comment by johanbrandhorst** [comment]
Specifically a beta release for the websocket stuff would be nice
