### ISSUE TITLE
Improbable JS client worker?

### ISSUE THREAD

**Issue by lazydino** [improbable-eng/grpc-web#168]
Our game is done in WebGL. Would this project help me build a browser side JavaScript improbable client worker that communicates with a 'managed worker', either done in node or C++? What would be the changes of workflow using spatialOS CLI tool ?  Does the current implementation version 12 support external client worker and managed worker done in two different languages? Is improbable schema language compatible with .proto ?

**Comment by easyCZ** [comment]
Hi @lazydino,

This project is independent of [SpatialOS](https://improbable.io/games). It does not implement any of the SpatialOS concepts. The general use case is to send grpc messages from the browser to a grpc server. 

For more details and support help, please use the [SpatialOS forum](https://forums.improbable.io/).
