### ISSUE TITLE
Use 'grpc-web-client ' can't connect for more than 10 seconds.

### ISSUE THREAD

**Issue by AaronJin2013** [improbable-eng/grpc-web#171]
When I connect the grpc server，it's can keep long connect，and use debug，it's return
```
MozXHR.onStateChange 3
MozXHR.XMLHttpRequest.HEADERS_RECEIVED 2
MozXHR.onProgressEvent:  
Uint8Array [ 0, 0, 0, 0, 0 ]
rawOnMessage 
Object { value: false }
```
But when it's 10 seconds，it's return
```
MozXHR.onStateChange 4
MozXHR.XMLHttpRequest.HEADERS_RECEIVED 2
MozXHR.onLoadEvent
grpc.onEnd
grpc.headers only response  null 
Array []
rawOnEnd 13 Response closed without grpc-status (Headers only) 
Object { headersMap: {…} }
GRPCrequest.onEnd 13 Response closed without grpc-status (Headers only) 
Object { headersMap: {…} }
```
I want to maintain a long-term connection. Is there any way?

**Comment by AaronJin2013** [comment]
It's the grpcwebproxy timeout setting，need set it on server

**Comment by jonahbron** [comment]
@AaronJin2013 Thank you for posting the solution, I ran into this issue as well.  More specifically, you can set the `--server_http_max_write_timeout` command-line flag to a value that [time.ParseDuration](https://golang.org/src/time/format.go?s=37192:37238#L1255) can read.  I set it to `1h` in my case.
