### ISSUE TITLE
Cannot find module 'grpc-web-client'

### ISSUE THREAD

**Issue by gertcuykens** [improbable-eng/grpc-web#179]
![image](https://user-images.githubusercontent.com/863731/39103569-d348f008-46ab-11e8-99a3-b980325a20aa.png)

![image](https://user-images.githubusercontent.com/863731/39103467-1f1e29ae-46ab-11e8-9101-81f30c422305.png)

```
% make
protoc -I=. grpc.proto \
                --js_out=import_style=commonjs,binary:./pkg \
                --plugin=protoc-gen-ts=/Users/gert/node/bin/protoc-gen-ts \
                --ts_out=service=true:./src
% tsc
src/grpc_pb_service.d.ts(5,20): error TS2307: Cannot find module 'grpc-web-client'.
% npm list --depth=0
ts@0.0.0 /Users/gert/go/src/bitbucket.org/gertcuykens/lib/ts
├── @types/google-protobuf@3.2.7
├── browser-headers@0.4.0
└── grpc-web-client@0.5.0

%
```
grpc-web-client doesn't seem to be able to be found.

Also note that the `npm -i grpc-web-client` version seem to be out of sync with master 0.6.0

Their is also a version mismatch between `"@types/google-protobuf": "^3.2.5"` and `"google-protobuf": "^3.2.0"` in package json

**Comment by johanbrandhorst** [comment]
This looks like an environment problem, and this isn't the forum for debugging this kind of thing. Please join the slack channel (or any TypeScript debugging forum) for help in getting your environment set up correctly.

**Comment by RoanBrand** [comment]
I am having the same issue, trying to upgrade from `grpc-web-client` (0.6.3)

Ran:
`yarn remove grpc-web-client` then `yarn @improbable-eng/grpc-web`
I also upgraded `google-protobuf` (3.12.4) & dev dependency `ts-protoc-gen` (0.7.7)

Using `--ts_out=service=true:${OUT_DIR}`,` when compiling I still get `*_service.d.ts` files with `var grpc = require("grpc-web-client").grpc;`

Any ideas?
