### ISSUE TITLE
server_tls_client_ca_files flag supportted?

### ISSUE THREAD

**Issue by sulliwane** [improbable-eng/grpc-web#18]
Is there already support for this flag?

my grpc server is running on localhost with a self-signed certificate (issued for localhost) but giving the rootCA.pem to grpcwebproxy doesn't work:
```bash
./bin/grpcwebproxy --server_tls_cert_file=/home/me/crt/localhost.crt --server_tls_key_file=/home/me/crt/localhost.key  --server_tls_client_ca_files=/home/me/crt/rootCA.pem --backend_addr=localhost:50052
```
complains:
```bash
Failed to dial localhost:50052: connection error: desc = "transport: x509: certificate signed by unknown authority"; please retry
```
Many thanks

**Comment by sulliwane** [comment]
I added the option ```--backend_tls=true```, and now my **grpc server** is throwing:
```
ssl_transport_security.c:947] Handshake failed with fatal error SSL_ERROR_SSL: error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number.
chttp2_server.c:123]        Handshaking failed: {"created":"@1491644898.916048787","description":"Handshake failed","file":"../src/core/lib/security/transport/security_handshaker.c","file_line":274,"tsi_code":10,"tsi_error":"TSI_PROTOCOL_FAILURE"}
```
and **grpcwebproxy** throws:
```
INFO[0013] transport: http2Client.notifyError got notified that the client transport was broken EOF.  system=system
```

**Comment by sulliwane** [comment]
I think I mixed these two flags:
1. ```--server_tls_client_ca_files```
2. ```--backend_tls_ca_files```

What I need for my **grpcwebproxy** to connect to backend grpc server that is using self-signed cert is the second flag I guess?

Still, starting  **grpcwebproxy** with the "correct" flag still complain with:

> Failed to dial localhost:50052: connection error: desc = "transport: x509: certificate signed by unknown authority"; please retry.  system=system

I'm using ```--backend_tls_noverify=true``` for now.

**Comment by jonnyreeves** [comment]
Closing this issue as it's a question (and it would appear no-one has the answer) - may I suggest you post on stackoverflow using the [grpc-web](https://stackoverflow.com/questions/tagged/grpc-web) tag?

Thanks :)
