### ISSUE TITLE
Is grpcwebproxy implementing last grpc-web protocol specs?

### ISSUE THREAD

**Issue by sulliwane** [improbable-eng/grpc-web#19]
Hello,

I still didn't try the grpcwebproxy, but I'd like to make sure about this point:

- Is grpcwebproxy implementing last grpc-web protocol specs?

Many thanks!

**Comment by mwitkow** [comment]
Yes. It is implementing the https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-WEB.md, with one exception: it doesn't support the base64 encoding which may be needed for really legacy browsers.
