### ISSUE TITLE
Compatibility with client stubs generated with gprc/grpc-web

### ISSUE THREAD

**Issue by atecce** [improbable-eng/grpc-web#192]
Hai!

I've generated a JavaScript client stub using the tools at `grpc/grpc-web` and have decided to pivot to this project when faced with the choice between deploying a custom configuration of nginx running in a Docker container configured to call a dotnet framework gRPC service running on the host as a gateway or simply dropping a Go binary on my host and having it connect to that service.

I've successfully built `grpcwebproxy` and it appears to connect to my service, however, when I attempt to use the client stub I generated in `grpc/grpc-web`, I get no response. No feedback whatsoever in the logging of either `grpcwebproxy` or the JavaScript console.

In a question, will the client stubs generated over in that project successfully connect to `grpcwebproxy`? Or do I have to use the tools here to generate the TypeScript stub?

**Comment by jonnyreeves** [comment]
PTAL at https://github.com/improbable-eng/ts-protoc-gen

**Comment by atecce** [comment]
right. so i’m going to take this as a “yes. the proxy is coupled to our typescript stub generator and is not compatible with grpc/grpc-web”

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by johanbrandhorst** [comment]
Relevant issue #162.

**Comment by atecce** [comment]
yes! very relevant. ty
