### ISSUE TITLE
Connection timeout using fetch-transport is not properly caught in Chrome

### ISSUE THREAD

**Issue by PatrickLehnerXI** [improbable-eng/grpc-web#195]
**To reproduce:**
* Use grpc-web-client@0.6.2, run the frontend in Chrome 66
* use `grpc.invoke()` to stream data from a grpc-web-proxy backend (with default timeout config, i.e. 10sec)
* open the connection and wait for timeout

**Expected behavior:**
* error is caught by grpc-web-client, and `onEnd` callback is invoked with appropriate error code

**Observed behavior:**
* error is **not** caught
* `onEnd` callback is **not** invoked
* the following two error outputs are printed to the browser console:
```
Failed to load resource: net::ERR_SPDY_PROTOCOL_ERROR
Uncaught (in promise) TypeError: network error
    Promise.then (async)		
    e.pump	@	fetch.js:26
    (anonymous)	@	fetch.js:36
    Promise.then (async)		
    e.pump	@	fetch.js:26
    (anonymous)	@	fetch.js:36
    Promise.then (async)		
    (... repeats some more ...)
```

**Additional Notes:**
* the same code (with grpc-web-client@0.6.2) works as expected in current Firefox
* the same code usage works when building the frontend against grpc-web-client@0.6.0 instead
* the error is caught in Chrome when adding an additiona `.catch()` after the `this.reader.read().then()` in [`fetch.js`@709b59 on line 47](https://github.com/improbable-eng/grpc-web/blob/709b592779c35e17f581f9bf866f4cac4b0b93fb/ts/src/transports/fetch.ts#L47)
* i therefore suspect that this needs additional error handling after the changes of #184

**Comment by johanbrandhorst** [comment]
This is a quality issue :100:

**Comment by Runar1** [comment]
PR has already been up for a while. Take a look at #189

**Comment by PatrickLehnerXI** [comment]
yup, definitely a dupe of #189 -- thanks for the hint, @Runar1 !
