### ISSUE TITLE
501 response...grpcwebproxy debug flag?

### ISSUE THREAD

**Issue by sulliwane** [improbable-eng/grpc-web#20]
Hello,

After solving the TLS certs related erros, I'm now sending a fetch request to the grpcwebproxy using:
```js
fetch('https://localhost:8443/package.service/method', {
        method: 'POST',
        mode: 'no-cors',
        headers: {
          'Content-Type': 'application/grpc-web',
          'X-GRPC-WEB': '1',
        },
        body: Message.encode(message).finish(),
      })
```
But I get a 501 status reply, and no reaction in my grpc server log.
![screenshot from 2017-04-08 19-57-08](https://cloud.githubusercontent.com/assets/1733686/24828707/9c050488-1c95-11e7-81c1-39e44b710705.png)

So is there a way to show the debug log from the grpcwebproxy in the console? Or what are the debug capabilities of grpcwebproxy? 

Thank you :)

**Comment by mwitkow** [comment]
Well, the typical way of debugging Go programs is... printf ;)

You can easily tweak the grpcwebproxy handling method, it's here:
https://github.com/improbable-eng/grpc-web/blob/master/go/grpcwebproxy/main.go#L77

`fmt.Printf("got request: %v", req)` should do the trick.

**Comment by sulliwane** [comment]
Looking at the chrome dev-tools network tab, this is **the preflight request** (```Request Method:OPTIONS```) which is actually failing with 500.
![screenshot from 2017-04-11 16-12-41](https://cloud.githubusercontent.com/assets/1733686/24899114/bd2b7690-1ed1-11e7-8886-746d0486e5cd.png)

As the preflight request do not have the ```content-type``` header field, the grpcwebproxy method ```IsGrpcWebRequest``` returns ```false```.

I believe the preflight request should not be tested with ```IsGrpcWebRequest``` method....What do you think?

**Comment by sulliwane** [comment]
this is from the ```grpc-nginx-gateway``` conf:
```cpp
location / {
      grpc_pass localhost:60052;
      if ($request_method = 'OPTIONS') {
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
        add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Transfer-En$
        add_header 'Access-Control-Max-Age' 1728000;
        add_header 'Content-Type' 'text/plain charset=UTF-8';
        add_header 'Content-Length' 0;
        return 204;
      }
```
If request method is **OPTIONS**, then gateway return 204.

**Comment by sulliwane** [comment]
Oops...I just see that this behaviour is actually implemented in the ```wrapper.go```. My bad!

**Comment by sulliwane** [comment]
I solved the preflight problem by adding:
```go
Handler: http.HandlerFunc(func(resp http.ResponseWriter, req *http.Request) {
    resp.Header().Set("Access-Control-Allow-Origin", "*")
    resp.Header().Set("Access-Control-Allow-Methods", "GET, POST, OPTIONS")
    resp.Header().Set("Access-Control-Allow-Headers", "Origin, Content-Type")
```
Even if there is a function responsible to check the origin, it returns true by default, but never set the ```Access-Control-Allow-Origin```. I'm probably doing it wrong, but it works now
