### ISSUE TITLE
Provide complete bidirectional example if possible?

### ISSUE THREAD

**Issue by alexpdp7** [improbable-eng/grpc-web#205]
Can you get working a bidirectional proto using grpcwebproxy and a non-Go server? This seems to be working at https://grpcweb.jbrandhorst.com/ ?

Does https://github.com/improbable-eng/grpc-web/pull/180 need to be merged?

Can you clarify the situation and possible document it? Or list the blockers?

**Comment by johanbrandhorst** [comment]
Note: https://grpcweb.jbrandhorst.com/ uses a Go gRPC backend. The source is available at johanbrandhorst/grpcweb-example. For a more minimal example, you can look at johanbrandhorst/grpcweb-boilerplate. I haven't used the standalone proxy but I believe the websocket transport should be supported.

**Comment by alexpdp7** [comment]
Yeah, I took a look at it, but was a little bit lost, really- I wonder how much GopherJS-specific magic is there or if `grpc-web-client` can be made to work. The use case for bidirectional streaming on a "regular" gRPC server (even if requiring a proxy) with Typescript on a browser as the client is really important to me.

**Comment by johanbrandhorst** [comment]
The GopherJS library just wraps the `grpc-web-client`, it does all the actual sending of requests. You can definitely do the same thing with just the `grpc-web-client`. You can take a look at the tests for some examples of how to use bidirectional streaming: https://github.com/improbable-eng/grpc-web/blob/master/test/ts/src/client.websocket.spec.ts#L77

**Comment by alexpdp7** [comment]
Ah, that's awesome, thanks!

Thinking egotistically, you can close the ticket, although I'd propose leaving it open so this is documented...

**Comment by cogmeta** [comment]
I am trying a bidirectional example with websocket support. But, I get 500 Internal Server Error in response to we call ws://sub.server.com:8080/package.Service/MethodName? What might be going wrong? How can i run the proxy server in verbose mode?

**Comment by cogmeta** [comment]
![image](https://user-images.githubusercontent.com/10062479/41368059-6df9d998-6f5e-11e8-97a1-d49521835332.png)

**Comment by johanbrandhorst** [comment]
Closing as example provided in tests
