### ISSUE TITLE
regular gRPC and gRPC-Web over same port ?

### ISSUE THREAD

**Issue by nikkolasg** [improbable-eng/grpc-web#209]
Hi all,

I was wondering if it is possible to use the same port to accept `gRPC` and `gRPC-Web` connections ? I have a use case where some servers talks to each other using already `gRPC` and I'd like to open a external API callable from browsers, so using `gRPC-Web` but using the same port if possible.
Is it possible already ? Is it possible at all ? and if yes, what would it take to do it ?

Thanks a lot !

PS: I've seen someone talking about it for a Rust impl. https://github.com/tower-rs/tower-grpc/issues/35

**Comment by graup** [comment]
Definitely possible, but depends on your implementation. For Go, I've had success with [this guide](https://medium.com/@thatcher/why-choose-between-grpc-and-rest-bc0d351f2f84), specifically the cmux version.

**Comment by johanbrandhorst** [comment]
My GopherJS gRPC-Web example does this, the key is to split traffic in a handler: https://github.com/johanbrandhorst/grpcweb-example/blob/master/main.go#L123.

**Comment by johanbrandhorst** [comment]
This issue is unrelated to the gRPC-Web implementation.
