### ISSUE TITLE
 Error during WebSocket handshake: Unexpected response code: 500 

### ISSUE THREAD

**Issue by cogmeta** [improbable-eng/grpc-web#210]
I am trying bidirectional streaming  with grpc web proxy connected to python backend grpc server. I am getting 500 Internal sever error in response to ws://proxy.com:8080/package.Service/MethodName
initiated by client.start()? How can i debug this? There is no trace of any error on proxy or backend server. The backend grpc python server by itself works fine. The proxy seems to be successfully connected to backend server without any error. 

 'ws://proxy.com:8080/package.Service/MethodName' failed: Error during WebSocket handshake: Unexpected response code: 500
start @ websocket.js:46

**Comment by cogmeta** [comment]
![image](https://user-images.githubusercontent.com/10062479/41408316-e48d531e-6fef-11e8-8aaf-a2d098a72eb4.png)

**Comment by vintikzzz** [comment]
Same here!

**Comment by cogmeta** [comment]
@vintikzzz , I guess either their is grpc/protobuf version mistmatch issue or we are using version of grpc web proxy that does not  support websocket bidirectional streaming. Don't how to proceed even to debug it? Any ideas?

**Comment by vintikzzz** [comment]
@cogmeta I have used the same version as i mentioned at [#200](https://github.com/improbable-eng/grpc-web/issues/200). But I have tweaked proxy `grpcwebproxy` to support websocket bidirectional streaming and got `Unexpected response code: 500`

**Comment by cogmeta** [comment]
Is it possible to show what have you tweaked in the proxy server?

**Comment by vintikzzz** [comment]
Sure, i've added additional flag at [line 54](https://gist.github.com/vintikzzz/c14bbfc69c0c8b4c78ff4813b6c09c21#file-main-go-L54)

**Comment by cogmeta** [comment]
Ok, let me try this and report back.

**Comment by cogmeta** [comment]
Now, I get 403 error instead of 500.

**Comment by cogmeta** [comment]
![image](https://user-images.githubusercontent.com/10062479/41496210-727fdfda-7157-11e8-915b-d1434c901d7c.png)

**Comment by cogmeta** [comment]
Ok i made some progress. You need to allow origin to get rid of 403 so added following line where allowAllOrigins functions returns true for all requests.

rappedGrpc := grpcweb.WrapServer(grpcServer,
                       grpcweb.WithCorsForRegisteredEndpointsOnly(false),
                       grpcweb.WithWebsocketOriginFunc(allowAllOrigins),
                                                                      grpcweb.WithWebsockets(true))


Error 403, is gone now. Now, I now get 502 error. But, i think that has to dot with they way i am calling it from browser. will try to fix it.


INFO[0005] finished streaming call                       error="rpc error: code = Canceled desc = context canceled" grpc.code=Canceled grpc.method=StreamingRecognize grpc.service=XXX.XXXX.XXXX.XXXX.Speech grpc.start_time="2018-06-16T06:11:19Z" grpc.time_ms=1995 span.kind=server system=grpc

**Comment by cogmeta** [comment]
Ok, got it working. Thank you so much. I would suggest you add following line and dont forget to install again which will update the binary **grpcwebproxy**


> grpcweb.WithWebsocketOriginFunc(allowAllOrigins),

**Comment by vintikzzz** [comment]
@cogmeta really great that you've made such a progress on this stuff. I'll try to do the same )

**Comment by vintikzzz** [comment]
@cogmeta it works! ...at last...
Updated gist can be found [here](https://gist.github.com/vintikzzz/c14bbfc69c0c8b4c78ff4813b6c09c21)

**Comment by cogmeta** [comment]
@vintikzzz Aweosme, Thanks.

**Comment by cogmeta** [comment]
Have you tried with https? I am having some issues connecting over https. the connection is not getting upgraded to https.

**Comment by johanbrandhorst** [comment]
TLS encryption is handled by the browser, you should equally be able to use wss and ws schemes without problems.
