### ISSUE TITLE
AsObject => ProtobufMessage

### ISSUE THREAD

**Issue by dimart** [improbable-eng/grpc-web#214]
**TL;DR:** Is there a way to convert AsObject's back to ProtobufMessage's somehow?

For example, if I have this proto definition:
```
message Test {
  string info = 1;
}
...
service API {
  rpc Update(Test) returns (MaybeSuccess) {};
}
```

And inside my react application I use Test objects as Test.AsObject.
At some point I need to make a grpc call to the server.
```
update(test: Test.AsObject) {
  ...
  grpc.unary(API.Update, {
            request: test, // can't pass Test.AsObject, expects ProtobufMessage!
            ...
  })
}
```
And I can't pass Test.AsObject, since it expects ProtobufMessage. 
Is the only way to recreate ProtobufMessage from AsObject is to manually set all the fields myself?

P. S. Thanks a lot for making grpc-web possible, I really like it so far! 🙏

**Comment by MHDante** [comment]
This seems to be related to this issue: https://github.com/google/protobuf/issues/1591 (Which @jonnyreeves  has already commented in)

**Comment by MHDante** [comment]
Incidentally, this may be better addressed in the https://github.com/improbable-eng/ts-protoc-gen repo

**Comment by dimart** [comment]
Thanks for sharing this, I haven't seen that google/protobuf issue!

**Comment by MarcusLongmuir** [comment]
Closing this as it's a protobuf issue. Please re-raise if there's something the grpc-web package can do  to make this easier.

**Comment by Daneng66** [comment]
@dimart did you ever find a quick way to achieve this?
