### ISSUE TITLE
Does this transmit binary? Or JSON?

### ISSUE THREAD

**Issue by trusktr** [improbable-eng/grpc-web#218]
What does this do under the hood? Does it transmit binary or text?

**Comment by MarcusLongmuir** [comment]
Binary, with the only strangeness being a workaround that allows XmlHttpRequest to reliably send binary: https://github.com/improbable-eng/grpc-web/blob/master/ts/src/transports/xhr.ts#L68.

Please raise an issue / PR if you think this could be explained in a way that yourself or others would find helpful.
