### ISSUE TITLE
Use `isomorphic-ws` for websocket transport

### ISSUE THREAD

**Issue by bcho** [improbable-eng/grpc-web#221]
Currently, websocket transports is referencing a global WebSocket constructor, which works on browser. But can we add isomorphic-ws and enable usage in node side?

**Comment by johanbrandhorst** [comment]
I think with https://github.com/improbable-eng/grpc-web/pull/204 it looks like we'll want to be moving away from supporting Node (not an official decision!), so I don't see us making this change anytime soon. There is an official implementation of gRPC for Node already.

**Comment by easyCZ** [comment]
This is no longer relevant given the split of the transports.
