### ISSUE TITLE
No transport available for client-streaming (requestStream) ?

### ISSUE THREAD

**Issue by dshuffma-ibm** [improbable-eng/grpc-web#242]
Currently getting [this error](https://github.com/improbable-eng/grpc-web/blob/master/ts/src/transports/Transport.ts#L34) when trying to setup a request stream.  Is this a point in time limitation of grpc-web or a browser limitation?  Assuming I can't change the grpc server's behavior, but I don't need a request stream, (unary is fine), is there a way to hack that together?

**Comment by johanbrandhorst** [comment]
You need to explicitly enable the websocket transport to get request streaming. It's the only transport that supports request streaming. Unary and server side are supported by both XHR and Fetch transports, and they should be chosen automatically.

**Comment by dshuffma-ibm** [comment]
for others that find this issue he's probably referring something like [this](https://github.com/improbable-eng/grpc-web/blob/master/test/ts/src/client.websocket.spec.ts#L89).

**Comment by johanbrandhorst** [comment]
Yes, thanks. We may enable the use of the websocket transport by default at some point but it's still considered experimental.
