### ISSUE TITLE
Deserialize from object

### ISSUE THREAD

**Issue by laSinteZ** [improbable-eng/grpc-web#243]
I am not sure, if this issue belongs here, but anyway:

I've used `protoc` with `protoc-gen-ts` plugin (as described in guide) and generated .js (and .ts) files from my .proto files.

Now I want to use method `QueryServiceClient.find` (from my proto-files) to get data from my grpc service. When I use it, I get response as a plain Javascript object (instead of `QueryResponse`) from protobuff. Is there any way to transfrom this plain object into Protobuff object?

I guess it happens because of this line: https://github.com/soramitsu/iroha-helpers/blob/master/src/proto/endpoint_pb_service.js#L208

As a temporary workaround, I can write `response.message.serializeBinary()` and deserialize it after I receive it, but it involves changing generated code (also, can't do anything in non-improbable-web-generated files). Is there anyway to deserialize proto response from plain object, so I can have access to all getters and setters?

**Comment by johanbrandhorst** [comment]
This sounds weird... It should return you a protobuf object. Have you looked at the examples in this repository (https://github.com/improbable-eng/grpc-web/blob/master/example/ts/src/index.ts)? What does that link have to do with this project (or this issue)? Is that a link to your projec that is experiencing the problem? We need more information here.

**Comment by laSinteZ** [comment]
@johanbrandhorst this is my fault. I overlooked that it actually returns a `protobuff` object. I will close this issue in shame. Thank you for your time! :)

**Comment by johanbrandhorst** [comment]
No worries. Thanks for your interest in the project!
