### ISSUE TITLE
Add option to Increase Max Message Size on the Proxy

### ISSUE THREAD

**Issue by nevi-me** [improbable-eng/grpc-web#245]
Is there a config option to increase max message size on the proxy?

There's a similar issue #21, but this one was extreme as I only need a few more MB on my message.

I'm not familiar with Go, but I know that there is a dial option to increase message size: https://github.com/grpc/grpc-go/blob/master/dialoptions.go#L147. 

I'm wondering if this has been exposed on the grpc-web proxy?

**Comment by johanbrandhorst** [comment]
I don't think this is exposed, but there's no reason we couldn't add such a setting. Would you be interested in contributing this?

**Comment by johanbrandhorst** [comment]
As a separate point, the 4MB message limit is already pretty high - personally I would switch to streaming if the messages are larger than 1MB.

**Comment by nevi-me** [comment]
I know it's high, and I tried streaming, but I end up streaming about 2000 small messages, to which the proxy throws an error after between 300-500 messages in my stream. I didn't capture the logs at the time, but I'll try reproduce it.

**Comment by johanbrandhorst** [comment]
Hmm yeah that sounds like a bug worth investigating.

**Comment by nevi-me** [comment]
I steam the ~2000 records from MongoDB using a NodeJS stream, then for `stream.on('data', {})` I pass the message to my stream.

It could be that the errors are because of the stream being saturated. Given that my stuff's dependent on a lot of things, I might struggle with creating a standalone repro that works on the streaming bit, but I'll try (and open a separate issue if I succeed).

I had a look at the proxy's Go code with where the flags are set. I'll try adding the option to increase max size, but I might need some hand-holding if you (and anyone else) don't mind.

**Comment by johanbrandhorst** [comment]
Of course, if you put a PR up I'll review it :).

**Comment by nevi-me** [comment]
How do I overcome `cannot find package "google.golang.org/grpc/transport"` error? I've come across the issue before when I was setting up the proxy on my environment, but I can't remember what workaround I applied, or where I found the source of that 😫

**Comment by johanbrandhorst** [comment]
@nevi-me You'll see [in my reply on #216](https://github.com/improbable-eng/grpc-web/issues/216#issuecomment-420189052) that this is only an issue if you try to build the proxy without using the appropriate dependency.

**Comment by johanbrandhorst** [comment]
Fixed with #246
