### ISSUE TITLE
In grpc.unary the browser error shoe responsestream is not defined 

### ISSUE THREAD

**Issue by hunnain** [improbable-eng/grpc-web#250]
when i used grpc.unary the borwser show me error 
Uncaught TypeError: Cannot read property 'responseStream' of undefined
same error in grpc.invoke
![screenshot from 2018-09-21 15-33-18](https://user-images.githubusercontent.com/24963356/45876437-17735f00-bdb4-11e8-9cac-11138026b0a8.png)

**Comment by johanbrandhorst** [comment]
Hi @hunnain. Like I said in the last issue you raised (#249), this is extremely hard for us to help you with given the information you've provided. I suggest again, why don't you start with one of our working examples and switch to your own configuration once you have something working? I still think this is just improper configuration or use and not an issue. Please swing by the slack where it will be easier to help you with this problem (https://join.slack.com/t/improbable-eng/shared_invite/enQtMzQ1ODcyMzQ5MjM4LWY5ZWZmNGM2ODc5MmViNmQ3ZTA3ZTY3NzQwOTBlMTkzZmIxZTIxODk0OWU3YjZhNWVlNDU3MDlkZGViZjhkMjc)

**Comment by hunnain** [comment]
Johan i try your example but there was an eror because you are using go and i didnt know go language so how may i understand and i have also installed go and follow your steps but your example cant run please show your example in nodejs so we can easily understand please help me how to solve this problem

**Comment by johanbrandhorst** [comment]
Join the slack channel so we can help you with your setup. This issue thread is an inappropriate medium for back and forth debugging.

**Comment by ajs117** [comment]
I too am currently experiencing this issue. Was there a quick fix for this issue or a known cause? I cannot join slack for security reasons.
