### ISSUE TITLE
CORS problem

### ISSUE THREAD

**Issue by Revinand** [improbable-eng/grpc-web#251]
Hello, I encountered a problem with CORS. I have GO on the backend and react on the fronted. I compiled my proto into js services and tried to request server stream. The backend is hosted on one subdomain and the react on the other. The backed sends one OPTIONS response with Access-Control-Allow-Origin=* header, but on the second POST response I got 504 error. What can be a problem? I searched everywhere for the solution, but with no luck.

Thanks for help

**Comment by johanbrandhorst** [comment]
Could you be more specific about the second response? 504 doesn't mean much to me. Did it send an error string? Did your go gRPC server log anything?

**Comment by Revinand** [comment]
Sorry, didn't find what caused a problem, but solved it by switching to `websocket` transport which works like a charm.

**Comment by poojakedar** [comment]
I am facing similar issue...getting CORS error

Trying to run react example app:
Access to fetch at 'http://localhost:9090/examplecom.library.BookService/GetBook' from origin 'http://localhost:8081' has been blocked by CORS policy: Request header field x-grpc-web is not allowed by Access-Control-Allow-Headers in preflight response.
