### ISSUE TITLE
Configure backend backoff

### ISSUE THREAD

**Issue by fordhurley** [improbable-eng/grpc-web#277]
During development, the 2 minute [default max backoff delay](https://github.com/grpc/grpc-go/blob/master/backoff.go#L31) is painfully long. It would be nice to be able to override this with a flag. The flag could map to the `WithBackoffMaxDelay` DialOption: https://godoc.org/google.golang.org/grpc#WithBackoffMaxDelay

I propose the flag be called `backend_backoff_max_delay` that would accept a duration string like "30s" (anything parseable with [time.ParseDuration](https://godoc.org/time#ParseDuration)).

I'd be happy to submit a PR.

**Comment by johanbrandhorst** [comment]
Sounds good, please do.
