### ISSUE TITLE
v6.0.4 not published to npm

### ISSUE THREAD

**Issue by antonosmond** [improbable-eng/grpc-web#279]
I noticed 0.6.4 has been created as a release in github but 0.6.4 has not been published to npm.
I really need 0.6.4 for the transport changes e.g. sending requests with `credentials: 'include'`.
Is the npm package likely to be published anytime soon?

**Comment by johanbrandhorst** [comment]
Ah yes this is my bad, I didn't think it actually included any client changes so I only built the proxy. @jonny-improbable @easyCZ @MarcusLongmuir I'm not familiar (and probably not authenticated) with the npm publishing steps, can one of you do it please?

**Comment by jonny-improbable** [comment]
Published [`grpc-web-client@0.7.0`](https://www.npmjs.com/package/grpc-web-client/v/0.7.0) to npm.
