### ISSUE TITLE
Proxy HTTP only serving

### ISSUE THREAD

**Issue by petr-k** [improbable-eng/grpc-web#31]
Hello guys,
is the proxy capable of serving a HTTP only endpoint (no TLS) and route that to a classic no-TLS Java gRPC server?

**Comment by petr-k** [comment]
When I start the proxy with `--backend_tls=false`, this is what I get upon startup:
```
level=info msg="Failed to dial whale.int.avast.com:20001: connection error: desc = "transport: tls: first record does not look like a TLS handshake"; please retry." system=system 
```

This makes me think the proxy is actually still attempting to contact the backend gRPC server via TLS?

**Comment by mwitkow** [comment]
Interesting, I definitely tested it against a backend without TLS. 
https://github.com/improbable-eng/grpc-web/blob/master/go/grpcwebproxy/backend.go#L44

Can you post the logs on the server side? Also, what is the git-hash of teh github.com/grpc/grpc-go package you've built against?

**Comment by petr-k** [comment]
Can it be that the flag name is actually the opposite of what it means? When I specify `--backend_tls=false`, backend dialing succeeds. In code, it is being referred to as `flagBackendIsInsecure` (https://github.com/improbable-eng/grpc-web/blob/master/go/grpcwebproxy/backend.go#L20)

Anyway, now I think that CORS OPTIONS preflight request is not being handled correctly and is passed to the underlying gRPC service. Shall I post a separate issue for that?

**Comment by mwitkow** [comment]
I'll follow up with a patch later today, apologies.

As for the CORS, please do :)

**Comment by alexcpn** [comment]
This is not really solved; In the latest it asks for the tls flags and paths even when the flag is set; when I comment the parts and build , it works
