### ISSUE TITLE
Can you please build a new windows release?

### ISSUE THREAD

**Issue by moabtools** [improbable-eng/grpc-web#357]
Hi! 
I need a new Windows release of this great tool with worked --allow_all_origins option
Thanks!

**Comment by johanbrandhorst** [comment]
The latest release defaults to allowing all origins AFAIK. The option was only added to allow users to keep allowing all origins and make the default safe.

**Comment by johanbrandhorst** [comment]
We're about due another release anyway but probably not due to this. I think we wanted to wait for #331.

**Comment by moabtools** [comment]
Maybe it's not CORS, but I see error: "2019/02/19 15:05:15 http2: server: error reading preface from client 37.147.184.187:50692: remote error: tls: bad certificate". Browser says that is CORS error.

**Comment by johanbrandhorst** [comment]
This is not a CORS error. This is your browser not trusting your servers certificate. You may need to use a specific certificate in your server. In any case this is not an issue with the proxy. Please reply if you need further assistance.
