### ISSUE TITLE
How do I make GRPC service calls in node

### ISSUE THREAD

**Issue by hmillison** [improbable-eng/grpc-web#367]
Using improbable-eng/grpc-web 0.8.0

I'm trying to make a GRPC service call in a node environment (doing server side rendering), but I get an error when executing the request from this library. I saw that Node environments are supported and I have verified that my tsconfig has the `dom` lib included. 

When i make a request in node, i get this error: `This environment's XHR implementation cannot support binary transfer.`  

It looks like the browser support checks (https://github.com/improbable-eng/grpc-web/blob/master/client/grpc-web/src/transports/http/xhr.ts#L13-L17) are assuming a browser environment.

Any tips on how to get this working in node?

**Comment by bioball** [comment]
Use this transport: https://www.npmjs.com/package/@improbable-eng/grpc-web-node-http-transport

**Comment by hmillison** [comment]
Thanks! That did the trick for me.

Sorry I forgot to close this yesterday after finding that when rereading the docs.

**Comment by talhairfanbentley** [comment]
hey, how did you used this transport? 
here's my code:
`
import * as grpct from "grpc";
// import { grpc } from "@improbable-eng/grpc-web";
import * as Message from "../common/route_guide_pb";
import * as Service from "../common/route_guide_pb_service";
// import { NodeHttpTransport } from "@improbable-eng/grpc-web-node-http-transport";
function main(): void {
    // @ts-ignore
    let client: Service.RequestClient = new Service.RequestClient("http://localhost:5001", grpct.credentials.createInsecure());
    // grpc.setDefaultTransport(NodeHttpTransport());
    let req: Message.HelloRequest = new Message.HelloRequest();
    req.setName("TALHA");
    client.sendRequest(req, (err: Service.ServiceError| null, res: Message.HelloReply| null) => {
        console.log(`
            ${err}
            ======
            ${res}
        `);
        if(!err) {
            if(res) {
                console.log(res.getMessage());
            }
        }
    });
}
main();

`

**Comment by hmillison** [comment]
you need to set the transport to `NodeHttpTransport`.

When instantiating the `Service.RequestClient`, you can pass in an options object to configure the transport of the GRPC service.

this is how my code looks:
```
new Service.RequestClient("http://localhost:5001", {
  transport: NodeHttpTransport()
});
```

**Comment by talhairfanbentley** [comment]
Got it, Thanks.
