### ISSUE TITLE
Allow base path before service-name and method

### ISSUE THREAD

**Issue by mangas** [improbable-eng/grpc-web#453]
**Versions of relevant software used**
Latest
**What happened**
Addding the wrapper to an existing router under a base path requires fixing the path before passing the request to the wrapper otherwise service is not found
**What you expected to happen**
That the last 2 parts of the path were used to match registered services rather than the full path
**How to reproduce it (as minimally and precisely as possible)**:
```
router.New()
r.POST("/grpc/*all", wrappedServer)

r.ServeHttp(resp,req)
```

**Comment by johanbrandhorst** [comment]
I don't think it's unreasonable for us to expect the user to use [http.StripPrefix](https://golang.org/pkg/net/http/#StripPrefix) when serving on non-root paths. We could probably make this more clear in the documentation though. Would you be interested in contributing a documentation fix for this?

**Comment by mangas** [comment]
What is the downside of handling gracefully on the wrapper side?

**Comment by johanbrandhorst** [comment]
I don't think it's as simple as just taking the last two elements, always. I would prefer not to add special case handling in the wrapper when it only affects the small portion of users who do not serve on `/`.

**Comment by mangas** [comment]
What are the cases when it's not just taking the last 2 elements?

**Comment by johanbrandhorst** [comment]
According to that exact doc, it specifies the `:path` prefix to the `Service-Name` / `MethodName` tuple, AND it also states that sometimes the path is not in this form, but that it is discouraged. It doesn't sound like something that we want to rely in, again, _especially_ when this is so easily handed in the initialization.

Even if that were not the case, consider that this would introduce a mandatory parsing step of the URL path into the wrapper, which has a cost to all users.

I think we need much more convincing evidence of this being widespread and painful to workaround before we should add it on the wrapper.

**Comment by mangas** [comment]
Following the current pattern for cors and origin, this could be introduced as a func for the parsing, allowing to switch between the behaviour hence not affecting everyone but still providing it as part of the wrapper?

**Comment by johanbrandhorst** [comment]
That would have less of an impact, but it still adds to the API surface and maintenance burden, and I don't understand why `http.StripPrefix` isn't suitable for your use case? Maybe if you could share a bit more about your setup we could come to a compromise.

**Comment by mangas** [comment]
httpStripPrefix does work for my case but is something that basically needs to be kind of discovered and implemented for each project and that doesn't actually follow the protocol as would be expected. So it's more of a question of where this should be handled. Since the library does use the path to match registered services it seems to me like it would be the natural place. 

Using strip prefix works but it does need some logic to find out what is the prefix to be stripped. 
As for the API service it seems like a very transparent change as Options are already defined and passed so it would just be a matter of encapsulating the path matching following the same patterns.

**Comment by johanbrandhorst** [comment]
I don't think it's that strange to assume that  `StripPrefix` is in use, and I have seen [other packages](https://godoc.org/github.com/fullstorydev/grpcui/standalone#Handler) use such comments when returning `http.Handler`s. I don't think it's too much to assume of the user.

I agree that the proposed changes would be very minimal though, and if you want you're welcome to propose an option that adds this capability. I would probably suggest the option includes in its comment that it is an alternative to `http.StripPrefix` and by no means mandatory.

How does that sound?

**Comment by mangas** [comment]
Yep if that works for you I'm happy to write it 👍

**Comment by johanbrandhorst** [comment]
Why don't you submit a PR and we can continue the discussion there. Would the PR be making the assumption about using the last two fields or would you try to inspect the `path` header as well to be correct? Or would it be a `StripPrefix` for the wrapper?

**Comment by mangas** [comment]
Since the "alternative" formats are not really encouraged I'd probably start with a `passthrough` and the fixed `last 2 places of path` and we can discuss from there. Re-using `StripPrefix` looks like a good way to achieve the latter

**Comment by mangas** [comment]
@johanbrandhorst any plans for releasing a new version?

**Comment by johanbrandhorst** [comment]
I thought this issue was closed with the PR, oops!

I think @jonny-improbable @jonnyreeves usually makes the releases, I don't have the permissions for NPM :grimacing:.

**Comment by jonnyreeves** [comment]
I'm on holiday. Will look to release next week.
