### ISSUE TITLE
Dart support

### ISSUE THREAD

**Issue by wstrange** [improbable-eng/grpc-web#46]
I'll be that guy ;-)

A code generator for Dart web clients would be really nice...

**Comment by mwitkow** [comment]
Unfortunately, we're not familar with Dart.

But looking around it seems that Dart already has an "offiicial" `dart-protoc-plugin`, so the hardest work is done:
https://github.com/dart-lang/dart-protoc-plugin

Generating stubs is very simple compared to message serialization. Here's the relevant `ts-protoc-gen` plugin:
https://github.com/improbable-eng/ts-protoc-gen/blob/master/src/js_service_index.ts

**Comment by gedw99** [comment]
Hey all.

There is working GRPC for Dart now. It works between a Dart Flutter client and golang using GRPC
But i have not tried between Dart Web client and golang using GRPC-web yet.
https://github.com/dart-lang/grpc-dart

Its very easy to get setup with Dart and flutter to get going.
https://flutter.io/setup/
This gets you everything for run on Web and Flutter.


I will also be happy to help with testing.

**Comment by sigurdm** [comment]
https://github.com/dart-lang/grpc-dart now implements grpc-web.
