### ISSUE TITLE
could you release new version 0.9.6 with current bugfixes, need them asap for my app release

### ISSUE THREAD

**Issue by midan888** [improbable-eng/grpc-web#464]
**Versions of relevant software used**

**What happened**

**What you expected to happen**

**How to reproduce it (as minimally and precisely as possible)**:

**Full logs to relevant components**

**Anything else we need to know**

**Comment by johanbrandhorst** [comment]
Hi @midan888, I believe @jonny-improbable @jonnyreeves is going to make a release as soon as he's back from holiday (I think it's this week?). It's always possible to use the source itself if you need something ASAP.

**Comment by midan888** [comment]
@johanbrandhorst Thanks for the info, I will wait a bit, this week is OK to me.

**Comment by jonny-improbable** [comment]
Will aim to get this done before EoD.

**Comment by midan888** [comment]
Awesome!

**Comment by jonny-improbable** [comment]
@johanbrandhorst; would you be happy to be given permission to release to npm? If so, please can you give me your npm username and I will grant you publish permission.

**Comment by johanbrandhorst** [comment]
@jonny-improbable I'd... rather not to be honest :grin:. I don't have an npm account and I'd like to keep it that way. I wouldn't trust myself to get it right anyway.

**Comment by jonnyreeves** [comment]
No worries, I totally understand and very much appreciate the significant
amount of every you already give to this project.

**Comment by johanbrandhorst** [comment]
@jonnyreeves could we include arm binaries with the new release, too? I know #406 is still pending but it'd be nice to have.

**Comment by jonny-improbable** [comment]
I'm afraid I can't as I'm building on macOS and the arm binaries don't
cross compile in that environment :(

**Comment by johanbrandhorst** [comment]
:thinking: I didn't realise that was a problem. I'll do it.

**Comment by jonnyreeves** [comment]
v0.9.6 has been released.
