### ISSUE TITLE
Client-side TLS certificate support in @improbable-eng/grpc-web

### ISSUE THREAD

**Issue by graup** [improbable-eng/grpc-web#485]
Does the client @improbable-eng/grpc-web support SSL certs? We want to implement mutual TLS (e.g. like [here](https://bbengfort.github.io/programmer/2017/03/03/secure-grpc.html)), but as far as I can tell there's no way to enable that on the Javascript side.

**Comment by johanbrandhorst** [comment]
It does not, as you surmised this isn't really possible in browsers at the moment. You can enable it in the proxy, though. Closing this courtesy of it being impossible.
