### ISSUE TITLE
Pain points using gRPC-Web as a new user

### ISSUE THREAD

**Issue by dalu** [improbable-eng/grpc-web#499]
Sorry but this template is getting in the way.

grpcwebproxy requires this grpc-web wrapper. However the grpc wrapper has v1.8.0 of grpc.

The error is:
```
cannot use gs (type *"google.golang.org/grpc".Server) as type *"github.com/improbable-eng/grpc-web/vendor/google.golang.org/grpc".Server in argument to grpcweb.WrapServer
```
Meanwhile grpc is at version v1.22.0

If I don't wrap it with the wrapper and use the proxy I'm getting 
```
INFO[0000] parsed scheme: ""                             system=system
INFO[0000] scheme "" not registered, fallback to default scheme  system=system
INFO[0000] ccResolverWrapper: sending update to cc: {[{localhost:9090 0  <nil>}] }  system=system
INFO[0000] ClientConn switching balancer to "pick_first"  system=system
INFO[0000] pickfirstBalancer: HandleSubConnStateChange: 0xc0001b8010, CONNECTING  system=system
INFO[0000] listening for http on: [::]:8080             
INFO[0000] transport: loopyWriter.run returning. connection error: desc = "transport is closing"  system=system
INFO[0000] pickfirstBalancer: HandleSubConnStateChange: 0xc0001b8010, TRANSIENT_FAILURE  system=system
INFO[0000] listening for http_tls on: [::]:8443         
INFO[0001] pickfirstBalancer: HandleSubConnStateChange: 0xc0001b8010, CONNECTING  system=system
INFO[0001] transport: loopyWriter.run returning. connection error: desc = "transport is closing"  system=system
INFO[0001] pickfirstBalancer: HandleSubConnStateChange: 0xc0001b8010, TRANSIENT_FAILURE  system=system
INFO[0002] pickfirstBalancer: HandleSubConnStateChange: 0xc0001b8010, CONNECTING  system=system
INFO[0002] pickfirstBalancer: HandleSubConnStateChange: 0xc0001b8010, TRANSIENT_FAILURE  system=system
INFO[0002] transport: loopyWriter.run returning. connection error: desc = "transport is closing"  system=system
INFO[0005] pickfirstBalancer: HandleSubConnStateChange: 0xc0001b8010, CONNECTING  system=system
INFO[0005] pickfirstBalancer: HandleSubConnStateChange: 0xc0001b8010, TRANSIENT_FAILURE  system=system
INFO[0005] transport: loopyWriter.run returning. connection error: desc = "transport is closing"  system=system
INFO[0009] pickfirstBalancer: HandleSubConnStateChange: 0xc0001b8010, CONNECTING  system=system
INFO[0009] transport: loopyWriter.run returning. connection error: desc = "transport is closing"  system=system
INFO[0009] pickfirstBalancer: HandleSubConnStateChange: 0xc0001b8010, TRANSIENT_FAILURE  system=system
INFO[0015] pickfirstBalancer: HandleSubConnStateChange: 0xc0001b8010, CONNECTING  system=system
INFO[0015] pickfirstBalancer: HandleSubConnStateChange: 0xc0001b8010, TRANSIENT_FAILURE  system=system
INFO[0015] transport: loopyWriter.run returning. connection error: desc = "transport is closing"  system=system
```

enovy proxy is a nightmare to configure and work with, they even banned me because I was criticising them.

google's grpc-web is unusable otherwise, the browser has CORS issues, nginx requires a special module to be compiled aka a custom compilation of nginx (not tried yet) regular nginx doesn't support google's grpc-web.
This repo's grpc-web requires the transpiler to by installed via npm (why?) instead of installing it at a global level. I wanted to use it but can't.
So I can't use 
- grpc directly
- grpcwebproxy because errors
- envoy because it's a PITA with arrogant devs, don't get me started with building a new docker module every time you change something. It's just absurd.
- nginx because it uses a non-default module
- any browser because CORS and a usable proxy doesn't exist
- generated services from .proto files because the `grpcweb.WrapServer` is incompatible

grpc-web is unusable

Wasted almost a week trying to get it to work.
In this week I could've been done with user registration.
I should not need to do a backflip handstand while barking and jodeling at the same time to be able to use grpc-web in whatever version or anyone else for that matter.

**Comment by johanbrandhorst** [comment]
Hi,

Thanks for writing down the pain points, that's useful. However, I think your build issue is to do with your environment, there shouldn't be a reason we couldn't keep using an older version of the grpc server type.

As a side note, this repo uses v1.20.0 of grpc: https://github.com/improbable-eng/grpc-web/blob/master/Gopkg.lock#L286.

**Comment by dalu** [comment]
Weird I cloned it as described and used `dep ensure`
I've now removed the vendor dir and it builds and runs. Will try some more and see what happens. Will absolutely leave feedback here.

**Comment by dalu** [comment]
https://github.com/improbable-eng/grpc-web/blob/master/Gopkg.toml#L55
v1.8.0
It's the toml file what defines what gets installed with `dep ensure` and the lock file just describes what's installed right now?
Also, I mean you do what you like best, but wasn't dep superseded  by go.mod? I know everyone has their workflow, I'm just saying.

**Comment by johanbrandhorst** [comment]
The version constraint in `Gopkg.toml` is not the same as the version used. In this case it means "any version between 1.8.0 and 2.0.0". See https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md#version-rules.
> Also, I mean you do what you like best, but wasn't dep superseded by go.mod
Yes, it has been, we have not migrated (yet). See https://github.com/improbable-eng/grpc-web/issues/202.

**Comment by dalu** [comment]
okok well to the issue at hand
grpc-web in any of its incarnations is effectively unusable, which is a shame, for the given reasons
Only thing I have not tried is the gopherjs client but I'm not really interested in that tbh.
I like Angular and might even get used to React or Vue and I know what you personally think about JS and strict types from one of your videos but I don't really share that view personally. Dynamic languages are a time saver. I couldn't imagine doing layout or listening for events in Go. The workflow and overhead must be awful. What's great in a server side context I imagine must be really horrible on the client side. And the size it produces is also too large.

So yeah again,
- browser to grpc backend - CORS problem
- direct solution doesn't work because CORS middleware can't be used or reduces performance (documentation says so, untested)
- proxy solution doesn't work because nginx doesn't support grpc-web yet/requires custom module
- envoyproxy doesn't work because too complicated and arrogant devs and development workflow fubar. They don't even provide a binary, only a docker container one has to build. Every. Time. Anew.
- grpcwebproxy also doesn't work because of errors

Resolution of the dep problem is not using dep and removing vendor dir if any (cd to grpc-web dir;go get -u)

So yeah... unusable grpc-web. Pitty. I really wish it was different.

**Comment by johanbrandhorst** [comment]
These are all things you might be able to help resolve. This is an open source project. I am myself not involved with Improbable at all. If you want it, build it.

**Comment by nevi-me** [comment]
I could add on here instead of creating a new issue.

@dalu I struggled to get envoy working, but I found out that:
- it works only when grpcwebproxy is listening with the secure server. Insecure just never works for me
- the reason why insecure doesn't work seems to be an issue (that I haven't pinpointed) with grpc proxy (a dependency of this project)
- on further investigation (by creating a grpc-go:1.8.0 client), I noticed that the issue might be with how the backend grpc call is constructed (by hand). I'm not very familiar with go, so I couldn't debug properly
- grpc proxy is stuck on 1.8.0, and when I cloned the repo to try update grpcwebproxy, I couldn't get anything above 1.8.0 to install. I wanted to try using a more recent grpc-go version to see if the above would be resolved, or if I'd get hard errors to point me in the right direction

I am very dependent on grpcwebproxy as I've built a whole solution around it, I've come across some pain points, so please shout if there's something I could help with.

nginx:latest sort of works, but streaming doesn't work, and trailers with errors don't get propagated back.

nghttpx has the same failure as envoy.

I lastly tried rewriting/porting the grpcwebproxy to Rust, but I got stuck and didn't have enough time. Something I should have carved out more time to work on :(

**Comment by dalu** [comment]
> it works only when grpcwebproxy is listening with the secure server. Insecure just never works for me

do you mean grpcwebproxy having a valid (no insecure, self signed) cert or the grpc server side, or both?

> grpc proxy is stuck on 1.8.0, and when I cloned the repo to try update grpcwebproxy, I couldn't get anything above 1.8.0 to install. I wanted to try using a more recent grpc-go version to see if the above would be resolved, or if I'd get hard errors to point me in the right direction

don't use `dep` and remove the vendor dir and you'll have the version currently installed of grpc. I tried it with the most recent version at the time of creating the issue and the errors above appeared. I did use a self signed cert on the gateway and the grpc server side. The same self-signed cert. I also accepted (in Firefox) the cert permanently.

I've never done anything in Rust, so I have to pass there.

> nginx:latest sort of works, but streaming doesn't work, and trailers with errors don't get propagated back.

It think manually building nginx (maybe with a modified gentoo ebuild) with [Google's grpc-web module](https://github.com/grpc/grpc-web/tree/master/net/grpc/gateway/nginx) might be the most simple and long-term approach, now that you mention it. It's a whole lot better than dealing with that envoy monster directly.

There is also https://github.com/micro/micro
which uses envoy apparently at least according to the image along with other services. But it might be overkill.

**Comment by dalu** [comment]
The TRANSIENT_FAILURE or `{"error":"all SubConns are in TransientFailure, latest connection error: connection closed","message":"all SubConns are in TransientFailure, latest connection error: connection closed"}` and similar errors are because, like nevi-me wrote, TLS errors.

Instead of boasting around writing stupid blog posts you could've just said that.
I remember in the back of my head that those error messages were related to TLS, so since I've played with the grpc-gateway and go-micro for a bit it all came back to me.

So when using grpc with either the gateway or this grpcwebproxy the grpc (not web) server needs to either have no certificate at all(no TLS) or one the browser and the system recognizes.

All this could be avoided if Sheldon here wasn't Sheldon.
