### ISSUE TITLE
Gitter / Slack / Discord for discussion and troubleshooting?

### ISSUE THREAD

**Issue by b3ntly** [improbable-eng/grpc-web#50]
Are their any plans to create one? It would be a useful medium to anything that doesn't fit into a github issue.

**Comment by jonnyreeves** [comment]
You are the first person to ask :) A community will only be useful if there are enough people around to answer questions :)

Another option, which relies less on real-time replies, would to be introduce a custom stackoverflow tag, eg: [grpc-web](https://stackoverflow.com/questions/tagged/grpc-web).

I'm going to close this issue now; however if you (or others!) want to create a community then please feel free to re-open and we will gladly link to it from the repo's README.

**Comment by Nickito12** [comment]
Isn't there already a grpc freenode irc? The discord could have an irc channel with a bot that links both, and maybe some other channels, making it "have" all the people in the irc already.
