### ISSUE TITLE
Wire formats supported?

### ISSUE THREAD

**Issue by cflaviu** [improbable-eng/grpc-web#504]
What are the wire formats and content types supported by this grpc-web implementation? In Google's gRPC page (https://github.com/grpc/grpc-web), the wire formats and content types are specified. I want to compare the communication between browser and proxy of these two grpc-web implementations. What is the most efficient (speed, size) wire format supported by this implementation using a modern browser?

**Comment by johanbrandhorst** [comment]
Hi,

You can start by reading the gRPC blog post on gRPC-Web, which gives a comparison between this client and the official one. It's available on https://grpc.io/blog/state-of-grpc-web/. It also includes a link to a compatibility test repo, which might be of use, too; https://github.com/johanbrandhorst/grpc-web-compatibility-test.

In terms of speed, according to the Google gRPC-Web team, using the text format is currently the fastest, but I don't think there's been any official benchmarking done.

**Comment by cflaviu** [comment]
Hi, as I understand improbable-eng/grpc-web supports
- websocket transport
- content-type "application/grpc-web[+proto?]" - meaning payloads are in binary protobuf format. Is this true?

**Comment by johanbrandhorst** [comment]
I think the post should answer those questions, but to be clear;

The improbable gRPC-Web client supports `application/grpc-web`. These are binary protobuf encoded payloads.

The improbable gRPC-Web _proxy_ supports both `application/grpc-web` and `application/grpc-web-text`.

The websocket transport is just that, an alternative transport. It uses the `application/grpc-web` content encoding. It does not use some custom encoding.

Does that answer your questions?

**Comment by cflaviu** [comment]
Yes, thanks!
