### ISSUE TITLE
Auth Tokens

### ISSUE THREAD

**Issue by graywolf336** [improbable-eng/grpc-web#51]
How would one go about including authentication tokens in the `grpc-web-client`? I see the `metadata` in the `RpcOptions` [type](https://github.com/improbable-eng/grpc-web/blob/master/ts/src/grpc.ts#L95) however when I try to use it TypeScript says that property isn't valid.

```
    grpc.invoke(BookService.GetBooks, {
      request: new BookFilter(),
      host: 'http://localhost:9090',
      onEnd: (code: grpc.Code, msg: string, trailers: BrowserHeaders) => {
        console.log('getBooks.onEnd', code, msg, trailers);
      },
    });
```

This is an [example](https://github.com/FideTech/grpcweb-example/blob/master/app/src/views/list.ts#L28) of how I am trying to include/use it.

**Comment by graywolf336** [comment]
Ah, closing this as I found the issue. The current version in npm is `0.2.1` and it doesn't contain the commit https://github.com/improbable-eng/grpc-web/commit/f11adde0f663c88b32085bdfa9087be73ae30555 as that's coming in `0.3.0` which is currently marked as beta.

**Comment by KShoukry** [comment]
@graywolf336 Can you please provide an example of how to edit the headers and add a bearer token in the request?

**Comment by graywolf336** [comment]
@KShoukry I can not. I have not touched grpc since 2017..

**Comment by colemars** [comment]
> closing this as I found the issue 
Nice dude so helpful!
