### ISSUE TITLE
"TypeError: http.request is not a function" using Angular 7

### ISSUE THREAD

**Issue by cflaviu** [improbable-eng/grpc-web#510]
Hi, I have this issue using the patch from #191 and Angular 7.

index.js:56 Uncaught TypeError: http.request is not a function
    at NodeHttp.push../node_modules/@improbable-eng/grpc-web-node-http-transport/lib/index.js.NodeHttp.start (index.js:56)
    at e.start (grpc-web-client.umd.js:1)
    at Object.t.unary (grpc-web-client.umd.js:1)

The error appears here:
<p>	
node_modules\@improbable-eng\grpc-web-node-http-transport\lib\index.js
	
    NodeHttp.prototype.start = function (metadata) {
        var _this = this;
        var headers = {};
        metadata.forEach(function (key, values) {
            headers[key] = values.join(", ");
        });
        var parsedUrl = url.parse(this.options.url);
        var httpOptions = {
            host: parsedUrl.hostname,
            port: parsedUrl.port ? parseInt(parsedUrl.port) : undefined,
            path: parsedUrl.path,
            headers: headers,
            method: "POST"
        };
        if (parsedUrl.protocol === "https:") {
            this.request = https.request(httpOptions, this.responseCallback.bind(this));
        }
        else {
	==>     this.request = http.request(httpOptions, this.responseCallback.bind(this));
</p>

Node HTTP transport is used:
<p>

        const myService: Service.MyService = new Service.MyService("http://localhost:8080", { transport: NodeHttpTransport() });

        grpc.setDefaultTransport(NodeHttpTransport());

</p>

The packages used are:
<p>

	"@angular/*": "7.1.4"

	"@improbable-eng/grpc-web": "^0.9.6"

	"@improbable-eng/grpc-web-node-http-transport": "^0.9.6"
	
	"@types/google-protobuf": "^3.7.1"
	
	"@types/node": "^12.6.8"
	
	"google-protobuf": "^3.9.0"	
</p>

On Visual Stdio Code the code compiles successfully.

I checked this https://stackoverflow.com/questions/22593994/node-js-typeerror-object-is-not-a-function, but http.request is not defined at all at run-time. I tried var x = https.request but it fails too.

Any idea how to fix it?

**Comment by johanbrandhorst** [comment]
I might be wrong, but it looks like you're trying to use the node transport in the browser? This will not work. You can specify a different transport or not set it at all to let the client choose the most appropriate one.

**Comment by cflaviu** [comment]
You are right! Thanks! Initially the code was used in a simple script where node transport was needed.

Just for you guys having the same issue: after the removal of node-http-transport option, I'm getting this 

`"Access to fetch at 'http://localhost:8080/<Service>/<function>' from origin 'http://localhost:4200' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled." `

I'm trying this solution from Stackoverflow [No 'Access-Control-Allow-Origin' header is present on the requested resource—when trying to get data from a REST API](https://stackoverflow.com/questions/43871637/no-access-control-allow-origin-header-is-present-on-the-requested-resource-whe) .
