### ISSUE TITLE
base64ResponseWriter.Flush() call itself recursively

### ISSUE THREAD

**Issue by light0x** [improbable-eng/grpc-web#526]
**Versions of relevant software used**
0.10.0
**What happened**
![image](https://user-images.githubusercontent.com/1164704/62528121-ea665880-b86e-11e9-9888-96aabd5d27dd.png)

**What you expected to happen**

**How to reproduce it (as minimally and precisely as possible)**:

**Full logs to relevant components**

**Anything else we need to know**

**Comment by johanbrandhorst** [comment]
Thanks for the bug report, this was caused by #479. I will back out the change until we can fix this.

**Comment by light0x** [comment]
Please tag a new release ASAP, since the bug has broken the whole thing.

**Comment by jonny-improbable** [comment]
@light0x we are on it; just waiting for CI to go green.

**Comment by jonny-improbable** [comment]
Resolved in release v0.11.0 which has just been published.
