### ISSUE TITLE
(Docs) Broken link to example repo

### ISSUE THREAD

**Issue by jbpratt78** [improbable-eng/grpc-web#538]
**What happened**
404 not found
**What you expected to happen**
A beautiful example would appear
**How to reproduce it (as minimally and precisely as possible)**:
[Click here](https://github.com/improbable-eng/grpc-web/tree/master/example)
**Full logs to relevant components**
https://github.com/improbable-eng/grpc-web/blob/master/client/grpc-web/README.md has an example link that is broken

**Comment by johanbrandhorst** [comment]
Hi @jbpratt78, thanks for the bug report! Would you be interested in contributing a fix for this? It should be an easy fix :).

**Comment by jbpratt78** [comment]
Sure, if it should just be swapped for the React example link, then I will do that now! :+1:
