### ISSUE TITLE
a way to add ws.remoteAddress into grpc metadata

### ISSUE THREAD

**Issue by alexvas** [improbable-eng/grpc-web#548]
One possible scenario is: 

1. js frontend establishes websocket connection with grpc-web-proxy via nginx;
1. nginx adds some headers (e.g. X-Real-IP) to the request;
1. grpc-web-proxy converts websocket headers into http2 headers (grpc metadata);
1. at the grpc backend one is able to get "X-Real-IP" header from request's metadata.

Are there better options? May you give some hints where to start with?

**Comment by johanbrandhorst** [comment]
Hi @alexvas. I'm a little confused, is this something you've tested and working or are you saying it's not working as expected? It sounds to me like you've got the best option figured out. I'm not sure if step 3 is supported at the moment which is why I ask.

**Comment by alexvas** [comment]
The step 3 is not supported indeed. I'd like to implement it and asking for suggestions where to start with.

**Comment by johanbrandhorst** [comment]
Ok, great! I think you can start looking in https://github.com/improbable-eng/grpc-web/blob/master/go/grpcweb/websocket_wrapper.go, that's where the websocket request transformation logic resides. I would suggest starting by adding a failing test to https://github.com/improbable-eng/grpc-web/tree/master/integration_test and then trying to get it to pass.

Hope that helps!

**Comment by alexvas** [comment]
Thanks!

**Comment by alexvas** [comment]
My naive attempt was to reuse grpcweb.WithAllowedRequestHeaders yet it failed. It seems like nginx do not set any headers after upgrading ws connection. Just for the reference, here are changes:
https://github.com/improbable-eng/grpc-web/compare/master...alexvas:failed_attempt?expand=1

Alas, it looks like I really need to go into websocket_wrapper internals.

**Comment by alexvas** [comment]
I seems I've done it. At least with nginx config like that:

```nginx
    location /ws/ {
        proxy_pass       http://127.0.0.1:5701/;
        proxy_set_header X-Real-IP          $remote_addr;
        proxy_set_header X-Forwarded-Host   $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;

        proxy_http_version 1.1;
        proxy_set_header   Upgrade    $http_upgrade;
        proxy_set_header   Connection 'upgrade';
        proxy_read_timeout 86400;
    }
```
and grpc web proxy running like

```bash
grpcwebproxy-v0.11.custom-linux-x86_64 \
  --server_bind_address=127.0.0.1 \
  --server_http_debug_port=5701 \
  --backend_addr=127.0.0.1:8722 \
  --run_tls_server=false \
  --use_websockets \
  --allow_all_origins \
  --allowed_headers=X-Real-Ip,X-Forwarded-For
```

one could see in backend logs:
```
headers=GrpcHttp2RequestHeaders[:path: /my.service/myMethod, :authority: 127.0.0.1:8733, :method: POST, :scheme: http, te: trailers, content-type: application/grpc, user-agent: grpc-go/1.24.0-dev, x-grpc-web: 1, x-real-ip: 109.111.111.111, x-forwarded-for: 109.111.111.111]
```

Yet I failed to run tests via `test-all.sh` script. The error is:
```
Testing go sources
# _/bla-bla-bla/grpc-web-1.git/go/grpcweb_test
grpcweb/wrapper_test.go:201:34: undefined: grpcweb.Trailer
grpcweb/wrapper_test.go:211:15: undefined: grpcweb.Trailer
grpcweb/wrapper_test.go:216:15: undefined: grpcweb.Trailer
grpcweb/wrapper_test.go:222:16: undefined: grpcweb.Trailer
grpcweb/wrapper_test.go:234:16: undefined: grpcweb.Trailer
grpcweb/wrapper_test.go:241:16: undefined: grpcweb.Trailer
grpcweb/wrapper_test.go:464:74: undefined: grpcweb.Trailer
grpcweb/wrapper_test.go:491:66: undefined: grpcweb.Trailer
grpcweb/wrapper_test.go:508:60: undefined: grpcweb.Trailer
grpcweb/wrapper_test.go:517:10: undefined: grpcweb.Trailer
grpcweb/wrapper_test.go:517:10: too many errors
```

May you suggest how to fix current tests as I am compete noob in Golang?

**Comment by johanbrandhorst** [comment]
Submit the PR and the automated tests will be run :). I don't know about this specific error but it sounds like you haven't installed the dependencies. It might be as easy as making sure you're running Go 1.13, but without knowing more about your setup it's hard to say.
