### ISSUE TITLE
client-stream -> unary response, how to access response?

### ISSUE THREAD

**Issue by danjenson** [improbable-eng/grpc-web#551]
I have a basic service that implements a file upload, so it streams from the client and then receives a single response with a key to that data. For example:

```
syntax = "proto3";
package vendor;

service Vendor {
  rpc store (stream Data) returns (Key);
}

message Data {
  bytes data = 1;
}

message Key {
  string key = 1; 
}
```

@improbable-eng/ts-protoc-gen generates the following:
```
// package: vendor
// file: vendor.proto

import * as vendor_pb from "./vendor_pb";
import {grpc} from "@improbable-eng/grpc-web";

type Vendorstore = {
  readonly methodName: string;
  readonly service: typeof Vendor;
  readonly requestStream: true;
  readonly responseStream: false;
  readonly requestType: typeof vendor_pb.Data;
  readonly responseType: typeof vendor_pb.Key;
};

export class Vendor {
  static readonly serviceName: string;
  static readonly store: Vendorstore;
}

export type ServiceError = { message: string, code: number; metadata: grpc.Metadata }
export type Status = { details: string, code: number; metadata: grpc.Metadata }

interface UnaryResponse {
  cancel(): void;
}
interface ResponseStream<T> {
  cancel(): void;
  on(type: 'data', handler: (message: T) => void): ResponseStream<T>;
  on(type: 'end', handler: (status?: Status) => void): ResponseStream<T>;
  on(type: 'status', handler: (status: Status) => void): ResponseStream<T>;
}
interface RequestStream<T> {
  write(message: T): RequestStream<T>;
  end(): void;
  cancel(): void;
  on(type: 'end', handler: (status?: Status) => void): RequestStream<T>;
  on(type: 'status', handler: (status: Status) => void): RequestStream<T>;
}
interface BidirectionalStream<ReqT, ResT> {
  write(message: ReqT): BidirectionalStream<ReqT, ResT>;
  end(): void;
  cancel(): void;
  on(type: 'data', handler: (message: ResT) => void): BidirectionalStream<ReqT, ResT>;
  on(type: 'end', handler: (status?: Status) => void): BidirectionalStream<ReqT, ResT>;
  on(type: 'status', handler: (status: Status) => void): BidirectionalStream<ReqT, ResT>;
}

export class VendorClient {
  readonly serviceHost: string;

  constructor(serviceHost: string, options?: grpc.RpcOptions);
  store(metadata?: grpc.Metadata): RequestStream<vendor_pb.Data>;
}
```

The question is, how can I get the response --> vendor_pb.Key from a call to client.store? I can successfully write all the data to the store request and end the call, but I can't figure out how to get the response. `on('end', ...)` and `on('status', ...)` don't return it either.

**Comment by jonny-improbable** [comment]
Thanks for raising @danjenson; this is an issue with the https://github.com/improbable-eng/ts-protoc-gen library; I am going to close this issue and have raised https://github.com/improbable-eng/ts-protoc-gen/issues/208 to track a fix.

**Comment by avanishmylari** [comment]
Hi i am getting error while compiling,
ERROR in node_modules/@improbable-eng/grpc-web/dist/typings/transports/http/fetch.d.ts(2,51): error TS2304: Cannot find name 'Exclude'.
node_modules/@improbable-eng/grpc-web/dist/typings/transports/http/fetch.d.ts(3,60): error TS2344: Type '"body" | "headers" | "method" | "signal"' does not satisfy the constraint '"body" | "window" | "headers" | "method" | "cache" | "credentials" | "integrity" | "keepalive" | ...'.
  Type '"signal"' is not assignable to type '"body" | "window" | "headers" | "method" | "cache" | "credentials" | "integrity" | "keepalive" | ...'  how to resolve this issue?
