### ISSUE TITLE
Add Windows 32 release builds for grpcwebproxy

### ISSUE THREAD

**Issue by jvmlet** [improbable-eng/grpc-web#556]
Please compile the `grpcwebproxy`  for win32 platform
Thanks

**Comment by johanbrandhorst** [comment]
I can make a windows 32 build for the latest release, but it would be good if you could contribute an update for https://github.com/improbable-eng/grpc-web/blob/master/publish-release.sh with windows32 added.

**Comment by johanbrandhorst** [comment]
I added win32 to v0.11.0: https://github.com/improbable-eng/grpc-web/releases/tag/v0.11.0

**Comment by jonny-improbable** [comment]
I've added the 386 architecture to the `./publish-release.sh` script which means both [0.12.0](https://github.com/improbable-eng/grpc-web/releases/tag/v0.12.0) and all future releases will get a win32 binary built.
