### ISSUE TITLE
grpcwebproxy flag parsing is a bit broken

### ISSUE THREAD

**Issue by Timmmm** [improbable-eng/grpc-web#564]
Ok I found out what was causing my weird issues in #562 and #563 - the flag parsing for bool parameters is kind of broken. Basically this:

     ./grpcwebprox --run_tls_server false

Means it *will* run the tls server. It doesn't produce an error or anything. You need to do this:

     ./grpcwebprox --run_tls_server=false

Ok crazy. Maybe you just always need to use `=`? No you don't! `--backend_addr 127.0.0.1` works fine. It is just the boolean flags that have this weird broken parsing.

**Comment by johanbrandhorst** [comment]
Yeah, this is a bit weird, I can see the reason for the confusion. However, this is how POSIX/GNU style flags work, apparently according to the library we're using: https://github.com/spf13/pflag#command-line-flag-syntax. I don't think we're going to change library, so while I'm sorry this caused some confusion for you, I don't think we're going to do anything about it.

**Comment by Timmmm** [comment]
It says:

> -b true is INVALID

That implies that it should give some kind of error. It also says:

> flags can be interspersed with arguments anywhere on the command line

So I think it is treating `true` as an argument (not a flag). In that case you should be processing arguments, and since the command doesn't support any arguments, give an error if there are any.

I think you can do it something like this (not tested at all):

```
func main() {
	pflag.Parse()
	if len(pflag.Args()) != 0 {
		for _, flag := range pflag.Args() {
			if flag == "true" || flag == "false" {
				logrus.Fatal("Boolean flags should be set using `--flag=false`, `--flag=true` or `--flag` (which is short for `--flag=true`). You cannot use `--flag true` or `--flag false`.")
			}
		}
		logrus.Fatal("Unknown argument: " + flag)
	}
	...
```

**Comment by johanbrandhorst** [comment]
Sounds worthwhile, since you ran into this issue, would you be interested in contributing this fix?
