### ISSUE TITLE
Unable to compile angular 6 error TS2304: Cannot find name 'Exclude'

### ISSUE THREAD

**Issue by coilnovasince1985** [improbable-eng/grpc-web#580]
**Versions of relevant software used**
"@angular/common": "6.0.2",
"@angular/compiler": "6.0.2",
"@angular/core": "6.0.2",
"typescript": "~2.7.0"

**What happened**

ERROR in node_modules/@improbable-eng/grpc-web/dist/typings/transports/http/fetch.d.ts(2,51): error TS2304: Cannot find name 'Exclude'.

I assume that the issue is related to typescript version, but currently I'm unable to upgrade to 3.*.
Is there any temporary fix in order to make it work and compile

**Comment by jonnyreeves** [comment]
I'm sorry but Exclude is a language feature in Typescript. Note that older
versions of grpc-web are compatible with earlier versions of Typescript.

**Comment by coilnovasince1985** [comment]
@jonnyreeves I've tried all, seems like it doesn't work on angular 6 :(

**Comment by coilnovasince1985** [comment]
I've tried on angular 8, no such an error. Seems like I just need to upgrade to the next version, but would be nice if somebody would share a solution for my current one

**Comment by jonny-improbable** [comment]
I don't believe there is a workaround for this issue given that @improbable-eng/grpc-web relies upon language features only present in TypeScript 3.x.

You may be able to specify the version of typescript used by your own package to resolve this issue.

**Comment by avanishmylari** [comment]
jonny-improbable i also got the same issue in my project currently my TS version is 2.7 why i am getting and how to solve it
