### ISSUE TITLE
Question: gRPC Web with C++ backend

### ISSUE THREAD

**Issue by mohsenomidi** [improbable-eng/grpc-web#583]
I am new in gRPC Web !

I already use the gRPC protocol and protobuf serializing in my C++ application as backend. 

now i want to use this protocol in my web user interface. my application bases forced me to make connection directly between C++ and my web API via HTTP2 (h2) 
Now i am interested in this library, i read the some documents in google blog and your library readme files. 

now i know the limitation that mentioned in these documents :

1- Google official blog says:

> The Improbable client supports both unary and server-side streaming, and has an implementation that automatically chooses between XHR and Fetch based on the browser capabilities.

2- This library mentioned : 

> Client-side streaming
> It is very important to note that the gRPC-Web spec currently does not support client-side streaming. This is unlikely to change until new whatwg fetch/streams API lands in browsers. As such, if you plan on using gRPC-Web you're limited to:
> 
> unary RPCs (1 request 1 response)
> server-side streaming RPCs (1 request N responses)
> This, however, is useful for a lot of frontend functionality.

3- this library uses http2 for  modern browser which supported http2

> grpcweb - a Go package that wraps an existing grpc.Server as a gRPC-Web http.Handler for both HTTP2 and HTTP/1.1.

my backend:

1- C++ grpc server, on http2

my requierments: 

1- http2 grpc web client 
2- support only http2 (for only http2 support browsers, no need to backward compatibility)
3- support only : unary RPCs ,  server-side streaming RPCs, 
4- no need to use proxy (Go Proxy or Envoy, or etc ) 
5- my Client web application is ReactJS

my question : 

is it possible to use this library for my requirements for developing the ReactJS app communicating with my C++ backend without any proxy ?

and could you please explain how i can do this ?

and if NOT, why ? (latest google Chrome supports http2, and grpc using the http2) 

**Environment**:
- OS : 

NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"

- Kernel : 

4.15.0-64-generic

- Others:
gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0

**Comment by johanbrandhorst** [comment]
> is it possible to use this library for my requirements for developing the ReactJS app communicating with my C++ backend without any proxy?

No. Browsers can use HTTP/2, but javascripts don't have enough power over the requests to speak pure gRPC. This is explained in the post you mentioned.

You can use this proxy in front of your C++ gRPC server though, just like you can use the Envoy proxy. But you do still need a proxy.

**Comment by mohsenomidi** [comment]
@johanbrandhorst  Thanks for your reply...

just for clarification :

The recent version of Node.js supports HTTP/2 very well.

[Node.js v13.0.1 Documentation ](https://nodejs.org/api/http2.html
)

I can't understand what kind of limitation exists in JavaScript?
I don't need the client side streaming as mentioned in Client-side streaming [streams API](https://www.w3.org/TR/streams-api/)

would you please explain more about this limitation just to understand technically?

Regards,

**Comment by jonnyreeves** [comment]
The limitation lies within browsers and the http primitives they exist, not
JavaScript the language.

**Comment by mohsenomidi** [comment]
@jonnyreeves 

Thanks so much for reply, I am confused, would you please give more in-depth detail info ?
If there is any article in this regards, would you please share it, to know what is this limitation ? 

As I mentioned above, I don't need the client side streaming (if the limitation is this) 
My usage is only for (**unary  , server-side streaming RPCs**) and need more details about what are the limitations that prevent to use these two functionality without any proxy via web and gRPC Server ?

Regards,

**Comment by johanbrandhorst** [comment]
Hi again @mohsenomidi. What both me and Jonny are trying to say is that you are confusing JavaScript in Node with JavaScript in the browser. The JavaScript in the browser does not have control over which protocol to use (http1 or http2), and even within each protocol, how to frame the HTTP frames. This is necessary to speak pure HTTP gRPC. That is why browsers cannot support gRPC without a proxy. Take a look at the definition of the Fetch API: https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API. How would you tell it to send a HTTP/2 request? Or with XHR? How would you do that? It's impossible. Go back and read the post, it's clearly stated:

> It is currently impossible to implement the HTTP/2 gRPC spec3 in the browser, as there is simply no browser API with enough fine-grained control over the requests. For example: there is no way to force the use of HTTP/2, and even if there was, raw HTTP/2 frames are inaccessible in browsers. 

If you need anymore explanation, maybe reach out to the author of the post ;).

**Comment by mohsenomidi** [comment]
@johanbrandhorst  : 

Thank You So Much :)

Now i get the root cause...The main issue is about the fetch api, that we can not force it to use HTTP2.
