### ISSUE TITLE
Not using stream.SendHeader in Server Streaming call yields error

### ISSUE THREAD

**Issue by johanbrandhorst** [improbable-eng/grpc-web#59]
I've been playing around with gRPC-Web for my GopherJS bindings, and I noticed that if I remove the `stream.SendHeader` call in `QueryBooks` I get the following error:

`Response closed without grpc-status (Headers only)`

The `onEnd` headers look like so:

```
access-control-allow-credentials:[true]
access-control-allow-origin:[https://localhost:10000]
content-type:[application/octet-stream]
date:[Fri, 23 Jun 2017 08:46:36 GMT]
status:[200]
strict-transport-security:[max-age=31536000; includeSubDomains; preload]
vary:[Origin]
```

Indeed, the `grpc-status` header is missing. When the `SendHeaders` call is added back the `onEnd` headers look like so instead:

```
grpc-status:[0]
```

I've tried debugging this a little but It'd be cool to know if this is reproducible on your end of if it's a problem with my setup. The source repo I'm using is https://github.com/johanbrandhorst/grpcweb-example.

**Comment by MarcusLongmuir** [comment]
@johanbrandhorst: This seems rather strange. Can you raise a PR with a failing test please? 

The existing tests try combinations of headers-only/trailers-only/both/none, so they _should_ have caught this.

**Comment by johanbrandhorst** [comment]
@MarcusLongmuir OK good to know - it might be something on my end. I'll take a look at the tests and see if I can reproduce it.

**Comment by johanbrandhorst** [comment]
Welp, after debugging this for 2 full days I updated my https://github.com/improbable-eng/grpc-web/tree/master/go/grpcweb and the problem seems to have gone away. Not sure quite what caused the problem but it appears fixed in master so I'm going to go ahead and close this.

**Comment by johanbrandhorst** [comment]
For the record, I think the fix was in https://github.com/improbable-eng/grpc-web/commit/79e709917e4aea4ba17dec8976631c6ffb837f61, specifically the grpc_web_response.go changes.

**Comment by MarcusLongmuir** [comment]
Looks right. Thanks for finding the root cause. Apologies for not making the connection.
