### ISSUE TITLE
Wrap server without cors

### ISSUE THREAD

**Issue by petomalina** [improbable-eng/grpc-web#61]
Is there any possibility to wrap the the gRPC proxy server without allowing CORS? We already have a gateway that serves all preflight requests, however, the headers are doubled as grpc web proxy also adds headers to the response.

**Comment by gelidus** [comment]
I resolved the issue with the Origin Option like this

    // Wrap grpc server to grpc-web server
	wrappedServer := grpcweb.WrapServer(s, grpcweb.WithOriginFunc(func(origin string) bool {
		// disable all origins, this is all done by the proxy before these servers
		return false
	}))

is there any better solution?

**Comment by jonnyreeves** [comment]
@MarcusLongmuir - IMHO the approach should be restrictive by default when it comes to security features such as CORS; would you welcome a patch that defaults to denying all CORS requests and adds a custom Option helper: `grpcweb.WithCORSWhitelist()`

**Comment by MarcusLongmuir** [comment]
@jonnyreeves: I agree. Would definitely welcome a patch, but this is likely to be a breaking change and it will need to be communicated.

At the very least (and only just palatable), we could change the function name to surface the change as a compilation error to anyone depending on `master` of this repo.

I think we need to fix up the release process as per #43 with this in mind.

Thoughts, @mwitkow?

**Comment by jonnyreeves** [comment]
PR incoming.

I think this is the correct change to make, even if it's impactful to users when upgrading, as many users may not be aware of the default behaviour which circumvents the browser's security model.  For those who were relying on this change, it should be fairly clear to them what has broken (ie: CORS) and a release note / changelog can call this out explicitly.

Also given that the project is still an alpha, early adopters should expect the occasional bump in the name of security, stability and performance ;)

**Comment by jonny-improbable** [comment]
Only took a year and a half, but #158 has now landed which closes this issue :)
