### ISSUE TITLE
gRPC Client connection lose tracking

### ISSUE THREAD

**Issue by coilnovasince1985** [improbable-eng/grpc-web#614]
Haven't found any documentations or issues related to tracking the browser tab close or browser close.
I do a server side streaming to the angular app, and if the app is closed the only way I can know that client is disconnected is when I try to send a message to client and catch an error. 

This is very important for me because I need to delete a rabbitMQ queue if the connection is lost.
Any ideas on how to track browser tab close or any other way of disconnect on a server side without sending a message ?

**Comment by johanbrandhorst** [comment]
The context will be cancelled, if it is a go gRPC application. I don't know for other type of gRPC servers.

**Comment by coilnovasince1985** [comment]
@johanbrandhorst yea actually the only thing interface provides is Context Error, so I solved it the same way as described in a similar issue:
```
if stream.Context().Err() != nil {
}
```

Closing issue
