### ISSUE TITLE
Getting remote IP from a load balancer

### ISSUE THREAD

**Issue by philipithomas** [improbable-eng/grpc-web#62]
Here's a fairly common thing I'm trying to do, but can't find docs to describe. 

I'm running this gRPC app behind a load balancer, which sets an HTTP header of the remote IP address. How can I fetch that in the gRPC server for logging purposes? Will that still work with streaming?

**Comment by MarcusLongmuir** [comment]
You should receive the headers as metadata on the server, allowing you to extract it from there.

Streaming is dependent upon how the load balancer is proxying the request, but it's likely to work.

**Comment by MarcusLongmuir** [comment]
Closing this. Please reopen if I misunderstood the question.
