### ISSUE TITLE
Request for arm64 (armv8) binary 

### ISSUE THREAD

**Issue by AleksandarFilipov** [improbable-eng/grpc-web#621]
At previous request (#387) you published prebuilt arm binaries which was apprechiated.

Latest commit works great with my project which previously failed (#393). The latest release (arm32) does not work however the problem is solved in latest commit https://github.com/improbable-eng/grpc-web/commit/2049acb57d304a04c1cd4be6baadb897812f98ef

btw, i doubt that there is any use of armv5 and armv6

Many thanks

**Comment by johanbrandhorst** [comment]
Latest commit (master) or latest release? We could probably do a new release @jonny-improbable

**Comment by AleksandarFilipov** [comment]
Sounds great, so commit linked above works great. Latest release does not.

**Comment by johanbrandhorst** [comment]
I don't have all the access rights to make a new npm commit, so I'll let @jonny-improbable do the release and I can manually build the arm binaries and upload them.

**Comment by jonny-improbable** [comment]
@johanbrandhorst I've just published 0.12.0 to github and npm; please could you build and attach an arm binary? Thanks :)

**Comment by johanbrandhorst** [comment]
ARM releases have been attached: https://github.com/improbable-eng/grpc-web/releases/tag/v0.12.0

**Comment by fscarmen2** [comment]
V0.15.0 Linux Arm64
https://github.com/fscarmen2/Argo-Nezha-Service-Container/releases/download/grpcwebproxy/grpcwebproxy_linux_arm64.tar.gz
