### ISSUE TITLE
Javascript websocket address construction should be optional?

### ISSUE THREAD

**Issue by Virtual-felix** [improbable-eng/grpc-web#622]
**Versions of relevant software used**
@improbable-eng/grpc-web 0.11.0

**What happened**
On the javascript library, I make a request using a websocket. I'm using Nginx to serve the frontend, which has a reverse proxy: it expect a request on `/api` and forward it to the IP/PORT of the improbable grpc server proxy.
The fact is that the javascript library, to build a websocket transport, expect the URL to start with either `http://` or `https://` to replace it with `ws://` or `wss://`, otherwise it throw an error.
But as I'm using nginx to reverse proxy my requests (which work without websocket), I make them on `/api` directly, without a full URL (http://...), so I can' t use websocket as it throw me `Websocket transport constructed with non-https:// or http:// host.`

In websocket.ts, in function websocketRequest(options: TransportOptions)
```ts
let webSocketAddress = constructWebSocketAddress(options.url);
```
In websocket.ts, 
```ts
function constructWebSocketAddress(url: string) {
  if (url.substr(0, 8) === "https://") {
    return wss://${url.substr(8)};
  } else if (url.substr(0, 7) === "http://") {
    return ws://${url.substr(7)};
  }
  throw new Error("Websocket transport constructed with non-https:// or http:// host.");
}
```

**What you expected to happen**
Is this check really necessary ? I tried to remove this function and it work perfectly without it (using directly /api). Can't we just make the replace IF there is http:// or https:// but do nothing if it is only a path URL ?

**Comment by johanbrandhorst** [comment]
The TS part isn't my strong side, but this sounds reasonable to me. It'll only work if you're hosting it on the same hostname as the server is running though, right?

**Comment by Virtual-felix** [comment]
Well, yes making the call on a path URL (i.e '/api') will make it on the same hostname. In my case, it will make the call on the Nginx server (which serves the TS), and Nginx will redirect this call to the URL I put in my nginx configuration, so it can be either the same hostname with a different port or a distant server, anyway the Nginx will act as a proxy.
But indeed if you do this you need to have a corresponding infrastructure. If it is not the case, currently it thows the error I mentioned but with my suggestion it would just probably return you a Cross Origin Request Blocked or something else

**Comment by johanbrandhorst** [comment]
I'd be happy to consider a PR for this, if you've got the time. I think we'd need @MarcusLongmuir or @jonny-improbable to review it though, but it's worthwhile raising it I think :).

**Comment by Virtual-felix** [comment]
Ok so after investigation and test, it is in fact a limitation of the WebSocket rfc https://html.spec.whatwg.org/multipage/web-sockets.html#dom-websocket, websocket URLs need to start with ws:// or wss://. My bad, I close the issue.
