### ISSUE TITLE
Slow server-side streaming with gRPC c++ backend + grpcwebproxy + grpc-web

### ISSUE THREAD

**Issue by wthwlh** [improbable-eng/grpc-web#629]
I am trying to use a c++ gRPC back-end to stream data to my browser as front-end, the package is around 200kb (as I logged out). Deploy all required components as different containers on my local machine. The streaming speed is around 20Hz.

**Versions of relevant software used**
gRPC c++ v1.19.0 as backend (Ubuntu 16.04)
grpcwebproxy latest version
grpc-web v0.11.0 as frontend
nginx:1.15.10

**What happened**
Front-end received the streaming data with accumulated latency. (it could be accumulated to 13 seconds as I tested)

**What you expected to happen**
Front-end could receive streaming data with acceptable latency (within 1 second?)

**Some of my configs of different containers**
grpcwebproxy:
```bash
grpcwebproxy --backend_addr=localhost:50050 --run_tls_server=false --allow_all_origins=true --server_http_max_write_timeout=2h
```
nginx:
```nginx
location /subscribe/ {
    proxy_pass http://localhost:8080/;
    proxy_pass_request_headers on;
    proxy_http_version 1.1;
  }
```

**Anything else we need to know**
I have tried out subscribing from my backend by connecting server via a c++ client (listen directly to port 50050 without passing through with same request). The latency could be within 1ms. 

Therefore I post it here to see if I have missed something that need to be configured properly. Any suggestions? Thanks.

**Comment by johanbrandhorst** [comment]
Hi! Am I understanding correctly that the transfer speed just seems slow between the gRPC backend and gRPC-Web frontend? Are you using Fetch or the Websocket transport? The only thing I can think of is that your nginx is artificially limiting your connection to the backend to HTTP/1.1, when it might support HTTP/2. Could you remove the nginx middleman? It shouldn't be necessary for something as simple as this.

**Comment by wthwlh** [comment]
@johanbrandhorst Hi thanks for the response. I cannot remove that nginx middleman or the request may return a 502 error. It seems I have to pass my request along with http1.1 header to grpcwebproxy (or is that true?). Another thing that worth to mention is, the latency disappeared with Firefox browser, but it still exists when using Chrome.

**Comment by johanbrandhorst** [comment]
It may be that your frontend code is slowing down the parsing? If it works fine with Firefox and not with Chrome it would seem to discredit the idea that it's a proxy or network issue. I don't think there's much we can do here without more information.

**Comment by wthwlh** [comment]
@johanbrandhorst Yeah I guess so, it also behaves differently on different machine. I thought you may have encountered this so I post it here. But thanks for all the responses and thoughts!
