### ISSUE TITLE
ServeHTTP should support HTTP2 / vanilla gRPC

### ISSUE THREAD

**Issue by philipithomas** [improbable-eng/grpc-web#63]
It looks like the Serve HTTP does not currently support vanilla HTTP2 gRPC requests. 

I propose changing the ServeHTTP to check defer to grpcServer.ServeHTTP when the request is HTTP2.

It should look something like this:

```go
func (w *WrappedGrpcServer) ServeHTTP(resp http.ResponseWriter, req *http.Request) {
	if r.ProtoMajor == 2 && strings.Contains(r.Header.Get("Content-Type"), "application/grpc") {
			w.grpcServer.ServeHTTP(w, r)
        } else if w.IsAcceptableGrpcCorsRequest(req) || w.IsGrpcWebRequest(req) {
		w.corsWrapper.Handler(http.HandlerFunc(w.HandleGrpcWebRequest)).ServeHTTP(resp, req)
		return
	}
	w.server.ServeHTTP(resp, req)
}
```
([source parent](https://github.com/google/keytransparency/blob/ad24e6d02c6b2cd5318183667cf995b56da0a42d/frontend/frontend.go))

**So -** is this approach ok? If I code it, will it get merged?

**Comment by MarcusLongmuir** [comment]
@philipithomas: This makes sense. Can you open a PR please?

**Comment by johanbrandhorst** [comment]
This issue confuses me a little, as w.grpcServer is currently not a field on the wrapper? I was going to suggest something similar to this but instead changing the parameter to the `WrapServer` method to a `http.Handler` to make it more composable. The restriction on a `*grpc.Server` type means you can't chain handlers easily with the wrapper. I think this would solve both these problems by letting th user define this handling themselves, if they wish, and passing that handler into the wrapper.

**Comment by johanbrandhorst** [comment]
I've opened https://github.com/improbable-eng/grpc-web/pull/81 which contains the suggested change.

**Comment by easyCZ** [comment]
Stale. Closing.

**Comment by frederikhors** [comment]
@MarcusLongmuir maybe we should reopen this?
