### ISSUE TITLE
Query: Can I use grpc-web Go wrapper package for production? Since I didn't like the envoy layer in between

### ISSUE THREAD

**Issue by cyantarek** [improbable-eng/grpc-web#661]

**Comment by johanbrandhorst** [comment]
Yes, the grpcweb wrapper is production ready, but note that you may get some degraded gRPC performance as it relies on the grpc server `ServeHTTP` method, which [in testing suffered some performance drawbacks](https://github.com/grpc/grpc-go/issues/586).

**Comment by johanbrandhorst** [comment]
Alternatively, you can deploy the go proxy instead of envoy between your frontend and backend services.

**Comment by cyantarek** [comment]
Great. And what about load balancing to those backend gRPC services when running on Kubernetes?

**Comment by johanbrandhorst** [comment]
It's just HTTP/1.1 or HTTP/2. It's no different from other networked services. You probably want one proxy per backend

**Comment by cyantarek** [comment]
Silly question: How can I check if my gRPC is running as HTTP/1.1 or HTTP/2 mode?
