### ISSUE TITLE
Naming & reference to the library

### ISSUE THREAD

**Issue by smnbbrv** [improbable-eng/grpc-web#667]
Hi guys,

love what you are doing and want to use it in https://github.com/ngx-grpc/ngx-grpc as one of client implementations.

However, I face a funny issue that's not anyhow connected to the library itself. 

I need to call the client library somehow, so I would have one `grpc-web-client` for google's grpc-web client already.

How should I refer to the client that connects to your library?

Would something like `@ngx-grpc/improbable-eng-client` or similar violate your terms of conditions / policies etc? How could I refer to your grpc-web implementation?

Thanks!

**Comment by johanbrandhorst** [comment]
The npm package name is `improbable-eng/grpc-web`: https://www.npmjs.com/package/@improbable-eng/grpc-web. How does that sound?

**Comment by smnbbrv** [comment]
So, @ngx-grpc/improbable-eng-grpc-web-client would be the right name then, is that what you mean?

**Comment by johanbrandhorst** [comment]
I suppose so :smile:.

**Comment by smnbbrv** [comment]
Creepy 😂😂😂 however the end result matters. Thank you for the advice 🙂
