### ISSUE TITLE
Client compatible with grpc-java? Any example ?

### ISSUE THREAD

**Issue by fabm22** [improbable-eng/grpc-web#67]
Hi, 

Is it possible to use the grpc-web client with the Java impl [grpc-java]( https://github.com/grpc/grpc-java)   (instead of the go server, basically)  ?

Has anyone successfully managed to make both talk to each other ? 

If so, would there be an example anywhere ?

Thanks a lot,  kinda lost here.

**Comment by fabm22** [comment]
So, from what I am getting, the only option I have currently is to use the [grpcwebproxy ](https://github.com/improbable-eng/grpc-web/tree/master/go/grpcwebproxy) kindly provided in this very repo in front of the java backend, and have the proxy talk with the browser.

Am I right ?
And any performances points to consider maybe in this case ? Was this configuration tested by people ?

Thanks a lot for your confirmation/help

**Comment by philipithomas** [comment]
Can you clarify whether you want to use grpc-java as the client or the server?

If it's the client, related to issue #63, as long as you serve standard gRPC in addition to grpc-web, it will function just like a normal gRPC server.

If it's the server, then - this code is not available in as a Java library.

**Comment by jonnyreeves** [comment]
Correct, [grpcwebproxy](https://github.com/improbable-eng/grpc-web/tree/master/go/grpcwebproxy) is indeed intended to sit infront of an existing gRPC server to allow gRPC-web clients to connect; the proxy itself has minimal business logic, however if it's on a separate box then there will be increased network latency.

Alternatively, you could look to port the [grpcweb logic](https://github.com/improbable-eng/grpc-web/tree/master/go/grpcweb/wrapper.go) to java - I'm sure others would also welcome this addition.
