### ISSUE TITLE
Setting gRPC message length.

### ISSUE THREAD

**Issue by arturgontijo** [improbable-eng/grpc-web#679]
**Versions of relevant software used**
"@improbable-eng/grpc-web": "^0.12.0"
**What happened**
rawOnError 8 Received message larger than max (5931980 vs. 4194304)
**What you expected to happen**
Be able to increase the default max receive message size. 
**How to reproduce it (as minimally and precisely as possible)**:
I've tried to illustrate it using the repo's example code.
**Full logs to relevant components**
```
rawOnEnd 8 Received message larger than max (5931980 vs. 4194304) 
{…}
headersMap: {…}
"access-control-allow-credentials": Array [ "true" ]
"access-control-allow-origin": Array [ "http://localhost:7010" ]
"content-type": Array [ "application/grpc+proto" ]
"grpc-message": Array [ "Received message larger than max (5931980 vs. 4194304)" ]
"grpc-status": Array [ "8" ]
vary: Array [ "Origin" ]
<prototype>: Object { … }
<prototype>: Object { appendFromString: appendFromString(e), delete: delete(e, t), append: append(e, t), … }
 ```

**Anything else we need to know**

Is it possible to set these fields when use has only access to the `invoke` (or other) function?
```
    "grpc.max_receive_message_length": 10 * 1024 * 1024,
    "grpc.max_send_message_length": 10 * 1024 * 1024
```

My current code is something like this:
```
import {Client, Code} from "third-party-sdk";

// Import code-generated data structures.
import {BookService} from "../_proto/examplecom/library/book_service_pb_service";
import {QueryBooksRequest, Book, GetBookRequest} from "../_proto/examplecom/library/book_service_pb";

const queryBooksRequest = new QueryBooksRequest();
queryBooksRequest.setAuthorPrefix("Geor");
Client.invoke(BookService.QueryBooks, {
  request: queryBooksRequest,
  host: "https://example.com",
  onMessage: (message: Book) => {
    console.log("got book: ", message.toObject());
  },
  onEnd: (code: Code, msg: string | undefined, trailers: Metadata) => {
    if (code == Code.OK) {
      console.log("all ok")
    } else {
      console.log("hit an error", code, msg, trailers);
    }
  }
});
```

If not what would be the right way to set them? Is it possible to ask the "third-party-sdk" to increase it in their code? I see that this can be achieved easily with the `grpcwebproxy` but not sure if this is the way to also set it in your library.

If I made the request using Python (with the options set) I can sent/receive the desired data.

BTW, I tried to access the Slack channel (from `README.md`) but got this error:
```This invite link is no longer active.```

**Comment by johanbrandhorst** [comment]
> BTW, I tried to access the Slack channel (from README.md) but got this error:
This invite link is no longer active.

Ah this isn't great, we basically stopped using that slack so we should remove it. Sorry about that.

As for your question, there is nothing you can do in the client to change the server max messages size (for security reasons), so you will have to ask your third party API to up this (in their proxy or on their server), or adjust your request accordingly. Unless you're the one running the proxy?

**Comment by arturgontijo** [comment]
> Unless you're the one running the proxy?

No, I'm not =/

Will close this one and get back as soon as I get a solution for it.
Thanks @johanbrandhorst

**Comment by arturgontijo** [comment]
Just to mark this as "solved", we've added these options in our own go proxy (following yours):
```
opts = grpc.WithDefaultCallOptions(
    grpc.MaxCallRecvMsgSize(10*1024*1024), 
    grpc.MaxCallSendMsgSize(10*1024*1024)
),
conn, err := grpc.Dial(passthroughURL.Host, grpc.WithInsecure(), opts)
```
