### ISSUE TITLE
Http download support via grpc web proxy

### ISSUE THREAD

**Issue by jvmlet** [improbable-eng/grpc-web#680]
Hello 
Does it make sense to support http download via grpc web proxy? I know this would probably violate the grpc web specification, but it might be useful extention. 
The proxied grpc call should have the predefined response proto message, like bytes, extension, content type, filename ect., everything needed to produce the valid http response for download. You will also publish the proto with service definition and have a special treatment in proxy implementation to feed http response accordingly.
Thanks

**Comment by johanbrandhorst** [comment]
Hi, yes this is a really interesting idea, it's been considered before, but regardless this is not the place to discuss this. I recommend opening an issue against gRPC itself or the official grpc-web repo. We're not going to spend the time implementing something that is not spec compliant at this point.

**Comment by jvmlet** [comment]
Thanks. https://github.com/grpc/grpc-web/issues/770
