### ISSUE TITLE
Error Expected HTTP/ when calling gRPC endpoints

### ISSUE THREAD

**Issue by nboukeffa** [improbable-eng/grpc-web#689]
Hi,

I'm trying to build a GraphQL API in Typescript connected to gRPC services written in Go.

The gRPC is working well (I think) since I can call it from another gRPC (desktop) client but the when using `grpc-web` I get the following error (everything's running locally):

```
NodeHttp.error Error: Parse Error: Expected HTTP/
    at Socket.socketOnData (_http_client.js:456:22)
    at Socket.emit (events.js:223:5)
    at Socket.EventEmitter.emit (domain.js:475:20)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:181:23) {
  bytesParsed: 0,
  code: 'HPE_INVALID_CONSTANT',
  reason: 'Expected HTTP/',
  rawPacket: <Buffer 00 00 06 04 00 00 00 00 00 00 05 00 00 40 00>
}
grpc.onEnd
rawOnError 2 Response closed without headers
```

Any idea what I'm missing?

Here the code of GraphQL API:
```ts
import { ApolloServer } from "apollo-server";
import { NodeHttpTransport } from "@improbable-eng/grpc-web-node-http-transport";
import { UserServiceClient } from "./pb/user-svc_pb_service";
import { GetUserRequest, User, GetUserResponse } from "./pb/user-svc_pb";
import typeDefs from "./schema";

const client = new UserServiceClient("http://127.0.0.1:8080/", {
  transport: NodeHttpTransport(),
  debug: true,
});

const resolvers = {
  Query: {
    getUserById: (_, { id }) => {
      let req = new GetUserRequest();
      req.setId(id);
      client.getUser(req, _, (err, res: GetUserResponse) => {
        console.log(err);
        if (err) return err;
        return res.getUser();
      });
    },
  },
};

const server = new ApolloServer({
  typeDefs,
  resolvers,
});

server.listen().then(({ url }) => {
  console.log(`🚀 Server ready at ${url}`);
});
```

**Comment by johanbrandhorst** [comment]
I'm no node expert, so I can't help you with this error, but if you're using a Node server I would recommend using the official node gRPC plugin instead of grpc-web. This package is meant to be used when you're executing code in the browser. It seems to me you don't have that need, since you're implementing a GraphQL server. I would suggest looking at the official node docs: https://grpc.io/docs/tutorials/basic/node/.

**Comment by nboukeffa** [comment]
Thanks for you answer. As you suggested, I switched to the official node library and succeed to make it work with statically generated code. 

I followed this example that explain also how to generate Typescript definitions:
https://github.com/agreatfool/grpc_tools_node_protoc_ts/blob/master/examples/src/client.ts

Thanks for the help.
