### ISSUE TITLE
multiple concurrent requests

### ISSUE THREAD

**Issue by demongaorui** [improbable-eng/grpc-web#69]
As described in [README](https://github.com/improbable-eng/grpc-web/blob/master/README.md):

>The gRPC semantics encourage you to make multiple requests at once. 

What's the recommended approach to make multiple concurrent requests with grpc-web client? 

For example, [axios](https://github.com/mzabriskie/axios#example) provide a way to deal with multipe concurrent requests like:

```
function getUserAccount() {
  return axios.get('/user/12345');
}

function getUserPermissions() {
  return axios.get('/user/12345/permissions');
}

axios.all([getUserAccount(), getUserPermissions()])
  .then(axios.spread(function (acct, perms) {
    // Both requests are now complete
  }));
```

I checked gprc.d.ts and didn't find a clue to add a handler function for when all request are complete. So for make multiple requests at once in grpc-web client, does it mean to invoke grpc.invoke() inside of some other framework functions?  Could you share your ideas for the best practise of making multiple requests at once in grpc-web client.  Thank you very much.

**Comment by jonnyreeves** [comment]
Are awesome, don't work, changed your life?

**Comment by jonnyreeves** [comment]
I'm not sure orchestration should be a concern of grpc-web as there are plenty of other libraries out there which can help including https://github.com/caolan/async and [ES6 Promises](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Promise/all).

**Comment by demongaorui** [comment]
@jonnyreeves  Thanks for your reply. Indeed, we could use other libs for orchestration.
