### ISSUE TITLE
gRPC Web Stream Ended Almost Immediately After Client Gets It

### ISSUE THREAD

**Issue by duckladydinh** [improbable-eng/grpc-web#693]
Hi,

does anyone know how to use server stream with gRPC Web? After I get the stream and add the listeners to 'data', 'status' and 'end'. The 'end' signal is sent immediately but I have never closed the stream on either server or client.

If we send the data immediately after the server gets hold of the stream, the client can still receive it but the 'end' signal still happens immediately.

Is this a bug?

Thanks

**Comment by jdollar** [comment]
@duckladydinh I was kind of scratching my head with that was up with my server streaming for a while where it sounds like similar was happening. Client would get a single message, the proxy would state "transport is closing" and the client would error out and the server would still be trying to send messages. 

Ended up my issue was related to the write and read timeouts from this issue: https://github.com/improbable-eng/grpc-web/issues/171. Upping those higher than the default 10s allowed my stream to function as expected. Unsure if that helps at all? Are there any errors in the logs of the proxy server?

**Comment by johanbrandhorst** [comment]
Could it also be a context cancellation? If the user closes the browser/web page it will cancel the underlying connection which is propagated to the server.

**Comment by duckladydinh** [comment]
> @duckladydinh I was kind of scratching my head with that was up with my server streaming for a while where it sounds like similar was happening. Client would get a single message, the proxy would state "transport is closing" and the client would error out and the server would still be trying to send messages.
> 
> Ended up my issue was related to the write and read timeouts from this issue: #171. Upping those higher than the default 10s allowed my stream to function as expected. Unsure if that helps at all? Are there any errors in the logs of the proxy server?

Hi @jdollar , thank you for the information. Actually I did not use any proxy server. All I did was to to use improbable-eng/grpc-web wrapper as can be seen here: https://github.com/duckladydinh/gochat/blob/master/go/main/main.go.

There is absolutely no log in the server. The client, after getting the stream, will just end naturally. I think there may be some connection with the read and write timeout as you mentioned, but do you maybe know how to configure it with grpc-web?

Thanks.

**Comment by duckladydinh** [comment]
> Could it also be a context cancellation? If the user closes the browser/web page it will cancel the underlying connection which is propagated to the server.

Hi @johanbrandhorst , actually the browser was never closed. The stream just ends in the most natural way without any exception. I think there may be some timeout configuration that I don't know. Do you happen to know how to configure it?

**Comment by johanbrandhorst** [comment]
The problem might be how you're using the stream: https://github.com/duckladydinh/gochat/blob/master/go/service/chat_service.go#L44-L56. I don't know if it's safe for you to return from this function and assume the stream is kept open. I think you need to keep it running.

Closing as unrelated to grpc-web.
