### ISSUE TITLE
show json like response in network tab

### ISSUE THREAD

**Issue by kinotto** [improbable-eng/grpc-web#694]
Hello guys,
i'm currently trying to find a way to "pretty print" the response of the grpc calls inside the Chrome network tab.

I've found only this plugin
https://github.com/SafetyCulture/grpc-web-devtools

seems quite straight forward but the example is referring to the grpc web official library.

has anyone been able to integrate it, or is there any other plugin for chrome compatible with this library? 

Thank you

**Comment by johanbrandhorst** [comment]
Does that version not work with this client?

**Comment by kinotto** [comment]
it doesn't seem to work for me, it keeps throwing an exception when i call the global function provided by the plugin window._GRPCWEB_DEVTOOLS_

i'm passing the service client that i get from the the compilation of the proto

![image](https://user-images.githubusercontent.com/4570071/80118875-e5724200-8580-11ea-9f4a-7e70d5fdf0ac.png)


![image](https://user-images.githubusercontent.com/4570071/80119119-308c5500-8581-11ea-9f4c-67b6912add52.png)

**Comment by johanbrandhorst** [comment]
I see, yeah that won't work. You can try setting the content type to `grpc-web-text` to see if that means the messages are sent in plaintext. I haven't experimented in this area recently.

**Comment by kinotto** [comment]
ok thank you, do you know if there is there any other way to display a human readable response in the network tab?

**Comment by johanbrandhorst** [comment]
No, I don't know. I would encourage you to look elsewhere than the network tab though, what are you trying to debug? Either print it in your frontend app or your backend service after decoding. The library takes care of the transport.

**Comment by kinotto** [comment]
i was just looking for a way to quickly check the response without explicitly log it in the console, the same way as standard http rest calls are displayed in the network tab.

**Comment by johanbrandhorst** [comment]
I see, yeah that workflow isn't terribly useful with grpc-web. It's possible to convert the encoding still of course, but it's a bit more work.

**Comment by SimiS22** [comment]
is it possible to somehow support this? At the moment its not so user friendly for the QAs in the team to make sense of the request by looking at the network tab rpc calls.

**Comment by johanbrandhorst** [comment]
You can use the grpc-web-text transport encoding with our proxy, but our client doesn't support anything other than protobuf. The idea is that you shouldn't care about what's being sent over the network tab, it's generated, all you need to do is inspect the data in your client or your server.

**Comment by SimiS22** [comment]
@johanbrandhorst thanks for the reply. The team is used to [gPRC chrome plugin](https://chrome.google.com/webstore/detail/grpc-web-developer-tools/ddamlpimmiapbcopeoifjfmoabdbfbjj). And we are considering switching to improbable. This is one of the things we have to find a workaround by ourself then :)

**Comment by johanbrandhorst** [comment]
If you use https://github.com/grpc/grpc-web you can use the `grpc-web-text` transport encoding which might make the messages more readable, I haven't investigated it myself.
