### ISSUE TITLE
native browser javascript client?

### ISSUE THREAD

**Issue by wiktortomczak** [improbable-eng/grpc-web#72]
Is there a native browser javascript client library for making requests to your grpcweb server?

If not, how to understand how such a client should be implemented? In particular: the format of messages, the transport(s) to use. Code examples together with example network traces would be the best.

Thanks

Note: I'm aware of the spec https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-WEB.md

**Comment by MarcusLongmuir** [comment]
Hey @wiktortomczak.

Can you describe how what you're looking for differs from [grpc-web-client](https://github.com/improbable-eng/grpc-web/tree/master/ts)? I'm not sure I understand what you mean by "native browser javascript client".

**Comment by mwitkow** [comment]
@wiktortomczak the content of this repo is both the server-side (Go middleware or Proxy) and the Typescript/JS client + code gen bundle.

As Marcus pointed out, please consult the grpc-web-client docs and reopen if you find them unclear :)
