### ISSUE TITLE
Cors Error / Invalid_HTTP_Response 

### ISSUE THREAD

**Issue by SabariVig** [improbable-eng/grpc-web#721]
**Versions of relevant software used**
Latest 

**What happened**
Cors Error

**How to reproduce it (as minimally and precisely as possible)**:
```
import { grpc } from '@improbable-eng/grpc-web'
import {MovieService} from './generated/movie_pb_service'
import  {Movie,Search } from './generated/movie_pb'
import { NodeHttpTransport } from '@improbable-eng/grpc-web-node-http-transport'

const index = () => {
grpc.setDefaultTransport(NodeHttpTransport())
const call = new Search()

call.setId(5)

grpc.invoke(MovieService.GetMovie,{
	request: call,
	host: "http://localhost:7899",
	onMessage: (message: Movie)=>{
console.log("Recived",message.toObject());

	},
	onEnd:(code:grpc.Code,msg:string | undefined | number, trailers: grpc.Metadata)=>{
   if(code = grpc.Code.OK){
			console.log("Worked")
	 }else{
			console.log("Not Working")
	 }
	}
});

	return (
		<div>
			hello			
		</div>
	)
}
export default index
```
**Full logs to relevant components**

![image](https://user-images.githubusercontent.com/33371586/86921287-86b47180-c148-11ea-935c-b40152260518.png)

![image](https://user-images.githubusercontent.com/33371586/86921487-d5620b80-c148-11ea-9659-7acc406e3170.png)

Using Nextjs

**Comment by johanbrandhorst** [comment]
You may need to configure CORS on your proxy. See https://github.com/improbable-eng/grpc-web/blob/279e29633558cddc6c1d0545efa3a8b0b106ac4f/go/grpcweb/options.go#L52.

**Comment by SabariVig** [comment]
is it possible to get it working with envoy proxy.
im getting grpc-message: upstream connect error or disconnect/reset before headers. reset reason: connection failure.
sorry if its out of scope. feel free to close it incase

**Comment by johanbrandhorst** [comment]
Hey, yeah, it definitely should be possible to configure the envoy proxy to allow this, but I haven't used it myself, so I think this isn't the right place to ask. Maybe try the envoy documentation?

I'm going to close this as its not related to our proxy or client.
