### ISSUE TITLE
How can I not use the set method when setting request parameters, but use the json method commonly used on the web instead

### ISSUE THREAD

**Issue by victorv587** [improbable-eng/grpc-web#775]
> 创建请求参数时，我们总是需要
>  const queryBooksRequest = new QueryBooksRequest();
>  queryBooksRequest.setAuthorPrefix("Geor");这样来创建
> 有什么方法可以直接使用json的方式来代替呢？
> 例如:{authorPrefix:'Geor'}这样来创建请求参数

When creating request parameters, we always need
```
const queryBooksRequest = new QueryBooksRequest();
queryBooksRequest.setAuthorPrefix("Geor"); // Create like this
```
Is there any way to directly use json instead?
```
{authorPrefix:'Geor'} // Populate request like this
```

**Comment by johanbrandhorst** [comment]
Hi @victorv587 

I've taken the liberty of translating your issue, since none of the maintainers speak or read Chinese that I know. I apologize for any mistake Google translate made have made in translating the wording.

I don't know if this is possible with the TypeScript bindings, but if you look directly at the [generated JS for our integration tests](https://github.com/improbable-eng/grpc-web/blob/master/integration_test/ts/_proto/improbable/grpcweb/test/test_pb.js#L33), you can see there is a parameter given to the `PingRequest` constructor. I think you might be able to do
```
const queryBooksRequest = new QueryBooksRequest({"authorPrefix":"Geor"});
```

**Comment by victorv587** [comment]
> 嗨@ victorv587
> 
> 由于您没有维护者会说或不会读我所知道的中文，因此我可以自由地翻译您的问题。对于Google翻译在翻译措辞时所犯的任何错误，我深表歉意。
> 
> 我不知道使用TypeScript绑定是否可行，但是如果直接查看[为我们的集成测试生成的JS](https://github.com/improbable-eng/grpc-web/blob/master/integration_test/ts/_proto/improbable/grpcweb/test/test_pb.js#L33)，则可以看到有一个参数提供给`PingRequest`构造函数。我想你也许可以
> 
> ```
> const queryBooksRequest = new QueryBooksRequest({"authorPrefix":"Geor"});
Thank you for your answer. In your way, my question has been solved

**Comment by victorv587** [comment]
> 嗨@ victorv587
> 
> 由于您没有维护者会说或不会读我所知道的中文，因此我可以自由地翻译您的问题。对于Google翻译在翻译措辞时所犯的任何错误，我深表歉意。
> 
> 我不知道使用TypeScript绑定是否可行，但是如果直接查看[为我们的集成测试生成的JS](https://github.com/improbable-eng/grpc-web/blob/master/integration_test/ts/_proto/improbable/grpcweb/test/test_pb.js#L33)，则可以看到有一个参数提供给`PingRequest`构造函数。我想你也许可以
> 
> ```
> const queryBooksRequest = new QueryBooksRequest({"authorPrefix":"Geor"});
> ```

你刚刚提到的那种方法并没有起作用，参数没有接收到，请问还有其他方式能够解决这个问题吗？

**Comment by victorv587** [comment]
> 嗨@ victorv587
> 
> 由于您没有维护者会说或不会读我所知道的中文，因此我可以自由地翻译您的问题。对于Google翻译在翻译措辞时所犯的任何错误，我深表歉意。
> 
> 我不知道使用TypeScript绑定是否可行，但是如果直接查看[为我们的集成测试生成的JS](https://github.com/improbable-eng/grpc-web/blob/master/integration_test/ts/_proto/improbable/grpcweb/test/test_pb.js#L33)，则可以看到有一个参数提供给`PingRequest`构造函数。我想你也许可以
> 
> ```
> const queryBooksRequest = new QueryBooksRequest({"authorPrefix":"Geor"

> 嗨@ victorv587
> 
> 由于您没有维护者会说或不会读我所知道的中文，因此我可以自由地翻译您的问题。对于Google翻译在翻译措辞时所犯的任何错误，我深表歉意。
> 
> 我不知道使用TypeScript绑定是否可行，但是如果直接查看[为我们的集成测试生成的JS](https://github.com/improbable-eng/grpc-web/blob/master/integration_test/ts/_proto/improbable/grpcweb/test/test_pb.js#L33)，则可以看到有一个参数提供给`PingRequest`构造函数。我想你也许可以
> 
> ```
> const queryBooksRequest = new QueryBooksRequest({"authorPrefix":"Geor"});
> ```

Thank you for your ideas, I found that this way can be used to achieve
const queryBooksRequest = new QueryBooksRequest(['Gero']);
