### ISSUE TITLE
[Feature Request] Generated Golang Client

### ISSUE THREAD

**Issue by jingweno** [improbable-eng/grpc-web#781]
**Versions of relevant software used**

N/A

**What happened**

I'm curious whether there are plans to add a generator for a Golang client besides the Typescript one. I saw examples in the test and it looks possible: https://github.com/improbable-eng/grpc-web/blob/master/go/grpcweb/wrapper_test.go#L196. My use case is to use the Golang client on the browser with [wasm](https://github.com/golang/go/wiki/WebAssembly)

**What you expected to happen**

There is a generator to generate a grpc-web Golang Client besides the Typescript one.

**How to reproduce it (as minimally and precisely as possible)**:

N/A

**Full logs to relevant components**

N/A

**Anything else we need to know**

N/A

**Comment by johanbrandhorst** [comment]
Hi, there are no plans to do this, and the eventual goal is to support grpc-web natively in Wasm through the proposed transport interface. It's not something we will be implementing in this repo. See https://github.com/grpc/grpc-go/issues/2294.

**Comment by fabstu** [comment]
It seems transports were deprioritized before finishing, sadly.

https://github.com/grpc/grpc-go/issues/906#issuecomment-691332579
