### ISSUE TITLE
Maximum number of server-side streaming requests

### ISSUE THREAD

**Issue by zonque** [improbable-eng/grpc-web#783]
I'm running Vue.js an application that makes use of server-side streaming gRPC protocols. Per invocation of the application, about 6 streams are opened and read from. This usually works fine if there is only one window per browser, but it breaks when a second instance to the same server is opened. The effect I see then is that the POST requests to the streaming endpoints remain in a 'pending' state, but once the other instance is ended (the window is closed), they proceed just fine.

I haven't found any documentation on this, but apparently there is a per-remote, per-browser limit of some sort that also seems to differ on different platforms and browsers.

Is this a known issue? Are there any ideas in how to work around this?

**Comment by johanbrandhorst** [comment]
This is a browser-side issue, nothing we can do about it unfortunately. The workaround is to open fewer streams :grimacing:.

**Comment by zonque** [comment]
Too bad. Are the limits at least documented somewhere?

**Comment by johanbrandhorst** [comment]
https://stackoverflow.com/questions/985431/max-parallel-http-connections-in-a-browser? I just googled "max 6 connections".

**Comment by zonque** [comment]
Alright, thanks a lot!
