### ISSUE TITLE
Node gRPC server using GCP Cloud Endpoint

### ISSUE THREAD

**Issue by pjm17971** [improbable-eng/grpc-web#79]
Hi,

This library looks super useful, but a question:

I have a gRPC server running (node.js), deployed onto Google Cloud with GKE and Cloud Endpoints. Another node.js client is capable of calling this endpoint from inside or outside of GCP using an JWT token and that works fine. Is it possible to use this library with such a cloud endpoint and call my service from a web application?

Thanks!

**Comment by jonnyreeves** [comment]
Yep totally, you probably want to make use of the pre-built [grpcweb-proxy](https://github.com/improbable-eng/grpc-web/tree/master/go/grpcwebproxy) which you can run as a standalone service in GKE infront of your node.js gRPC Server, ie:

![untitled drawing](https://user-images.githubusercontent.com/200185/29635444-fdee5436-8844-11e7-8ca6-71b77057138b.jpg)

Let us know how you get on :)

**Comment by pjm17971** [comment]
Well some progress today on this. We have something like this setup, and from a typescript react application we are able to make an gRPC call to the gRPC-proxy. Yay, type completion on the client and we can still call the gRPC API from another non-web client!

![grpc](https://user-images.githubusercontent.com/1288813/29847091-c1df0a9c-8cce-11e7-9f05-70270dc34fd1.png)

However, the problem here is that we are doing an end run around the [ESP](https://github.com/cloudendpoints/esp), so we lose all the management capabilities of that. I'd imagine that the ideal solution here might be to extend the ESP to provide the functionality of the grpc-proxy in the same way that it seems to already be extended to allow [transcoding](https://cloud.google.com/endpoints/docs/grpc/transcoding) of gRPC to HTTP/1.1 REST. Unfortunately such a project is probably out of scope for us.

Any thoughts?
