### ISSUE TITLE
how to set client dealine in browser environment?

### ISSUE THREAD

**Issue by washanhanzi** [improbable-eng/grpc-web#831]
I have a go grpc backend, and sent grpc-web request from the browser.

If I implanted a check for the request deadline on server, like:

```
d, ok := ctx.Deadline()
```

The question is how to set it in grpc-web? I use envoy as the proxy.

**Comment by johanbrandhorst** [comment]
You can set the timeout in the call to `Invoke`: https://github.com/improbable-eng/grpc-web/blob/master/integration_test/ts/src/invoke.spec.ts#L235.

**Comment by xu1718191411** [comment]
@johanbrandhorst 
Sorry I am still confused on how to set an deadline at client side.
The reference showed me is setting timeout of test code.

As the grpc side shows us that it is better to setup timeout config on client side.
https://grpc.io/blog/deadlines/

Could you give me some hint if it is possible?
Thank you

**Comment by johanbrandhorst** [comment]
Hm, I think you're right I linked the wrong thing. I think you can manually set the timeout with a header called `grpc-timeout: 10s` (for 10 seconds) when making the request on the client. I haven't got an example of that.

**Comment by fatfatson** [comment]
> Hm, I think you're right I linked the wrong thing. I think you can manually set the timeout with a header called `grpc-timeout: 10s` (for 10 seconds) when making the request on the client. I haven't got an example of that.

setting the `grpc-timeout` header leads below result:

00000000: 7270 6320 6572 726f 723a 2063 6f64 6520  rpc error: code 
00000001: 3d20 496e 7465 726e 616c 2064 6573 6320  = Internal desc 
00000002: 3d20 6d61 6c66 6f72 6d65 6420 7469 6d65  = malformed time
00000003: 2d6f 7574 3a20 7472 616e 7370 6f72 743a  -out: transport:
00000004: 2074 696d 656f 7574 2075 6e69 7420 6973   timeout unit is
00000005: 206e 6f74 2072 6563 6f67 6e69 7a65 643a   not recognized:
00000006: 2022 3230 3022 0a                         "200".

**Comment by johanbrandhorst** [comment]
Sorry, it's `10S` for 10 seconds. See the gRPC spec for the timeout units: https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md#requests

**Comment by fatfatson** [comment]
> Sorry, it's `10S` for 10 seconds. See the gRPC spec for the timeout units: https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md#requests

thanks!
but if there's a spell mistake, the browser client won't receive a error callback.
