### ISSUE TITLE
Add ability to set-cookie on response

### ISSUE THREAD

**Issue by kostyay** [improbable-eng/grpc-web#833]
Hey there
I'm using grpc-web go server wrapper and I would like to have an option to return custom headers, specifically Set-Cookie from response based on metadata attached to grpc.
What would be the best way to implement it? 
I debugged the code abit and can't find the best place.
Thanks in advance.

**Comment by kostyay** [comment]
In case anyone is wondering this is how u can do it:

```go
grpc.SendHeader(ctx, metadata.Pairs("Set-Cookie", "cookie=f00"))
```

**Comment by forgoty** [comment]
In my case worked this:
```go
_ = grpc.SetTrailer(ctx, metadata.Pairs("Set-Cookie", "cookie=asdf"))
```
