### ISSUE TITLE
Passing token based auth through proxy?

### ISSUE THREAD

**Issue by jdugan1024** [improbable-eng/grpc-web#84]
Hello, I'm working with @pjm17971 and this is a follow up to #79.  Thanks for grpc-web -- I think it's fantastic idea and we'd really love to use it in our project.

We're trying to use the grpc-web proxy to talk to an gRPC server that is fronted by [Google Cloud Endpoints](https://cloud.google.com/endpoints/)  -- I've attached a diagram.  We are using JWT tokens for authentication.  It seems like the token isn't making it through the grpcwebproxy.  I've looked at the code and I can't see why that isn't getting passed through.

Do you think the JWT token should be making it through to the backend server?  Is there someplace I'd need to add something to help with that?  I'm totally fine adding some code but I'm not sure I fully get how the proxy works and so I'm not sure if that would be an adjustment to the grpcwebproxy code or perhaps to the grpc-proxy library.  Any pointer you could give would be greatly appreciated! 

![esp](https://user-images.githubusercontent.com/589276/29946403-c7c505ae-8e6a-11e7-8821-a7a26ea738f9.png)

**Comment by pjm17971** [comment]
@jonnyreeves Any thoughts on this one? We never came up with a solution for this but are still interested in making this work. Thanks!

**Comment by ypoluektovich** [comment]
This appears to be the same as #91.
