### ISSUE TITLE
Websocket transport

### ISSUE THREAD

**Issue by pkieltyka** [improbable-eng/grpc-web#85]
Thanks very much for this project. Just a thought - it would be nice to see the project designed in such a way that the transport can be swapped out. I think a WS/WSS transport would work quite well for gRPC-Web with full streaming support and even better browser compatibility than what this current project supports.

**Comment by easyCZ** [comment]
Please see https://github.com/improbable-eng/grpc-web/pull/137 for websocket support. Feedback welcome.
