### ISSUE TITLE
Debugger Interface Proposal

### ISSUE THREAD

**Issue by easyCZ** [improbable-eng/grpc-web#87]
This is a proposal for a debugger interface in grpc-web-client. The intent is to make the current console based debugger extensible and allow clients to implement their own version of the debugger. The driving factor is to improve the currently tedious debugging experience where grpc-web requests shown in the Network tab are not properly serialized and hard to inspect. The proposed interface allows for an extension to be build for Chrome & Firefox to expose grpc-web requests similarly to the Network tab in Chrome.

This document is an aimed athelping shape the debugger interface and get feedback on the proposed changes.

## Interface
The interface proposed consists of a `DebuggerProvider` and a `Debugger`.

### DebuggerProvider
The provider is responsible for supplying an instance of a debugger to be used in a particular request. Additionally, it can implement supplemental functionality such as tracking of requests or recording request history.
```typescript
export interface DebuggerProvider {
    // Obtain an instance of a debugger.
    // A convenience proxy allowing the provider to implement additional functionality
    // such as tracking history of requests
    getInstanceForRequest(id: number): Debugger;
}
```

### Debugger
The `Debugger` implements callback methods for the lifecycle of a grpc-web request.
```typescript
// Implements callbacks for grpc-web request/response lifecycle events
export interface Debugger {
    // Called just before a request is fired, called only once
    onRequestStart(host: string, method: MethodDefinition): void;

    // Called just before a request is fired, called only once
    onRequestHeaders(headers: BrowserHeaders): void;

    // Called with the request payload, potentially called multiple times with request streams
    onRequestMessage(payload: Message): void;

    // Called when response headers are available, called once multiple times
    // This is a low level method intended to debug byte serialization
    onResponseHeaders(headers: BrowserHeaders, httpStatus: number): void;

    // Called with each received chunk
    onResponseChunk?(chunk: Chunk[], chunkBytes: Uint8Array): void;

    // Called with each response message, called multiple times with response streams
    onResponseMessage(payload: Message): void;

    // Called with response trailers, called once
    onResponseTrailers(metadata: BrowserHeaders): void;

    // Called when a request completes, called once
    onResponseEnd(grpcStatus: Code | null): void;

    // Called with any error occuring in the flow, potentially called multiple times
    onError(code: Code, err: Error): void;
}
```

### Example
```typescript
export class ConsoleDebuggerProvider implements DebuggerProvider {

    getInstanceForRequest(id: number): Debugger {
        return new ConsoleDebugger(id);
    }

}

export class ConsoleDebugger implements Debugger {

    readonly id: number;

    constructor(id: number) {
        this.id = id;
    }

    onRequestStart(host: string, method: MethodDefinition): void {
        debug(`gRPC-Web #${this.id}: Making request to ${host} for ${method.service.serviceName}.${method.methodName}`, method);
    }

    onRequestHeaders(headers: BrowserHeaders): void {
        debug(`gRPC-Web #${this.id}: Headers:`, headers);
    }

    onRequestMessage(payload: Message): void {
        debug(`gRPC-Web #${this.id}: Request message:`, payload.toObject());
    }

    onResponseHeaders(headers: BrowserHeaders, httpStatus: number) {
        debug(`gRPC-Web #${this.id}: Response headers:`, headers, 'HTTP Status:', httpStatus);
    }

    onResponseMessage(payload: Message): void {
        debug(`gRPC-Web #${this.id}: Response message:`, payload.toObject());
    }

    onResponseTrailers(metadata: BrowserHeaders): void {
        debug(`gRPC-Web #${this.id}: Response trailers:`, metadata);
    }

    onResponseEnd(grpcStatus: Code | any): void {
        debug(`gRPC-Web #${this.id}: Finished with status:`, grpcStatus);
    }

    onError(code: Code, err: Error): void {
        debug(`gRPC-Web #${this.id}: Error. Code:`, code, 'Error:', err);
    }

}
```

## Registration of Debuggers
In order to allow clients a custom implementation of a debugger, an API must be exposed to allow the registration, retrieval and de-registration of debuggers. The following section discusses possible scenarios of achieving this. When addressing this problem, it is important to consider a scenario where an implementation is not immediately available when an application executes, ie. extension loaded when a user opens developer tools. 

### Explict registration in client code
In this option, the client is required to explictly include any required debuggers in user code. An example might look as follows:
```typescript
grpc.registerDebugger(new ConsoleDebuggerProvider());
// extension debugger exposes itself on the window as window.__GRPC_WEB_DEVTOOLS__
if ((window as any).__GRPC_WEB_DEVTOOLS__) {
    grpc.registerDebugger((window as any).__GRPC_WEB_DEVTOOLS__);
}
```
* (+) The user is direct control of what extension runs in a given application
* (-) An extension loaded at some point in the future will not be able to register itself (can be solved by exposing grpc on the window object)

### Expose a global with a list of Debuggers
Grpc-web-client reads from a specific global variable containing a list of debuggers to use. This can be made to work in NodeJS as well.
```typescript
(function (debuggers) {
    debuggers.push(new ShinyDebuggerProvider());
    window.__GRPC_WEB_DEBUGGERS__ = debuggers;
})(window.__GRPC_WEB_DEBUGGERS__ || []);
```

* (+) An extension loaded at a later stage can attach itself without the need to have `grpc` on the global scope
* (+) No need for client code to attach an extension debugger
* (-) Pollutes global scope
* (-) Is stringly typed

## Lifecycle callback
In order to implement the debugger callbacks, we dispatch individual callbacks inside `grpc-web-client`'s `invoke` method. For example:
```typescript
const transportOptions: TransportOptions = {
    // ...
    onHeaders: (headers: Metadata, status: number) => {
        detach(() => debugger.onRequestHeaders(headers));
        // rest omitted
    }
    // ...
}
```

To simplify execution of callbacks for multiple debuggers we can utilize a proxy implementation of the `Debugger` interface which dispatches to all registered debuggers. [Example here](https://github.com/easyCZ/grpc-web/blob/debugger/ts/src/debug.ts#L107)

## Debug property
Currently, we use a `debug` property on a request invocation to determine if we should log debug information. This flag would become obsolete and could be removed/depracted.

### Working examples
* [Fork with debugger on a branch](https://github.com/easyCZ/grpc-web/tree/debugger) - [grpc.ts](https://github.com/easyCZ/grpc-web/blob/debugger/ts/src/grpc.ts), [debug.ts](https://github.com/easyCZ/grpc-web/blob/debugger/ts/src/debug.ts)
* [Grpc Web Devtools](https://github.com/easyCZ/grpc-web-devtools) - A WIP implementation of a Chrome extension implementing the above interface to provide a debugger extension similar to Chrome

What do you think? Suggestions & improvements are extremely welcome.
@jonnyreeves @MarcusLongmuir @mwitkow

**Comment by MarcusLongmuir** [comment]
- BrowserHeaders should referred to as Metadata
- `onError` is no longer exposed to the user code, so it probably shouldn't exist in the `Debugger` interface. Errors occurring during transport will result in an `onEnd` call with an appropriate status.
- `Provider` -> `Factory`?
- `DebuggerProvider/Factory` could be a function `(id: number) => Debugger`, rather than an interface with `getInstanceForRequest`

**Comment by joeblew99** [comment]
This is a really great idea... thanks everyone

**Comment by unlikely-leo** [comment]
The design of `ClientInterceptor` in the Java gRPC implementation could be relevant here: https://grpc.io/grpc-java/javadoc/index.html?io/grpc/ClientInterceptor.html

Example use: https://github.com/grpc-ecosystem/java-grpc-prometheus/tree/master/src/main/java/me/dinowernli/grpc/prometheus exports metrics on unary and stream RPCs based on `ClientInterceptor`

**Comment by mindyourlifeguide** [comment]
Any news on compatibility with gRPC-Web Developer Tools?
