### ISSUE TITLE
React native client not connecting to server when using in Android but working in ios. 

### ISSUE THREAD

**Issue by Akshith-Banda** [improbable-eng/grpc-web#873]
**Versions of relevant software used**

 "@improbable-eng/grpc-web": "^0.13.0",
 "@improbable-eng/grpc-web-react-native-transport": "^0.13.0",
 "google-protobuf": "^3.14.0",
 "react": "16.13.1",
 "react-native": "0.63.4",
 "node":"12.18.4"
  

**What happened**

By going through example provided at [https://github.com/improbable-eng/grpc-web/tree/master/client/grpc-web-react-example](url) I created a grpc client by transpiling the ts file to javascript file and it uses grpc-react-native-transport and return the title of the book to display. It was working for ios but when I ran the code in android emulator I'm getting status code 2 i.e. unknown. Please help me in figuring it out.

**What you expected to happen**

I expected the server to return details of book and I would take title of the book and make it display on android emulator.

**How to reproduce it (as minimally and precisely as possible)**:

clone [https://github.com/improbable-eng/grpc-web/tree/master/client/grpc-web-react-example](url), install all dependencies, transpile index.ts file to index.js set default transport as ReactNativeTransport, build an react-native project using "npx reacct-native init <proj_name>" command and copy paste all the proto and js files from client into the proj. Import GetBook() from index.js into App.js, create class component and set the title of the book as the state and insert the state value into view component.

OR

you can check the code at [https://github.com/S7-Works/grpc-react](url) and make an android build and **check.**

**Full logs to relevant components**

<details>
build Logs :
<p>
npm run android

> gRPCAPP1@0.0.1 android
> react-native run-android

info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 967 file(s) to forward-jetify. Using 4 workers...
info JS server already running.
info Installing the app...

> Task :app:stripDebugDebugSymbols UP-TO-DATE
Compatible side by side NDK version was not found.

> Task :app:installDebug
04:31:12 V/ddms: execute: running am get-config
04:31:12 V/ddms: execute 'am get-config' on 'emulator-5554' : EOF hit. Read: -1
04:31:12 V/ddms: execute: returning
Installing APK 'app-debug.apk' on 'Pixel_3a_Edited_1_API_29(AVD) - 10' for app:debug
04:31:12 D/app-debug.apk: Uploading app-debug.apk onto device 'emulator-5554'
04:31:12 D/Device: Uploading file onto device 'emulator-5554'
04:31:12 D/ddms: Reading file permision of D:\s7works\grpc-web\client\gRPCAPP\gRPCAPP1\android\app\build\outputs\apk\debug\app-debug.apk as: rwx------
04:31:14 V/ddms: execute: running pm install -r -t "/data/local/tmp/app-debug.apk"
04:31:16 V/ddms: execute 'pm install -r -t "/data/local/tmp/app-debug.apk"' on 'emulator-5554' : EOF hit. Read: -1
04:31:16 V/ddms: execute: returning
04:31:16 V/ddms: execute: running rm "/data/local/tmp/app-debug.apk"
04:31:16 V/ddms: execute 'rm "/data/local/tmp/app-debug.apk"' on 'emulator-5554' : EOF hit. Read: -1
04:31:16 V/ddms: execute: returning
Installed on 1 device.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 25s
27 actionable tasks: 2 executed, 25 up-to-date
info Connecting to the development server...
info Starting the app on "emulator-5554"...
Starting: Intent { cmp=com.grpcapp1/.MainActivity }
</p>

metro-serer Logs :
<p>
[Fri Feb 12 2021 16:34:11.488]  BUNDLE  ./index.js
[Fri Feb 12 2021 16:34:20.356]  LOG      Running "gRPCAPP1" with {"rootTag":11}
[Fri Feb 12 2021 16:34:20.360]  WARN     Require cycle: node_modules\react-nativ
e\Libraries\Network\fetch.js -> node_modules\whatwg-fetch\dist\fetch.umd.js -> n
ode_modules\react-native\Libraries\Network\fetch.js
Require cycles are allowed, but can result in uninitialized values. Consider ref
actoring to remove the need for a cycle.
App@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:991
13:36
RCTView
RCTView
AppContainer@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=
false:68158:22
[Fri Feb 12 2021 16:34:20.455]  LOG      status  2  msg  null
</p>
</details>

**Anything else we need to know**

Android emulator using Android10(API level 29) and we've set  android:usesCleartextTraffic="true" after encountering an security error.

**Environment**:
- OS (windows10, 64bit ):

**Comment by johanbrandhorst** [comment]
I'm afraid I have no idea how the react native transport works, it was contributed by @pbsf, maybe they can help?

**Comment by pbsf** [comment]
@Akshith-Banda, did you get it to work on the emulator? If you are running the server locally the target ip on the emulator shouldn’t be localhost, but rather 10.0.2.2.
