### ISSUE TITLE
gRCP-web call returning nil response causing a panic

### ISSUE THREAD

**Issue by smartaquarius10** [improbable-eng/grpc-web#881]
Team,

I have made a sample application but while calling it through client I'm getting nil pointer dereference error. I have also tried through chrome but gets "**gRPC requires HTTP/2**". Here is the code

**Server.go**
```
package main

import (
	"context"
	"fmt"
	"net/http"
	"os"
	"strconv"

	"./hellopb"
	"github.com/improbable-eng/grpc-web/go/grpcweb"
	"google.golang.org/grpc"
	"google.golang.org/grpc/grpclog"
)

var port = 50051

type server struct {
}

func (*server) Hello(ctx context.Context, request *hellopb.HelloRequest) (*hellopb.HelloResponse, error) {
	name := request.Name
	response := &hellopb.HelloResponse{
		Greeting: "Hello " + name,
	}
	return response, nil
}

func main() {
	grpcServer := grpc.NewServer()
	hellopb.RegisterHelloServiceServer(grpcServer, &server{})

	wrappedServer := grpcweb.WrapServer(grpcServer)
	handler := func(resp http.ResponseWriter, req *http.Request) {
		wrappedServer.ServeHTTP(resp, req)
	}

	httpServer := http.Server{
		Addr:    fmt.Sprintf(":%d", port),
		Handler: http.HandlerFunc(handler),
	}
	fmt.Printf("Server is listening on http://localhost:%v ...", port)
	if err := httpServer.ListenAndServe(); err != nil {
		grpclog.Fatalf("failed starting http server: %v", err)
	}
}
```
**Client.go**
```
package main

import (
	"context"
	"fmt"
	"log"

	"../hellopb"
	"google.golang.org/grpc"
)

func main() {
	fmt.Println("Hello client ...")
	opts := grpc.WithInsecure()
	cc, err := grpc.Dial("localhost:50051", opts)
	if err != nil {
		log.Fatal(err)
	}
	defer cc.Close()

	client := hellopb.NewHelloServiceClient(cc)
	request := &hellopb.HelloRequest{Name: "Max"}

	resp, er := client.Hello(context.Background(), request)
	if er != nil {
		log.Fatal(er)
	}

	fmt.Printf("Receive response => [%v]", resp.Greeting)
}
```
**Proto.pb**

```
syntax = "proto3";

package hello;
option go_package = "hellopb";

message helloRequest {
    string name = 1;
}

message helloResponse {
    string greeting = 1;
}

service helloService {
    rpc Hello(helloRequest) returns (helloResponse) {};
}
```
The error I'm receiving in client.go at `client.Hello`:

> 2021/02/22 02:19:04 rpc error: code = Unavailable desc = connection closed
> exit status 1 

This issue doesn't comes with tcp listener. The moment I've added grpc-web I don't know why nil output has started coming. I would be grateful if someone can help here. 

Thank you.

**Comment by smartaquarius10** [comment]
@MarcusLongmuir , Sorry for tagging you here. I've tried following this [example ](https://github.com/improbable-eng/grpc-web/tree/master/client/grpc-web-react-example/go). But making some mistake in client.go. Could you please help.

Thank you

**Comment by johanbrandhorst** [comment]
It doesn't look like you are using grpc-web in your client in this example. Are you sure you need grpc-web for your use case? You can't use a Go gRPC client with a grpc-web server like this, you'll need to serve the gRPC server separately. What are you trying to do?

**Comment by smartaquarius10** [comment]
Correct. I by mistake mixed the things. My problem i need to host grpc on azure app services and currently, it supports grpc web only.  

I thought with grpc web we can call through grpc client but we have to make normal http rest type call. 

But the problem is tried that one also with curl command and I only received 200 status ok with blank output.

**Comment by johanbrandhorst** [comment]
You'll need a grpc-web client, which cURL could be but it'd be a bit of work to encode the data correctly. I'm not sure what you're asking of us here, have you tried using our grpc-web client as instructed in the README?

**Comment by johanbrandhorst** [comment]
I'm going to close this as it appears not to be an issue with the library.
