### ISSUE TITLE
Cookies are not getting forwarded from websocket Upgrade request to the backend

### ISSUE THREAD

**Issue by zolkin** [improbable-eng/grpc-web#883]
**Versions of relevant software used** 0.14.0

**What happened** Cookies are not getting forwarded from websocket Upgrade request to the backend

**What you expected to happen** Cookies should be forwarded, if present

**How to reproduce it (as minimally and precisely as possible)**: Reproducible on any websocket Upgrade request carrying cookies

**Comment by Hellysonrp** [comment]
As far as I know, for websockets, you have to explicit allow the headers you want to be forwarded to gRPC.
This is the code that do the filtering:

https://github.com/improbable-eng/grpc-web/blob/e757cdbb2b76e6f16963366ad156b95c47372688/go/grpcweb/wrapper.go#L163-L168

`w.allowedHeaders` is just `["*"]` by default, resulting in all headers being removed.

This might be a bug, but the workaround for the moment is to use `grpcweb.WithAllowedRequestHeaders` to explicit allow the 'Cookie' header.
It's worth to mention that the string comparison is case sensitive.

**Comment by zolkin** [comment]
Cookies are not quite headers, so something like this should be added to forward them:
    cookies := req.Cookies()
...
    for _, cookie := range cookies {
	    req.AddCookie( cookie )
    }

Allowing 'Cookie' header explicitly, or allowing all headers doesn't work for me in this case.

**Comment by zolkin** [comment]
My bad, after recheck, looks like allowing cookie header explicitly is working. Closing the issue.
