### ISSUE TITLE
Codec support

### ISSUE THREAD

**Issue by mackross** [improbable-eng/grpc-web#9]
Love where this is going. Are you thinking [jsonpb](https://godoc.org/github.com/golang/protobuf/jsonpb) codec as an option or default for generated deserializer? IMHO this would be much better than protobufjs as browser decode speed is way better for json than the base64 hackery used in protobufjs.

Either way if it could support multiple codecs as per spec someone else can add.

**Comment by mwitkow** [comment]
There's a couple of things:

a) the [wrapper](https://github.com/improbable-eng/grpc-web/blob/master/go/grpcweb/wrapper.go) doesn't do any coding/decoding at all. It just passes the gRPC frames through without toching them. As such, if your gRPC server uses jsonpb, that's whats gonna be sent in the payload.

b) the canonical implementation in TS and JS will not use [protobuf.js](https://github.com/dcodeIO/protobuf.js). Instead it will use the canonical codegen of the `protoc>=3.2.0`. The decoding functions are code-generated and backed by ArrayBuffers, and we found them to be basically the same speed as JSON deserialization for non-trivial messages (with nesting)

c) we'll make the gRPC Web client library (TS+JS) be built in a layered fashion, so you would be able to extend it by passing your own deserializers/encoders.

But again, we're fairly far away ATM.
