### ISSUE TITLE
Passing metadata  through proxy? 

### ISSUE THREAD

**Issue by endpress** [improbable-eng/grpc-web#91]
I am using grpcwebproxy. My backend server is a node js grpc server. I want pass metadata through   grpc-web-client.

```node js
  const testRequest = new TestRequest();
  testRequest.setUserId('testuserid');

  grpc.unary(MeetService.testHistory, {
    request: testRequest,
    host: host,
    debug: true,
    metadata: {test_token: 'xxxxxxxxxxx'},
    onEnd: res => {
      const { status, statusMessage, headers, message, trailers } = res;
      if (status === Code.OK && message) {
        // console.log('meetHistory.onEnd.message', message.toObject());
      }
      // console.log('meetHistory.onEnd.trailers', trailers);
    }
  });
```

But my node server cannot get metadata. It only can get a user-agent metadata.
```
Metadata { _internal_repr: { 'user-agent': [ 'grpc-go/1.7.0-dev' ] } }
ServerUnaryCall {
  domain: null,
  _events: { error: [Function] },
  _eventsCount: 1,
  _maxListeners: undefined,
  call: Call {},
  cancelled: false,
  metadata: Metadata { _internal_repr: { 'user-agent': [Array] } },
  request: 
   { wrappers_: null,
     messageId_: undefined,
     arrayIndexOffset_: -1,
     array: [ 'testuserid' ],
     pivot_: 1.7976931348623157e+308,
     convertedFloatingPointFields_: {} } }
```

**Comment by endpress** [comment]
My grpc-web-client version is  "grpc-web-client": "^0.3.1",

**Comment by ypoluektovich** [comment]
I'm seeing the same problem. The go proxy thing seems to be swallowing metadata/headers.

**Comment by suusan2go** [comment]
I have the same problem. My backend server is a SpringBoot server(with grpc-java using Kotlin.)

**Comment by mwitkow** [comment]
Indeed. The previous code of grpc-proxy, that the current grpc-webproxy relies on, relied on the implicit forwarding of metadata inside the `context.Context` between gRPC-Go calls. This behaviour has changed in gRPC-Go 1.5. 

The fix requires a change to upstream grpc-go and is discussed in 
https://github.com/mwitkow/grpc-proxy/issues/19

**Comment by MarcusLongmuir** [comment]
@endpress / @ypoluektovich  / @suusan2go: Please re-open if [latest master](https://github.com/improbable-eng/grpc-web/commit/be0c2b345bd05d234ac112af05f1f1ae28e306ff) does not fix the issue you're seeing.

**Comment by ypoluektovich** [comment]
It does for me. Thanks!
