### ISSUE TITLE
go/grpcwebproxy installation failed with go 1.16 (but works with 1.15)

### ISSUE THREAD

**Issue by stanley-cheung** [improbable-eng/grpc-web#910]
**Versions of relevant software used**
0.14.0
**What happened**
Got an installation error with go 1.16, when trying to install go/grpcwebproxy.

```
Step 11/14 : RUN dep ensure &&   go install ./go/grpcwebproxy
 ---> Running in 0b2cd714627b
go: cannot find main module, but found Gopkg.lock in /go/src/github.com/improbable-eng/grpc-web
	to create a module there, run:
	go mod init
```

Worked if I switch back to go 1.15.

**How to reproduce it (as minimally and precisely as possible)**:
Full dockerfile here: https://github.com/grpc/grpc-web/blob/master/net/grpc/gateway/docker/grpcwebproxy/Dockerfile

**Comment by stanley-cheung** [comment]
Adding a go environment variable `GO111MODULE=auto` seems to have solved the problem:

```
Step 11/14 : RUN dep ensure &&   go env -w GO111MODULE=auto &&   go install ./go/grpcwebproxy
 ---> Running in 350370b1ca82
Removing intermediate container 350370b1ca82
 ---> 87be384084db
```

This page https://golang.org/ref/mod#mod-commands specifically mentioned the behavior change between 1.15 and 1.16.

**Comment by johanbrandhorst** [comment]
Hi Stanley, thanks for the issue! Is there anything we need to do here? I suppose finally migrating to go modules would be one thing. Do you think we need to update our docs?

**Comment by stanley-cheung** [comment]
Up to you guys. I guess updating the docs in the meantime will be helpful, especially for users who aren't exactly very familiar with the Go ecosystem. Thanks!

**Comment by johanbrandhorst** [comment]
We've now migrated the repo to modules, so this should be fixed
