### ISSUE TITLE
grpc-web example don't work 

### ISSUE THREAD

**Issue by orel509** [improbable-eng/grpc-web#920]
Hi, I tried using the example in the tutorial of grpc-web(link: https://grpc.io/docs/platforms/web/basics/), but I am receiving the following error:
POST http://localhost:8080/EchoService/Echo net::ERR_CONTENT_LENGTH_MISMATCH 503 (Service Unavailable)
I am using webpack as in the tutorial, using envoy as proxy in localhost(where my grpc server is running and where I access the website from) my website host is AWS ubuntu machine with a simple http server using the http-server command.

Any help would be highly appreciated.

**Comment by johanbrandhorst** [comment]
Hi, that tutorial is written for a different project; https://github.com/grpc/grpc-web. We can't help you with that issue I'm afraid.
