### ISSUE TITLE
Websockets ?

### ISSUE THREAD

**Issue by gedw99** [improbable-eng/grpc-web#94]
Does this handle streaming over websockets for doing push upwards from a golang server ?

**Comment by easyCZ** [comment]
Currently websockets are not supported and neither is bidirectional streaming. @MarcusLongmuir is working on adding websocket support - https://github.com/MarcusLongmuir/grpc-web/tree/websockets

**Comment by gedw99** [comment]
thanks @easyCZ :)

Have been using this: 
https://github.com/johanbrandhorst/grpcweb-example

& for react front end this:
https://github.com/myitcv/react

It allows using protobuf for all Gets and Sets with a react front end.
All the react code is written in golang too. Transpiled with gopherjs.

Not saying its the way to go, as there are drawbacks for sure.

But just putting here for reference. 
@MarcusLongmuir

**Comment by johanbrandhorst** [comment]
Only just discovered this issue, I'm the author of the GopherJS gRPC-Web bindings that add the websocket proxy for client-side and bidirectional streaming, happy to provide any lessons learned for getting this kind of thing into gRPC-Web.

**Comment by gedw99** [comment]
@johanbrandhorst that woudl be great.

Just for fun, I am playing around with exposing dgraph into react at the moment with gopherjs binding.

**Comment by abeMedia** [comment]
Any update on websockets support?

**Comment by easyCZ** [comment]
Please see #137

**Comment by dbskccc** [comment]
since  websocket  support has merged(#137 ), does any one know client stream is possible now？

**Comment by johanbrandhorst** [comment]
Yes, client side streaming and bidirectional streaming is possible with websockets enabled in the proxy

**Comment by gedw99** [comment]
:) woooh

**Comment by jonnyreeves** [comment]
Websocket support is available on 0.6 which can be installed on the client
using `npm install grpc-web-client@beta`.

Documentation for websocket support needs to be added before a stable
release can be made.

**Comment by dbskccc** [comment]
great news, so what's the next release time? and a bidi example would be helpful.

**Comment by johanbrandhorst** [comment]
The tests contain examples of using bidi streaming: https://github.com/improbable-eng/grpc-web/blob/master/test/ts/src/client.websocket.spec.ts#L77

**Comment by matthijskooijman** [comment]
IIUC, the new websocket support will do an HTTP request for a single method call, which is then upgraded to a websocket. The websocket is used to transport the request body and the response, which allows streaming.

The new websocket support will *not* use a single websocket connection and multiplex multiple requests over this single connection (e.g. like normally happens on the grpc HTTP/2 transport).

Did I get that right?

**Comment by johanbrandhorst** [comment]
Yes, that's right. It's not using websockets for request multiplexing. If you're interested, I think the websocket proxy code is an example of very nicely using the Go `net/http` interfaces to encapsulate this fairly complex code: https://github.com/improbable-eng/grpc-web/blob/master/go/grpcweb/websocket_wrapper.go

**Comment by MarcusLongmuir** [comment]
Websocket support has been released in `0.6.1`, which is currently `@latest` on npm.

As this is still opt-in support it must be enabled explicitly on both the client and server:

Enable Websocket support in the grpc-web Golang package:
```go
grpcweb.WrapServer(grpcServer, grpcweb.WithWebsockets(true), grpcweb.WithWebsocketOriginFunc(func(req *http.Request) bool {
	return true
}))
```

Specify that the client should use the Websocket transport factory for the rpc:
```ts
const myClient = grpc.client(MyService.MyMethod, {
    host: myHost,
    transport: grpc.WebsocketTransportFactory,
});
client.send(myFirstMsg);
client.send(mySecondMsg);
client.finishSend();
```

Whilst you can use `transport: grpc.WebsocketTransportFactory` with `grpc.unary` and `grpc.invoke`, only `grpc.client` allows client-streaming and bidi-streaming rpcs.

**Comment by gedw99** [comment]
@johanbrandhorst Have you tried this with the gopherjs client yet ? Not sure if you already are using it.

**Comment by johanbrandhorst** [comment]
My gopherjs grpc-web library has been using the websocket transport by default since release [v0.6.0](https://github.com/johanbrandhorst/protobuf/releases/tag/v0.6.0).
