### ISSUE TITLE
How to configure TLS @improbable-eng/grpc-web for NextJS based application?

### ISSUE THREAD

**Issue by softshipper** [improbable-eng/grpc-web#981]
Hi all 

I am using NextJS to build my web application. The following React element uses `grpc.invoke` to communicate with GRPC service:
```
export default function Index({user}: OverviewProps) {

    useEffect(() => {
        grpc.invoke(RepoService.ListRepos, {
            host: "http://localhost:9000",
            request: listReq,
            onMessage: (msg) => {
                console.log(msg);
            },
            onEnd:(code:grpc.Code,msg:string | undefined | number, trailers: grpc.Metadata)=>{
                console.log(code);
                if(code == grpc.Code.OK){
                    console.log("Worked")
                }else{
                    console.log("Not Working")
                }
            },
            debug: true

        })

    }, [])

    return wrapWithLayout(
        <p>Hi {user.nickname}</p>
    );
}
``` 
The backend service is secured with TLS. On the client-side, I have to load somehow the certificate into the client. The question is, how to load the certificate into the client-side that it can communicate with the backend service?  

Thanks

**Comment by johanbrandhorst** [comment]
Hi! There isn't anything you can do in your client to handle this - the user has to accept the certificate in their browser. The easiest and safest way to do this is to use a certificate authority like Let's Encrypt to issue the certificate for your server.

I'm going to close this as it's not related to the library, but feel free to respond if you need more help.

**Comment by softshipper** [comment]
Hi @johanbrandhorst 
Last question, does improbable-eng/grpc-web supports [Token-based authentication](https://grpc.io/docs/guides/auth/)? 

Thanks

**Comment by johanbrandhorst** [comment]
The best the grpc-web client can do is set custom authentication headers, or use cookies.

**Comment by softshipper** [comment]
How to use cookies or set custom authentication headers on grpc-web client? Could you please provide an example?

**Comment by johanbrandhorst** [comment]
Hi, I'm not entirely sure if we allow setting headers on requests, I've mostly implemented cookie based authentication. You can read about cookie based authentication here: https://auth0.com/docs/sessions/cookies. It is not specific to our library.
